<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['InvoiceDelivery.!error.libxml_required'] = "Les extensions libxml et simplexml sont requises pour l'envoi de factures.";
$lang['InvoiceDelivery.deliverinvoices.interfax_subject'] = "Facture #%1\$s"; // %1$s is the invoice number (or the first invoice number in a group of several)
$lang['InvoiceDelivery.deliverinvoices.postalmethods_description'] = "Facture # %1\$s"; // %1$s is the invoice number (or the first invoice number in a group of several);
?>