<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminFilter.index.page_title'] = "Envoi de masse > Filtre";
$lang['AdminFilter.text.all'] = "Tout";
$lang['AdminFilter.!tooltip.client_group_ids'] = "Les clients doivent appartenir à l'un des groupes sélectionnés.";
$lang['AdminFilter.!tooltip.client_statuses'] = "Les clients doivent appartenir à l'un des statuts sélectionnés.";
$lang['AdminFilter.!tooltip.languages'] = "Les clients doivent avoir leur langue défini dans une des langues sélectionnées";
$lang['AdminFilter.!tooltip.contact_types'] = "Les contacts doivent appartenir à l'un des types sélectionnés.";
$lang['AdminFilter.!tooltip.client_start_date'] = "Les clients doivent avoir été créés à ou après cette date. Laissez ce champ vide pour l'ignorer.";
$lang['AdminFilter.!tooltip.client_end_date'] = "Les clients doivent avoir été créés à ou avant cette date. Laissez ce champ vide pour l'ignorer.";
$lang['AdminFilter.!tooltip.filter_services'] = "Si cette option est cochée, les clients doivent également correspondre aux critères de filtre du service.";
$lang['AdminFilter.!tooltip.service_renew_date'] = "Les services doivent être renouvelés à, ou avant cette date. Laissez ce champ vide pour l'ignorer.";
$lang['AdminFilter.!tooltip.service_statuses'] = "Les services doivent être dans l'un des statuts sélectionnés.";
$lang['AdminFilter.!tooltip.module_id'] = "Les services doivent appartenir au module sélectionné";
$lang['AdminFilter.!tooltip.service_parent_type'] = "Les services seront ensuite filtrés par package ou par module.";
$lang['AdminFilter.!tooltip.selected_packages'] = "Les services doivent appartenir à l'un des packages sélectionnés.";
$lang['AdminFilter.!tooltip.include_all_services'] = "Si cette option est cochée, tous les services seront inclus. Les contacts recevront potentiellement plusieurs e-mails; un pour chaque service correspondant. Si cette case est décochée, les contacts ne recevront qu'un seul e-mail contenant le premier service correspondant.";
$lang['AdminFilter.index.boxtitle'] = "Envoi de masse";
$lang['AdminFilter.index.heading.client_filters'] = "Options de filtre du client";
$lang['AdminFilter.index.form.client_group_ids'] = "Groupes de clients";
$lang['AdminFilter.index.form.client_statuses'] = "États du client";
$lang['AdminFilter.index.form.languages'] = "Langues";
$lang['AdminFilter.index.form.contact_types'] = "Types de contact";
$lang['AdminFilter.index.form.client_start_date'] = "Date de début de la création du client";
$lang['AdminFilter.index.form.client_end_date'] = "Date de fin de création du client";
$lang['AdminFilter.index.form.filter_services'] = "Filtrer par services";
$lang['AdminFilter.index.heading.service_filters'] = "Options de filtre du service";
$lang['AdminFilter.index.form.service_renew_date'] = "Renouvellement par";
$lang['AdminFilter.index.form.service_statuses'] = "Status des services";
$lang['AdminFilter.index.form.service_parent_type'] = "Forfait/Module";
$lang['AdminFilter.index.form.service_parent_type_package'] = "Forfait";
$lang['AdminFilter.index.form.service_parent_type_module'] = "Module";
$lang['AdminFilter.index.form.package_group'] = "Filtre du groupe de forfait";
$lang['AdminFilter.index.form.selected_packages'] = "Forfaits sélectionnés";
$lang['AdminFilter.index.form.selectable_packages'] = "Forfaits disponibles";
$lang['AdminFilter.index.form.module_id'] = "Module";
$lang['AdminFilter.index.form.include_all_services'] = "Inclure pour tous les services";
$lang['AdminFilter.index.form.continue'] = "Continuer";
$lang['AdminFilter.index.form.export'] = "Exporter";
$lang['AdminFilter.!tooltip.receive_email_marketing'] = "Si cette option est cochée, seuls les clients ayant choisi marketing/offres recevront cet e-mail";
$lang['AdminFilter.index.form.receive_email_marketing'] = "Limiter aux clients commercialisables";
?>