<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompose.index.page_title'] = "Courrier de masse - Composer";
$lang['AdminCompose.!tooltip.log'] = "Si cette case est cochée, tous les courriels envoyés seront enregistrés dans Blesta";
$lang['AdminCompose.index.boxtitle'] = "Écrire un e-mail";
$lang['AdminCompose.index.form.from_name'] = "Expéditeur";
$lang['AdminCompose.index.form.from_address'] = "Expéditeur";
$lang['AdminCompose.index.form.subject'] = "Sujet";
$lang['AdminCompose.index.form.html'] = "HTML";
$lang['AdminCompose.index.form.text'] = "Texte";
$lang['AdminCompose.index.form.log'] = "Enregistrer les e-mails";
$lang['AdminCompose.index.text.note'] = "Si rien n'est défini dans texte, ce sera générée automatiquement à partir de la version HTML.";
$lang['AdminCompose.index.heading_client_tags'] = "Tags client";
$lang['AdminCompose.index.heading_service_tags'] = "Tags de service";
$lang['AdminCompose.index.link_back'] = "Retour";
$lang['AdminCompose.index.form.preview'] = "Aperçu";
$lang['AdminCompose.preview.boxtitle'] = "Aperçu de l'envoi";
$lang['AdminCompose.preview.email_total'] = "Nombre total de contacts à envoyer par e-mail: %1\$s"; // %1$s is the total number of contacts
$lang['AdminCompose.preview.heading.email_sample'] = "Exemple d'e-mail";
$lang['AdminCompose.preview.text_name'] = "De: %1\$s %2\$s"; // %1$s is the email's from name, %2$s is the email's from address
$lang['AdminCompose.preview.text_subject'] = "Sujet: %1\$s"; // %1$s
$lang['AdminCompose.preview.link_back'] = "Retour";
$lang['AdminCompose.preview.form.send'] = "Envoyer";
?>