<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!error.export_found'] = "L'exportation est introuvable sur le système de fichiers.";
$lang['AdminMain.index.page_title'] = "E-mail de masse";
$lang['AdminMain.index.boxtitle'] = "Tâches d'e-mail de masse";
$lang['AdminMain.index.categorylink_compose'] = "Créer un nouveau mailing";
$lang['AdminMain.index.job_task_total'] = "%1\$s / %2\$s"; // %1$s is the number of mailing tasks completed, %2$s is the total number of mailing tasks
$lang['AdminMain.index.heading_date'] = "Date ajoutée";
$lang['AdminMain.index.heading_type'] = "Type";
$lang['AdminMain.index.heading_status'] = "Statut";
$lang['AdminMain.index.heading_complete'] = "Terminé";
$lang['AdminMain.index.heading_options'] = "Options";
$lang['AdminMain.index.option_export'] = "Exporter";
$lang['AdminMain.index.type.email'] = "E-mail";
$lang['AdminMain.index.type.export'] = "Exporter";
$lang['AdminMain.index.email_to'] = "À";
$lang['AdminMain.index.email_from'] = "De";
$lang['AdminMain.index.email_subject'] = "Sujet";
$lang['AdminMain.index.email_to_recipients'] = "%1\$s destinataire(s)"; // %1$s is the number of email recipients
$lang['AdminMain.index.no_export_details'] = "Il n'y a pas de détails disponibles sur l'exportation.";
$lang['AdminMain.index.no_results'] = "Il n'y a actuellement aucune offre d'emploi.";
?>