<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.export.id_code'] = "ID du client";
$lang['Config.export.first_name'] = "Prénom";
$lang['Config.export.last_name'] = "Nom";
$lang['Config.export.company'] = "Société";
$lang['Config.export.email'] = "E-mail";
$lang['Config.export.date_added'] = "Date d'ajout";
$lang['Config.export.package_name'] = "Paquet";
$lang['Config.export.service_name'] = "Service";
$lang['Config.export.service_date_renews'] = "Renouveler la date ";
$lang['Config.export.module_name'] = "Module";
$lang['Config.export.module_label'] = "Ligne de module";
?>