<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerPlugin.name'] = "Messagerie de masse";
$lang['MassMailerPlugin.nav_secondary_staff.admin_main'] = "Messagerie de masse";
$lang['MassMailerPlugin.permission.admin_main'] = "Listes de diffusion de masse";
$lang['MassMailerPlugin.permission.admin_filter'] = "Mass Mailer Filters";
$lang['MassMailerPlugin.permission.admin_compose'] = "Messagerie de masse composer un e-mail";
$lang['MassMailerPlugin.cron.export_name'] = "Créer un export mailing";
$lang['MassMailerPlugin.cron.export_desc'] = "Construit un fichier CSV pour tout tâche de publipostage en attente d'exportation.";
$lang['MassMailerPlugin.cron.mass_mail_name'] = "Envoyer un e-mail en masse";
$lang['MassMailerPlugin.cron.mass_mail_desc'] = "Envoie des e-mail pour toute tâche d'envoi en attente.";
?>