<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerController.!success.mail_job_added'] = "La tâche de mailing a été mis en file d'attente avec succès. Les e-mails seront envoyés via cron.";
$lang['MassMailerController.!success.export_job_added'] = "L'exportation a été mise en file d'attente avec succès. Il sera disponible sur la page de listing une fois qu’il aura été traité via cron.";
?>