<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerEmails.!error.job_id.valid'] = "ID de tâche invalide.";
$lang['MassMailerEmails.!error.job_id.unique'] = "Un e-mail a déjà été attribué à la tâche.";
$lang['MassMailerEmails.!error.from_name.empty'] = "S'il vous plait entrez un nom";
$lang['MassMailerEmails.!error.from_address.valid'] = "Veuillez entrer une adresse e-mail valide.";
$lang['MassMailerEmails.!error.subject.empty'] = "Veuillez entrer un sujet.";
$lang['MassMailerEmails.!error.html.empty'] = "S'il vous plait entrez un contenu HTML";
$lang['MassMailerEmails.!error.log.valid'] = "L'option de journal doit être définie sur 0 ou 1.";
?>