<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Tags.client.id_code'] = "ID";
$lang['Tags.client.status'] = "Statut";
$lang['Tags.contact.first_name'] = "Prénom";
$lang['Tags.contact.last_name'] = "Nom de famille";
$lang['Tags.contact.company'] = "Nom de la société";
$lang['Tags.contact.address1'] = "Adresse 1";
$lang['Tags.contact.address2'] = "Adresse 2";
$lang['Tags.contact.city'] = "Ville";
$lang['Tags.contact.state'] = "Etat";
$lang['Tags.contact.country'] = "Pays";
$lang['Tags.contact.zip'] = "Code postal";
$lang['Tags.contact.email'] = "Email";
$lang['Tags.contact.date_added'] = "Date du membre";
$lang['Tags.package.name'] = "Nom du forfait";
$lang['Tags.package.description'] = "Description du package";
$lang['Tags.package.description_html'] = "Description HTML du forfait";
$lang['Tags.package.status'] = "Statut du forfait";
$lang['Tags.service.name'] = "Étiquette";
$lang['Tags.service.date_added'] = "Date ajoutée";
$lang['Tags.service.date_renews'] = "Date de renouvellement";
$lang['Tags.service.date_last_renewed'] = "Date du dernier renouvellement";
$lang['Tags.service.date_suspended'] = "Date suspendue";
$lang['Tags.service.date_canceled'] = "Date d'annulation";
$lang['Tags.service.status'] = "Statut";
$lang['Tags.module.name'] = "Nom du module";
$lang['Tags.module.label'] = "Étiquette de ligne de module";
?>