<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Payumoney.name'] = "Payumoney";
$lang['Payumoney.merchant_key'] = "Clé du marchand";
$lang['Payumoney.merchant_salt'] = "Sel marchand";
$lang['Payumoney.auth_header'] = "En-tête d'autorisation";
$lang['Payumoney.auth_header_note'] = "L'en-tête d'autorisation se trouve dans le tableau de bord Payumoney sous Manage Account -> My Account -> Merchant Key-Salt.";
$lang['Payumoney.merchant_key_note'] = "La clé du commerçant se trouve sur le tableau de bord Payumoney sous Manage Account -> My Account -> Merchant Key-Salt.";
$lang['Payumoney.merchant_salt_note'] = "Le sel marchand se trouve sur le tableau de bord Payumoney sous Manage Account -> My Account -> Merchant Key-Salt.";
$lang['Payumoney.test_mode'] = "Mode sandbox";
$lang['Payumoney.test_mode_note'] = "Activer cette option utilisera le sandbox de Payumoney. Activez cette option uniquement si vous testez avec un compte Payumoney Sandbox.";
$lang['Payumoney.buildprocess.submit'] = "Payer via Payumoney";
$lang['Payumoney.!error.merchant_key.valid'] = "Veuillez entrer une clé de commerçant valide.";
$lang['Payumoney.!error.merchant_salt.valid'] = "Veuillez entrer un sel valide.";
$lang['Payumoney.!error.auth_header.valid'] = "Veuillez entrer un en-tête d'autorisation valide.";
$lang['Payumoney.!error.key.valid'] = "Clé de marchand invalide.";
$lang['Payumoney.!error.invalid_token.response'] = "Payumoney a répondu avec un jeton invalide.";
?>