<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Vesta.name'] = "Vesta";
$lang['Vesta.module_row'] = "Serveur";
$lang['Vesta.module_row_plural'] = "Serveurs";
$lang['Vesta.module_group'] = "Groupe de serveurs";
$lang['Vesta.tab_stats'] = "Statistiques";
$lang['Vesta.tab_client_actions'] = "Actions";
$lang['Vesta.submit'] = "Envoyer";
$lang['Vesta.tab_stats.info.WEB_DOMAINS'] = "Domaines";
$lang['Vesta.tab_stats.info.WEB_ALIASES'] = "Alias";
$lang['Vesta.tab_stats.info.DNS_DOMAINS'] = "Domaines DNS";
$lang['Vesta.tab_stats.info.DNS_RECORDS'] = "Enregistrements DNS";
$lang['Vesta.tab_stats.info.MAIL_DOMAINS'] = "Domaines de messagerie";
$lang['Vesta.tab_stats.info.MAIL_ACCOUNTS'] = "Comptes de messagerie";
$lang['Vesta.tab_stats.info.DATABASES'] = "Bases de données";
$lang['Vesta.tab_stats.info.CRON_JOBS'] = "Tâches Cron";
$lang['Vesta.tab_stats.info.DISK_QUOTA'] = "Utilisation du disque";
$lang['Vesta.tab_stats.info.BANDWIDTH'] = "Utilisation de la bande passante";
$lang['Vesta.tab_stats.info.BACKUPS'] = "Sauvegardes";
$lang['Vesta.add_module_row'] = "Ajouter un serveur";
$lang['Vesta.add_module_group'] = "Ajouter un groupe de serveurs";
$lang['Vesta.manage.module_rows_title'] = "Serveurs";
$lang['Vesta.manage.module_groups_title'] = "Groupes de serveurs";
$lang['Vesta.manage.module_rows_heading.name'] = "Étiquette du serveur";
$lang['Vesta.manage.module_rows_heading.hostname'] = "Nom d'hôte";
$lang['Vesta.manage.module_rows_heading.port'] = "Port";
$lang['Vesta.manage.module_rows_heading.accounts'] = "Comptes";
$lang['Vesta.manage.module_rows_heading.options'] = "Options";
$lang['Vesta.manage.module_groups_heading.name'] = "Nom de groupe";
$lang['Vesta.manage.module_groups_heading.servers'] = "Nombre de serveurs";
$lang['Vesta.manage.module_groups_heading.options'] = "Options";
$lang['Vesta.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Vesta.manage.module_rows.edit'] = "Modifier";
$lang['Vesta.manage.module_groups.edit'] = "Modifier";
$lang['Vesta.manage.module_rows.delete'] = "Supprimer";
$lang['Vesta.manage.module_groups.delete'] = "Supprimer";
$lang['Vesta.manage.module_rows.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer ce serveur?";
$lang['Vesta.manage.module_groups.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer ce groupe de serveurs?";
$lang['Vesta.manage.module_rows_no_results'] = "Il n'y a pas de serveurs.";
$lang['Vesta.manage.module_groups_no_results'] = "Il n'y a pas de groupes de serveurs.";
$lang['Vesta.order_options.first'] = "Premier serveur non complet";
$lang['Vesta.add_row.box_title'] = "Ajouter un serveur Vesta";
$lang['Vesta.add_row.basic_title'] = "Paramètres de base";
$lang['Vesta.add_row.remove_name_server'] = "Supprimer";
$lang['Vesta.add_row.add_btn'] = "Ajouter un serveur";
$lang['Vesta.edit_row.box_title'] = "Modifier le serveur Vesta";
$lang['Vesta.edit_row.basic_title'] = "Paramètres de base";
$lang['Vesta.edit_row.remove_name_server'] = "Supprimer";
$lang['Vesta.edit_row.add_btn'] = "Modifier le serveur";
$lang['Vesta.row_meta.server_name'] = "Étiquette du serveur";
$lang['Vesta.row_meta.host_name'] = "Nom d'hôte";
$lang['Vesta.row_meta.user_name'] = "Nom d'utilisateur";
$lang['Vesta.row_meta.password'] = "Mot de passe";
$lang['Vesta.row_meta.port'] = "Port";
$lang['Vesta.row_meta.use_ssl'] = "Utiliser SSL lors de la connexion à l'API (recommandé)";
$lang['Vesta.package_fields.package_name'] = "Nom du forfait Vesta";
$lang['Vesta.package_fields.package_name_how_to'] = "Vous pouvez obtenir le nom du forfait en vous connectant à votre Panneau de configuration Vesta> Packages";
$lang['Vesta.service_field.domain'] = "Nom de domaine";
$lang['Vesta.service_field.username'] = "Nom d'utilisateur";
$lang['Vesta.service_field.password'] = "Mot de passe";
$lang['Vesta.stored_locally_only'] = "Ce champ sera modifier localement uniquement";
$lang['Vesta.service_info.hostname'] = "Nom d'hôte";
$lang['Vesta.service_info.username'] = "Nom d'utilisateur";
$lang['Vesta.service_info.password'] = "Mot de passe";
$lang['Vesta.service_info.server'] = "Serveur";
$lang['Vesta.service_info.options'] = "Options";
$lang['Vesta.service_info.option_login'] = "Se connecter";
$lang['Vesta.tab_client_actions.change_password'] = "Changer le mot de passe";
$lang['Vesta.tab_client_actions.password'] = "Mot de passe";
$lang['Vesta.tab_client_actions.confirm_password'] = "Confirmer le mot de passe";
$lang['Vesta.tab_stats.info_heading.field'] = "Champ";
$lang['Vesta.tab_stats.info_heading.value'] = "Valeur";
$lang['Vesta.!error.server_name_valid'] = "Vous devez entrer un Label pour le serveur";
$lang['Vesta.!error.host_name_valid'] = "Le nom d'hôte semble être invalide.";
$lang['Vesta.!error.user_name_valid'] = "Le nom d'utilisateur semble être invalide.";
$lang['Vesta.!error.port_valid'] = "Le port semble être invalide.";
$lang['Vesta.!error.password_valid'] = "Le mot de passe semble être invalide.";
$lang['Vesta.!error.meta[package_name].empty'] = "Veuillez entrer le nom du forfait Vesta.";
$lang['Vesta.!error.api.internal'] = "Une erreur interne s'est produite ou le serveur n'a pas répondu à la demande.";
$lang['Vesta.!error.module_row.missing'] = "Une erreur interne est survenue. La ligne de module est indisponible.";
$lang['Vesta.!error.domain.format'] = "Veuillez entrer un nom de domaine valide, par exemple domain.com.";
$lang['Vesta.!error.domain.test'] = "Le nom de domaine ne peut pas commencer par 'test'.";
$lang['Vesta.!error.user_name.empty'] = "Le nom d'utilisateur ne peut être vide";
$lang['Vesta.!error.password.valid'] = "Le mot de passe doit comporter au moins 8 caractères.";
$lang['Vesta.!error.actions_password.valid'] = "Les champs Mot de passe et Confirmer le mot de passe ne peuvent pas être vides.";
?>