<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ReassignPricingServices.!error.pricing_id.exists'] = "ID de prix invalide.";
$lang['ReassignPricingServices.!error.pricing_id.company'] = "L'ID de prix n'appartient pas à la même société que le service";
$lang['ReassignPricingServices.!error.module_row_id.exists'] = "ID de ligne de module incorrect à partir de l'ID de prix donné.";
$lang['ReassignPricingServices.!error.module_row_id.company'] = "L'ID de ligne de module n'appartient pas à la même société que le service.";
$lang['ReassignPricingServices.!error.service_id.exists'] = "ID de service invalide.";
?>