<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Payza.name'] = "Payza";
$lang['Payza.merchant_id'] = "Courriel du marchand";
$lang['Payza.merchant_id_note'] = "Entrez votre compte marchand adresse e-mail. Ex: nom_du_marchand@domaine.com";
$lang['Payza.api_security_code'] = "Mot de passe de l'API";
$lang['Payza.api_password_note'] = "Le mot de passe de l'API est requis pour traiter les remboursement par AlertPay.";
$lang['Payza.test_mode'] = "Mode \"Carré de sable\"";
$lang['Payza.test_mode_note'] = "L'activation de cette option sera d'utiliser l'environnement de test AlertPay. N'utilisez cette option que si vous testez avec un compte AlertPay sandbox.";
$lang['Payza.buildprocess.submit'] = "Payer avec Payza";
$lang['Payza.!error.merchant_id.valid'] = "Veuillez entrer une adresse courriel de compte marchand valide.";
$lang['Payza.!error.security.response'] = "Les remboursements ne peuvent pas être traitées sans mettre un mot de passe de l'API avec Payza";
$lang['Payza.!error.invalid_token.response'] = "Payza a répondu avec un jeton invalide.";
?>