<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PaypalPaymentsStandard.name'] = "PayPal Payments Standard";
$lang['PaypalPaymentsStandard.account_id'] = "Courriel du compte PayPal";
$lang['PaypalPaymentsStandard.page_style'] = "Nom du style de page";
$lang['PaypalPaymentsStandard.page_style_note'] = "Le nom du style de la page personnalisée de paiement que vous avez créé dans Paypal. Laissez blanc si votre page de paiement est celle par défaut.";
$lang['PaypalPaymentsStandard.dev_mode'] = "Mode développeur";
$lang['PaypalPaymentsStandard.dev_mode_note'] = "L'activation de cette option affichera les transactions à l'environnement de test PayPal. N'utilisez cette option que si vous testez avec un compte PayPal Sandbox.";
$lang['PaypalPaymentsStandard.api_username'] = "Nom d'utilisateur API";
$lang['PaypalPaymentsStandard.api_username_note'] = "Ceci, en plus du mot de passe et de la signature API, sont requis afin de traiter les remboursements via Paypal.";
$lang['PaypalPaymentsStandard.api_password'] = "Mot de passe d'API";
$lang['PaypalPaymentsStandard.api_signature'] = "Signature API";
$lang['PaypalPaymentsStandard.pay_type'] = "Options de paiement";
$lang['PaypalPaymentsStandard.pay_type_onetime'] = "Paiements uniques seulement";
$lang['PaypalPaymentsStandard.pay_type_subscribe'] = "Paiements d'abonnement uniquement";
$lang['PaypalPaymentsStandard.pay_type_both'] = "Paiements ponctuels et d'abonnement lorsque cela est possible.";
$lang['PaypalPaymentsStandard.modify'] = "Permettre aux utilisateur de modifier les abonnements en cours et d'en créer des nouveaux.";
$lang['PaypalPaymentsStandard.buildprocess.submit'] = "Payer avec PayPal";
$lang['PaypalPaymentsStandard.!error.account_id.valid'] = "Vous devez entrer une adresse de courriel valide.";
$lang['PaypalPaymentsStandard.!error.dev_mode.valid'] = "Le mode développeur doit être mis sur 'Vrai' si donné.";
?>