<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CWatch.name'] = "CWatch";
$lang['CWatch.module_row.name'] = "Identification";
$lang['CWatch.module_row_plural.name'] = "Informations d'identification";
$lang['CWatch.!success.sftp_test'] = "La connexion SFTP a réussi!";
$lang['CWatch.!tooltip.initiateDns'] = "S'il faut lancer une analyse des enregistrements DNS.";
$lang['CWatch.!tooltip.autoSsl'] = "S'il faut installer un certificat FREE SSL de Comodo.";
$lang['CWatch.!error.cwatch_email.format'] = "Format d'e-mail invalide.";
$lang['CWatch.!error.cwatch_email.unique'] = "Un client avec l'e-mail donné existe déjà.";
$lang['CWatch.!error.cwatch_firstname.empty'] = "Entrez un prénom.";
$lang['CWatch.!error.cwatch_lastname.empty'] = "Entrez un nom.";
$lang['CWatch.!error.cwatch_country.length'] = "Pays invalide.";
$lang['CWatch.!error.limit_exceeded'] = "Le nombre de licences actuellement sur ce compte dépasse la limite entrée. Veuillez supprimer les licences avant de réduire votre limite.";
$lang['CWatch.!error.api.internal'] = "Une erreur interne s'est produite, ou le serveur n'a pas répondu à la demande.";
$lang['CWatch.!error.sftp_test'] = "La connexion SFTP a échoué! Veuillez vérifier vos paramètres puis essayez une nouvelle fois.";
$lang['CWatch.manage.boxtitle'] = "Gérer les informations d'identification CWatch";
$lang['CWatch.manage.title'] = "Comptes API";
$lang['CWatch.manage.add_module_row'] = "Ajouter des informations d'identification API";
$lang['CWatch.manage.option_edit'] = "Modifier";
$lang['CWatch.manage.delete'] = "Supprimer";
$lang['CWatch.manage.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer cet utilisateur?";
$lang['CWatch.manage.no_results'] = "Aucun compte trouvé";
$lang['CWatch.manage.heading_username'] = "Nom d'utilisateur";
$lang['CWatch.manage.heading_options'] = "Options";
$lang['CWatch.package_fields.package_type'] = "Type de forfait";
$lang['CWatch.package_fields.tooltip.package_type'] = "Les forfaits de licences uniques ne fournissent qu'une seule licence dans cWatch du type sélectionné ici par le forfait. Les forfaits de licences multiples utilisent des options configurables pour permettre aux clients de commander un nombre variable de licences de différents types.";
$lang['CWatch.package_fields.license_type'] = "Type de licence";
$lang['CWatch.package_fields.license_basic_detection'] = "Basic";
$lang['CWatch.package_fields.license_pro'] = "Professionnel";
$lang['CWatch.package_fields.license_pro_free'] = "Essai professionnel";
$lang['CWatch.package_fields.license_pro_free_60d'] = "Essai professionnel prolongé";
$lang['CWatch.package_fields.license_premium'] = "Premium";
$lang['CWatch.package_fields.license_premium_free'] = "Essai Premium";
$lang['CWatch.package_fields.license_premium_free_60d'] = "Essai Premium étendu";
$lang['CWatch.packagetypes.single_license'] = "Licence unique";
$lang['CWatch.packagetypes.multi_license'] = "Licence Multi";
$lang['Cwatch.service_field.domain'] = "Domaine";
$lang['Cwatch.service_field.email'] = "E-mail";
$lang['Cwatch.service_field.firstname'] = "Prénom";
$lang['Cwatch.service_field.lastname'] = "Nom";
$lang['Cwatch.service_field.country'] = "Pays";
$lang['CWatch.add_row.box_title'] = "Ajouter un compte API";
$lang['CWatch.add_row.basic_title'] = "Paramètres utilisateur";
$lang['CWatch.add_row.field_username'] = "Nom d'utilisateur";
$lang['CWatch.add_row.field_password'] = "Mot de passe";
$lang['CWatch.add_row.field_sandbox'] = "Activer Sandbox";
$lang['CWatch.add_row.add_btn'] = "Ajouter un compte";
$lang['CWatch.edit_row.box_title'] = "Modifier les informations d'identification";
$lang['CWatch.edit_row.basic_title'] = "Paramètres utilisateur";
$lang['CWatch.edit_row.field_username'] = "Nom d'utilisateur";
$lang['CWatch.edit_row.field_password'] = "Mot de passe";
$lang['CWatch.edit_row.field_sandbox'] = "Activer SandBox";
$lang['CWatch.edit_row.add_btn'] = "Modifier les informations d'identification";
$lang['CWatch.service_info.option_login'] = "Se connecter à cWatch";
$lang['CWatch.tab_licenses.licenses'] = "Gérer les licences";
$lang['CWatch.tab_licenses.add'] = "Ajouter un nouveau site";
$lang['CWatch.tab_licenses.licenseKey'] = "Clé de licence";
$lang['CWatch.tab_licenses.type'] = "Type de licence";
$lang['CWatch.tab_licenses.domain'] = "Nom de domaine";
$lang['CWatch.tab_licenses.status'] = "Statut du domaine";
$lang['CWatch.tab_licenses.malware_scanner'] = "Analyseur de logiciels malveillants";
$lang['CWatch.tab_licenses.actions'] = "Actions";
$lang['CWatch.tab_licenses.no_results'] = "Aucune licence n'a été fournie pour ce client.";
$lang['CWatch.tab_licenses.not_applicable'] = "N/D";
$lang['CWatch.tab_licenses.remove_site'] = "Supprimer le site";
$lang['CWatch.tab_licenses.add_site'] = "Ajouter un site";
$lang['CWatch.tab_licenses.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer ce domaine?";
$lang['CWatch.tab_licenses.initiateDns'] = "DNS initial";
$lang['CWatch.tab_licenses.autoSsl'] = "AutoSSL";
$lang['CWatch.tab_licenses.submit'] = "Envoyer";
$lang['CWatch.tab_malware.malware'] = "Contrôle des logiciels malveillants";
$lang['CWatch.tab_malware.add_scanner'] = "Ajouter un scanner";
$lang['CWatch.tab_malware.test_credentials'] = "Testez ces informations d'identification";
$lang['CWatch.tab_malware.domainname'] = "Nom de domaine";
$lang['CWatch.tab_malware.ftppassword'] = "Mot de passe FTP";
$lang['CWatch.tab_malware.ftpusername'] = "Nom d'utilisateur FTP";
$lang['CWatch.tab_malware.host'] = "Nom d'hôte FTP";
$lang['CWatch.tab_malware.port'] = "Port FTP";
$lang['CWatch.tab_malware.path'] = "Répertoire site";
$lang['CWatch.tab_malware.submit'] = "Envoyer";
$lang['CWatch.getsitestatuses.waiting'] = "En attente";
$lang['CWatch.getsitestatuses.site_inprogress'] = "Mise en place du site en cours";
$lang['CWatch.getsitestatuses.site_retry'] = "Nouvelle tentative de mise en place du site";
$lang['CWatch.getsitestatuses.site_completed'] = "Site ajouté";
$lang['CWatch.getsitestatuses.site_failed'] = "Echec de la mise en place du site";
$lang['CWatch.getsitestatuses.dns_inprogress'] = "Analyse DNS en cours";
$lang['CWatch.getsitestatuses.dns_retry'] = "Réessayer l'analyse DNS";
$lang['CWatch.getsitestatuses.dns_completed'] = "Analyse DNS terminée";
$lang['CWatch.getsitestatuses.dns_failed'] = "Site ajouté, échec de l'analyse DNS";
$lang['CWatch.getsitestatuses.ssl_inprogress'] = "Installation SSL en cours";
$lang['CWatch.getsitestatuses.ssl_retry'] = "Nouvelle tentative d'installation SSL";
$lang['CWatch.getsitestatuses.ssl_completed'] = "Certificat SSL ajouté";
$lang['CWatch.getsitestatuses.ssl_fail'] = "Site ajouté, échec de l'installation SSL";
?>