<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['BuycPanel.!error.email.valid'] = "Veuillez entrer l'adresse courriel de votre compte.";
$lang['BuycPanel.!error.key.empty'] = "Veuillez entrer votre clé API.";
$lang['BuycPanel.!error.test_mode.valid'] = "Le mode test doit être paramétré à vrai ou faux.";
$lang['BuycPanel.!error.meta[license_type].valid'] = "Veuillez choisir un type de licence valide. ";
$lang['BuycPanel.!error.buycpanel_ipaddress.format'] = "Veuillez entrer une adresse IP valide.";
$lang['BuycPanel.!error.buycpanel_domain.format'] = "Veuillez entrer un nom de domaine valide.";
$lang['BuycPanel.!error.api.internal'] = "Une erreur interne s'est produite, ou le serveur n'a pas répondu à la demande.";
$lang['BuycPanel.name'] = "BuycPanel";
$lang['BuycPanel.module_row.name'] = "Compte";
$lang['BuycPanel.module_rows.name'] = "Comptes";
$lang['BuycPanel.module_group.name'] = "Groupe de compte";
$lang['BuycPanel.order_options.first'] = "Premier";
$lang['BuycPanel.please_select'] = "-- Veuillez choisir --";
$lang['BuycPanel.add_module_row'] = "Ajouter un compte";
$lang['BuycPanel.manage.module_rows_title'] = "Comptes";
$lang['BuycPanel.manage.module_rows_heading.email'] = "Courriel";
$lang['BuycPanel.manage.module_rows_heading.test_mode'] = "Mode test";
$lang['BuycPanel.manage.module_rows_heading.options'] = "Options";
$lang['BuycPanel.manage.module_rows.edit'] = "Modifier";
$lang['BuycPanel.manage.module_rows.delete'] = "Effacer";
$lang['BuycPanel.manage.module_rows.confirm_delete'] = "Êtes-vous sûr de vouloir effacer ce compte?";
$lang['BuycPanel.manage.module_rows.test_yes'] = "Oui";
$lang['BuycPanel.manage.module_rows.test_no'] = "Non";
$lang['BuycPanel.manage.module_rows_no_results'] = "Il n'y a pas de comptes.";
$lang['BuycPanel.tab_client_ip.heading_changeip'] = "Changer l'adresse IP";
$lang['BuycPanel.tab_client_ip.current_ipaddress'] = "Adresse IP actuelle";
$lang['BuycPanel.tab_client_ip.field_ipaddress'] = "Nouvelle adresse IP";
$lang['BuycPanel.tab_ip'] = "Changer l'adresse IP";
$lang['BuycPanel.tab_client_ip.field_submit'] = "Sauvegarder";
$lang['BuycPanel.package_fields.license_type'] = "Type de licence ";
$lang['BuycPanel.service_fields.ipaddress'] = "Adresse IP";
$lang['BuycPanel.service_field.tooltip.ipaddress'] = "Entrez l'adresse IP à  laquelle la licence va être appliquée.";
$lang['BuycPanel.service_fields.domain'] = "Domaine";
$lang['BuycPanel.service_field.tooltip.domain'] = "Entrez votre nom de domaine.";
$lang['BuycPanel.service_field.tooltip.domain_edit'] = "Le changement de nom de domaine affectera seulement le service localement.";
$lang['BuycPanel.service_info.ip_address'] = "Adresse IP";
$lang['BuycPanel.service_info.license_type'] = "Licence ";
$lang['BuycPanel.row_meta.email'] = "Courriel";
$lang['BuycPanel.row_meta.tooltip.email'] = "Entrez votre adresse courriel pour votre compte BuycPanel.";
$lang['BuycPanel.row_meta.key'] = "Clé API";
$lang['BuycPanel.row_meta.tooltip.key'] = "Entrez votre clé d'API de compte BuycPanel.";
$lang['BuycPanel.row_meta.test_mode'] = "Mode test";
$lang['BuycPanel.add_row.box_title'] = "Ajouter un compte BuycPanel";
$lang['BuycPanel.add_row.basic_title'] = "Paramètres de base";
$lang['BuycPanel.add_row.add_btn'] = "Ajouter compte";
$lang['BuycPanel.edit_row.box_title'] = "Modifier le compte BuycPanel";
$lang['BuycPanel.edit_row.basic_title'] = "Paramètres de base";
$lang['BuycPanel.edit_row.add_btn'] = "Mettre à jour le compte";
$lang['BuycPanel.license_types.0'] = "cPanel / WHM Plus!";
$lang['BuycPanel.license_types.10'] = "Optimisé pour cPanel VPS";
$lang['BuycPanel.license_types.20'] = "cPanel VPS optimisé chaque année";
$lang['BuycPanel.license_types.3'] = "Licence 1 an";
$lang['BuycPanel.license_types.4'] = "Licence de 2 ans";
$lang['BuycPanel.license_types.5'] = "Licence de 3 ans";
$lang['BuycPanel.license_types.attracta'] = "Attracta";
$lang['BuycPanel.license_types.blesta'] = "Blesta";
$lang['BuycPanel.license_types.clientexec'] = "ClientExec";
$lang['BuycPanel.license_types.cloudlinux'] = "Cloud Linux";
$lang['BuycPanel.license_types.fantastico'] = "Fantastico";
$lang['BuycPanel.license_types.installatron'] = "Installatron";
$lang['BuycPanel.license_types.installatronvps'] = "Installatron VPS";
$lang['BuycPanel.license_types.litespeed'] = "Lite Speed";
$lang['BuycPanel.license_types.litespeed_cpu'] = "Lite Speed CPU";
$lang['BuycPanel.license_types.litespeedultra'] = "Lite Speed Ultra";
$lang['BuycPanel.license_types.litespeedvps'] = "Lite Speed VPS";
$lang['BuycPanel.license_types.rvsitebuilder'] = "RVSiteBuilder";
$lang['BuycPanel.license_types.rvsitebuildervps'] = "RVSiteBuilder VPS";
$lang['BuycPanel.license_types.rvskin'] = "RVSkin";
$lang['BuycPanel.license_types.softaculous'] = "Softaculous";
$lang['BuycPanel.license_types.solusvm'] = "SolusVM Enterprise";
$lang['BuycPanel.license_types.solusvmslave'] = "SolusVM Micro Slave";
$lang['BuycPanel.license_types.solusvminislave'] = "SolusVM mini esclave";
$lang['BuycPanel.license_types.solusvmunslave'] = "Esclave SolusVM";
$lang['BuycPanel.license_types.solusvmnovirtual'] = "SolusVM Slave Only Master";
$lang['BuycPanel.license_types.spamscan'] = "Scan des spam";
$lang['BuycPanel.license_types.trendyflash'] = "TrendySite Builder Lite";
$lang['BuycPanel.license_types.trendyflashdedicated'] = "TrendySite Builder dédié";
$lang['BuycPanel.license_types.trendyflashvps'] = "VPS TrendySite Builder";
$lang['BuycPanel.license_types.whmsonic'] = "WHMSonic";
$lang['BuycPanel.license_types.whmxtra'] = "WHMXtra";
?>