<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Phpids.email_alert_name'] = "Alerte d'intrusion PHPIDS";
$lang['AdminCompanyEmails.templates.Phpids.email_alert_desc'] = "Courriel d'alerte de détection d'intrusion PHPIDS, envoyé aux adresses configurés sous le plugin PHPIDS.";
?>