<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PhpidsManagePlugin.!success.settings_updated'] = "Les paramètres ont été mis à jour avec succès.";
$lang['PhpidsManagePlugin.index.page_title'] = "PHPIDS > Paramètres";
$lang['PhpidsManagePlugin.logs.page_title'] = "PHPIDS > Journaux";
$lang['PhpidsManagePlugin.index.boxtitle_phpids'] = "PHPIDS";
$lang['PhpidsManagePlugin.index.tab_settings'] = "Paramètres";
$lang['PhpidsManagePlugin.index.tab_logs'] = "Journaux";
$lang['PhpidsManagePlugin.index.heading_general'] = "Options de base";
$lang['PhpidsManagePlugin.index.field.compound_impact'] = "Évaluation de l'impact composé au cours de la session";
$lang['PhpidsManagePlugin.index.field.rotate_impact'] = "Intervalle d'évaluation de l'impact d'une session de rotation";
$lang['PhpidsManagePlugin.index.heading_logging'] = "Connexion";
$lang['PhpidsManagePlugin.index.field.log_min_score'] = "Seuil d'impact minimal à écrire au journal";
$lang['PhpidsManagePlugin.index.field.log_rotate_freq'] = "Fréquence de rotation des journaux";
$lang['PhpidsManagePlugin.index.heading_email'] = "Alertes courriel";
$lang['PhpidsManagePlugin.index.field.email_min_score'] = "Indice d'impact minimum pour un e-mail";
$lang['PhpidsManagePlugin.index.field.email_addresses'] = "Adresses pour l'envoi d'alertes courriel (séparés par une virgule)";
$lang['PhpidsManagePlugin.index.text.edit_template'] = "Modifier le modèle courriel";
$lang['PhpidsManagePlugin.index.heading_redirect'] = "Redirection";
$lang['PhpidsManagePlugin.index.field.redirect_min_score'] = "Indice d'impact minimum pour rediriger";
$lang['PhpidsManagePlugin.index.field.redirect_url'] = "URL de redirection";
$lang['PhpidsManagePlugin.index.field.submit'] = "Mettre à jour les paramètres";
$lang['PhpidsManagePlugin.getIntervals.mins_singular'] = "%1\$s minute"; // %1$s is the number of minutes
$lang['PhpidsManagePlugin.getIntervals.mins_plural'] = "%1\$s minutes"; // %1$s is the number of minutes
$lang['PhpidsManagePlugin.getDays.days_singular'] = "%1\$s jour"; // %1$s is the number of days
$lang['PhpidsManagePlugin.getDays.days_plural'] = "%1\$s jours"; // %1$s is the number of days
$lang['PhpidsManagePlugin.getDays.days_never'] = "Jamais retourner";
$lang['PhpidsManagePlugin.logs.heading.name'] = "Nom";
$lang['PhpidsManagePlugin.logs.heading.value'] = "Valeur";
$lang['PhpidsManagePlugin.logs.heading.uri'] = "URI";
$lang['PhpidsManagePlugin.logs.heading.ip'] = "IP";
$lang['PhpidsManagePlugin.logs.heading.user_id'] = "ID d'utilisateur";
$lang['PhpidsManagePlugin.logs.heading.tags'] = "Étiquettes";
$lang['PhpidsManagePlugin.logs.heading.impact'] = "Impact";
$lang['PhpidsManagePlugin.logs.heading.date_added'] = "Date ajouté";
$lang['PhpidsManagePlugin.logs.no_results'] = "Il n'y a pas de résultats.";
?>