<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Skrill.name'] = "Skrill";
$lang['Skrill.user_email'] = "Courriel";
$lang['Skrill.secret_word'] = "Mot secret";
$lang['Skrill.merchant_id'] = "ID de marchant";
$lang['Skrill.mqi'] = "Mot de passe MQI";
$lang['Skrill.secret_word_note'] = "Veuillez entrer le mot secret de votre compte Skrill.";
$lang['Skrill.user_email_note'] = "Veuillez entrer votre adresse courriel de votre compte Skrill";
$lang['Skrill.merchant_id_note'] = "Veuillez entrer votre ID de compte Skrill.";
$lang['Skrill.mqi_note'] = "Entrez le mot de passe MQI API de votre compte Skrill.";
$lang['Skrill.buildprocess.submit'] = "Payer avec Skrill";
$lang['Skrill.invoice.description'] = "Factures";
$lang['Skrill.!error.libxml_required'] = "Les extensions libxml et simplexml sont requises pour cette paserelle.";
$lang['Skrill.!error.user_email.valid'] = "Veuillez entrer une adresse courriel valide.";
$lang['Skrill.!error.secret_word.empty'] = "Veuillez entrer le mot secret de votre compte.";
$lang['Skrill.!error.mqi.empty'] = "Veuillez entrer votre mot de passe MQI.";
$lang['Skrill.!error.merchant_id.empty'] = "Veuillez fournir votre ID de marchand.";
?>