<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Converge.name'] = "Converger";
$lang['Converge.login_id'] = "Nom d'utilisateur";
$lang['Converge.transaction_key'] = "Clé de transaction";
$lang['Converge.api'] = "API de paiement";
$lang['Converge.merchant_id'] = "ID du marchand";
$lang['Converge.user_id'] = "ID utilisateur";
$lang['Converge.pin'] = "PIN";
$lang['Converge.live_mode'] = "Mode Live";
$lang['Converge.multiCurrency'] = "Le compte Converge est configuré pour plusieurs devises";
$lang['Converge.yes'] = "Oui";
$lang['Converge.no'] = "Non";
$lang['Converge.multiCurrency.error'] = "Vous devez spécifier si votre compte Converge est réglé sur multi-devise ou pas.";
$lang['Converge.!error.login_id.format'] = "L'ID de connexion ne doit pas comporter plus de 20 caractères et ne peut pas être vide.";
$lang['Converge.!error.transaction_key.format'] = "La clé de transaction doit comporter 16 caractères.";
$lang['Converge.!error.live_mode.valid'] = "Le mode en direct doit être réglé sur \"vrai\" s'il est donné.";
?>