<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftPackage.!error.meta[server_name].format'] = "Veuillez définir un nom pour le serveur.";
$lang['MulticraftPackage.!error.meta[players].format'] = "Veuillez spécifier le nombre maximal de slot de joueur à permettre.";
$lang['MulticraftPackage.!error.meta[memory].format'] = "Veuillez paramétrer la quantité maximale de mémoire (chiffre intègre) en Mo.";
$lang['MulticraftPackage.!error.meta[jardir].format'] = "Veuillez sélectionner un répertoire JAR valide.";
$lang['MulticraftPackage.!error.meta[user_jar].format'] = "La sélection du JAR par le propriétaire doit être paramétré à 1 ou 0.";
$lang['MulticraftPackage.!error.meta[user_name].format'] = "Que le propriétaire puisse définir un nom doit être mis à 1 ou 0.";
$lang['MulticraftPackage.!error.meta[user_schedule].format'] = "Que le propriétaire puisse planifier des tâches doivent être paramétré à 1 ou 0.";
$lang['MulticraftPackage.!error.meta[user_ftp].format'] = "Pour que le propriétaire puisse donner l'accès FTP à d'autres personnes cela doit être réglé sur 1 ou 0.";
$lang['MulticraftPackage.!error.meta[user_visibility].format'] = "Qu'un propriétaire puisse, ou non, changer la visibilité d'un serveur doit être défini à 1 ou 0.";
$lang['MulticraftPackage.!error.meta[default_level].format'] = "Veuillez choisir un rôle par défaut valide.";
$lang['MulticraftPackage.!error.meta[autostart].format'] = "Si le serveur doit démarrer automatiquement le démarrage doit être réglé sur 1 ou 0.";
$lang['MulticraftPackage.!error.meta[create_ftp].format'] = "Permettre la création d'un compte FTP doit être défini à 1 ou 0.";
$lang['MulticraftPackage.!error.meta[server_visibility].format'] = "Veuillez sélectionner une visibilité serveur valide.";
$lang['MulticraftPackage.package_fields.server_name'] = "Nom du serveur";
$lang['MulticraftPackage.package_fields.players'] = "Case joueur";
$lang['MulticraftPackage.package_fields.memory'] = "Mémoire RAM du serveur";
$lang['MulticraftPackage.package_fields.tooltip.memory'] = "Définissez la mémoire en Mo, ou laissez vide pour utiliser le montant par défaut.";
$lang['MulticraftPackage.package_fields.jarfile'] = "Fichier JAR";
$lang['MulticraftPackage.package_fields.tooltip.jarfile'] = "Laisser en blanc pour utiliser le fichier JAR par défaut.";
$lang['MulticraftPackage.package_fields.jardir'] = "Rechercher un JAR dans le répertoire suivant";
$lang['MulticraftPackage.package_fields.tooltip.jardir'] = "Si vous n'utilisez pas le répertoire JAR du démon, Multicraft doit s'exécuter en mode multi-utilisateur.";
$lang['MulticraftPackage.package_fields.jardir_daemon'] = "Répertoire des démons JAR";
$lang['MulticraftPackage.package_fields.jardir_server'] = "Répertoire JAR du serveur";
$lang['MulticraftPackage.package_fields.jardir_server_base'] = "Répertoire de base du serveur";
$lang['MulticraftPackage.package_fields.user_jar'] = "JAR sélectionnable par le propriétaire";
$lang['MulticraftPackage.package_fields.user_name'] = "Le propriétaire peut paramétrer le nom";
$lang['MulticraftPackage.package_fields.tooltip.user_name'] = "Définit si le propriétaire peut définir ou modifier le nom du serveur.";
$lang['MulticraftPackage.package_fields.user_schedule'] = "Le propriétaire peut paramétrer des tâches";
$lang['MulticraftPackage.package_fields.tooltip.user_schedule'] = "Définit si le propriétaire peut créer des tâches planifiées et modifier le réglage de sauvegarde automatique.";
$lang['MulticraftPackage.package_fields.user_ftp'] = "Le propriétaire peut gérer les services FTP";
$lang['MulticraftPackage.package_fields.tooltip.user_ftp'] = "Définit si le propriétaire peut donner des accès FTP aux autres utilisateurs.";
$lang['MulticraftPackage.package_fields.user_visibility'] = "Le propriétaire peut paramétrer la visibilité";
$lang['MulticraftPackage.package_fields.tooltip.user_visibility'] = "Définit si le propriétaire peut modifier la visibilité du serveur et le rôle par défaut.";
$lang['MulticraftPackage.package_fields.default_level'] = "Rôle par défaut";
$lang['MulticraftPackage.package_fields.tooltip.default_level'] = "Sélectionnez quel joueur peut être assigné lors de la première connexion. Utilisez Aucun accès pour une liste blanche.";
$lang['MulticraftPackage.package_fields.default_level_0'] = "Aucun accès";
$lang['MulticraftPackage.package_fields.default_level_10'] = "Invité";
$lang['MulticraftPackage.package_fields.default_level_20'] = "Utilisateur";
$lang['MulticraftPackage.package_fields.default_level_30'] = "Modérateur";
$lang['MulticraftPackage.package_fields.autostart'] = "Serveur de démarrage";
$lang['MulticraftPackage.package_fields.tooltip.autostart'] = "Démarrer automatiquement le serveur lorsque Multicraft redémarre.";
$lang['MulticraftPackage.package_fields.create_ftp'] = "Créer un compte FTP";
$lang['MulticraftPackage.package_fields.tooltip.create_ftp'] = "Création automatique d'un compte FTP";
$lang['MulticraftPackage.package_fields.server_visibility'] = "Visibilité serveur";
$lang['MulticraftPackage.package_fields.tooltip.server_visibility'] = "Définir la visibilité du serveur dans la liste des serveurs Multicraft.";
$lang['MulticraftPackage.package_fields.server_visibility_0'] = "Propriétaire seulement";
$lang['MulticraftPackage.package_fields.server_visibility_1'] = "Rôle par défaut";
$lang['MulticraftPackage.package_fields.server_visibility_2'] = "Utilisateurs avec rôles seulement";
?>