<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftService.!error.internal'] = "Une erreur interne est survenue ou le serveur n'as pas répondu à la requête.";
$lang['MulticraftService.!error.client'] = "Aucun client n'as été trouvé pour lequel créer un utilisateur Multicraft.";
$lang['MulticraftService.!error.server_id.format'] = "L'identifiant serveur doit etre un nombre intègre, ou laissé blanc.";
$lang['MulticraftService.!error.user_id.format'] = "L'ID d'utilisateur doit être un nombre intègre ou laissé blanc.";
$lang['MulticraftService.!error.daemon_id.format'] = "L'ID du démon doit être un nombre intègre, ou laissé blanc.";
$lang['MulticraftService.!error.ip.format'] = "Veuillez entrer une adresse IP valide, ou laissez blanc.";
$lang['MulticraftService.!error.port.format'] = "Veuillez fournir un numéro de port valide ou laissez vide.";
$lang['MulticraftService.service_fields.server_id'] = "ID de serveur";
$lang['MulticraftService.service_fields.tooltip.server_id'] = "Définissez l'ID unique du serveur Multicraft auquel ce service doit être affecté. Laissez ce champ vide autrement.";
$lang['MulticraftService.service_fields.user_id'] = "Identifiant";
$lang['MulticraftService.service_fields.tooltip.user_id'] = "Définissez l'ID unique de l'utilisateur Multicraft auquel ce service doit être affecté. Laissez le champ vide sinon.";
$lang['MulticraftService.service_fields.daemon_id'] = "ID de démon";
$lang['MulticraftService.service_fields.tooltip.daemon_id'] = "Spécifiez l'ID du démon Multicraft auquel ce service sera assigné. Laisser le vide autrement.";
$lang['MulticraftService.service_fields.ip'] = "Adresse IP";
$lang['MulticraftService.service_fields.tooltip.ip'] = "Définissez l'adresse IP du serveur Multicraft pour lequel ce service doit être affecté. Laissez ce champ vide autrement.";
$lang['MulticraftService.service_fields.port'] = "Port";
$lang['MulticraftService.service_fields.tooltip.port'] = "Paramétrez le port du serveur Multicraft auquel ce service sera assigné. Laissez le en blanc autrement.";
$lang['MulticraftService.service_fields.yes'] = "Oui";
$lang['MulticraftService.service_fields.no'] = "Non";
$lang['MulticraftService.!error.configoptions[user_players].format'] = "Si le propriétaire du serveur peut définir le nombre de joueurs doit être défini à 1 ou 0.";
$lang['MulticraftService.!error.configoptions[players].format'] = "Veuillez indiquer le nombre de joueurs.";
$lang['MulticraftService.!error.configoptions[memory].format'] = "Veuillez indiquer une valeur valide de mémoire.";
$lang['MulticraftService.!error.configoptions[daemon_id].format'] = "Veuillez choisir un démon valide.";
$lang['MulticraftService.!error.configoptions[dedicated_ip].format'] = "Le choix d'utiliser une adresse IP dédiée doit être défini sur 1 ou 0.";
?>