<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Multicraft.!error.module_row.missing'] = "Une erreur s'est produite. La rangée du module est non-disponible.";
$lang['Multicraft.name'] = "Multicraft";
$lang['Multicraft.module_row.name'] = "Serveur";
$lang['Multicraft.module_rows.name'] = "Serveurs";
$lang['Multicraft.add_module_row'] = "Ajouter un serveur";
$lang['Multicraft.manage.module_rows_title'] = "Serveurs";
$lang['Multicraft.manage.module_rows_heading.username'] = "Nom d'utilisateur";
$lang['Multicraft.manage.module_rows_heading.server_name'] = "Étiquette de serveur";
$lang['Multicraft.manage.module_rows_heading.panel_api_url'] = "URL de l'API panel";
$lang['Multicraft.manage.module_rows_heading.options'] = "Options";
$lang['Multicraft.manage.module_rows.edit'] = "Modifier";
$lang['Multicraft.manage.module_rows.delete'] = "Effacer";
$lang['Multicraft.manage.module_rows.confirm_delete'] = "Êtes-vous sur de vouloir effacer ce serveur?";
$lang['Multicraft.manage.module_rows_no_results'] = "Il n'y a pas de serveur.";
$lang['Multicraft.manage.module_rows_in_use_0'] = "Non";
$lang['Multicraft.manage.module_rows_in_use_1'] = "Oui";
$lang['Multicraft.service_info.options'] = "Options";
$lang['Multicraft.service_info.option_login'] = "Connexion";
$lang['Multicraft.tab_client_actions'] = "Actions";
$lang['Multicraft.tab_client_players'] = "Joueurs";
$lang['Multicraft.tab_client_console'] = "Console";
$lang['Multicraft.tab_client_actions.heading_server_address'] = "Adresse du serveur";
$lang['Multicraft.tab_client_actions.address_ip'] = "Adresse IP";
$lang['Multicraft.tab_client_actions.address_port'] = "Port";
$lang['Multicraft.tab_client_actions.heading_server_status'] = "Statut du serveur";
$lang['Multicraft.tab_client_actions.heading_server_actions'] = "Actions serveurs";
$lang['Multicraft.tab_client_actions.action_restart'] = "Redémarrer";
$lang['Multicraft.tab_client_actions.action_stop'] = "Stop";
$lang['Multicraft.tab_client_actions.action_start'] = "Départ";
$lang['Multicraft.tab_client_actions.action_set_daytime'] = "Régler à l'heure du jour";
$lang['Multicraft.tab_client_actions.action_set_nighttime'] = "Réglé sur le mode nuit";
$lang['Multicraft.tab_client_actions.action_server_name'] = "Définir le nom du serveur";
$lang['Multicraft.tab_client_actions.unknown'] = "Inconnu";
$lang['Multicraft.tab_client_actions.heading_server_name'] = "Définir le serveur de noms";
$lang['Multicraft.tab_client_console.field_server_name'] = "Nom du serveur";
$lang['Multicraft.tab_client_actions.submit_save'] = "Sauvegarder";
$lang['Multicraft.tab_client_actions.status_online'] = "En ligne, %1\$s/%2\$s joueurs"; // %1$s is the number of players online, %2\$s is the maximum number of players
$lang['Multicraft.tab_client_actions.status_offline'] = "Hors ligne";
$lang['Multicraft.tab_client_actions.status_suspended'] = "Suspendu";
$lang['Multicraft.tab_client_actions.status_unknown'] = "Inconnu";
$lang['Multicraft.tab_client_players.heading_players'] = "Joueurs connectés";
$lang['Multicraft.tab_client_players.heading_player_name'] = "Nom du joueur";
$lang['Multicraft.tab_client_players.heading_action'] = "Action";
$lang['Multicraft.tab_client_players.action_kick'] = "Sortir le joueur";
$lang['Multicraft.tab_client_players.no_results'] = "Il n'y a pas de joueurs connectés.";
$lang['Multicraft.tab_client_players.heading_console'] = "Console serveur";
$lang['Multicraft.tab_client_console.field_command'] = "Commande";
$lang['Multicraft.tab_client_console.submit_send'] = "Envoyer";
$lang['Multicraft.tab_client_console.chat_entry'] = "[%1\$s] %2\$s: %3\$s"; // %1$s is the timestamp of the log entry, %2$s is the player name, %3$s is the message
$lang['Multicraft.tab_client_console.submit_clear_log'] = "Vider les journaux";
$lang['Multicraft.tab_client_players.heading_console_tab'] = "Journaux console";
$lang['Multicraft.tab_client_players.heading_chat_tab'] = "Journaux de bavardage";
$lang['Multicraft.add_row.box_title'] = "Ajouter un serveur Multicraft";
$lang['Multicraft.add_row.basic_title'] = "Paramètres de base";
$lang['Multicraft.add_row.add_btn'] = "Ajouter un serveur";
$lang['Multicraft.add_row.daemons_title'] = "Adresses IP dédiées";
$lang['Multicraft.add_row.ip_btn'] = "Ajouter une adresse IP";
$lang['Multicraft.add_row.remove_ip'] = "Enlever";
$lang['Multicraft.add_row.daemon_col'] = "ID démon";
$lang['Multicraft.add_row.ip_col'] = "Adresse IP";
$lang['Multicraft.add_row.in_use_col'] = "En utilisation";
$lang['Multicraft.edit_row.box_title'] = "Modifier le serveur Multicraft";
$lang['Multicraft.edit_row.basic_title'] = "Paramètres de base";
$lang['Multicraft.edit_row.add_btn'] = "Modifier le serveur";
$lang['Multicraft.edit_row.daemons_title'] = "Adresse IP dédiée";
$lang['Multicraft.edit_row.ip_btn'] = "Ajouter une adresse IP";
$lang['Multicraft.edit_row.remove_ip'] = "Enlever";
$lang['Multicraft.edit_row.daemon_col'] = "ID de démon";
$lang['Multicraft.edit_row.ip_col'] = "Adresse IP";
$lang['Multicraft.edit_row.in_use_col'] = "En utilisation";
$lang['Multicraft.!tooltip.panel_url'] = "Veuillez entrer l'URL de votre tableau de bord Multicraft (Ex: http://multicraft.domaine.com/)";
$lang['Multicraft.!tooltip.panel_api_url'] = "Entrez l'URL de votre API Multicraft. Ex: http://multicraft.domaine.com/api.php";
$lang['Multicraft.!tooltip.key'] = "Entrez la clé API générée pour vos utilisateurs sur Multicraft.";
$lang['Multicraft.!tooltip.log_all'] = "Cochez pour enregistrer toutes les requêtes API, ou décochez pour enregistrer seulement les demandes essentielles.";
$lang['Multicraft.row_meta.server_name'] = "Étiquette serveur";
$lang['Multicraft.row_meta.panel_url'] = "URL du panel";
$lang['Multicraft.row_meta.panel_api_url'] = "URL de l'API du Panel";
$lang['Multicraft.row_meta.username'] = "Nom d'utilisateur";
$lang['Multicraft.row_meta.key'] = "Clé API";
$lang['Multicraft.row_meta.log_all'] = "Inscrire au journal toutes les requêtes d'API";
$lang['Multicraft.add_row.port_col'] = "Port";
$lang['Multicraft.edit_row.port_col'] = "Port";
?>