<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['404.heading_error'] = "404
";
$lang['404.text_error'] = "Désolé, la page que vous tentez d'accéder n'existe pas ou peut-être déplacé.
";
?>