<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['_PaymentTypes.cash'] = "Argent";
$lang['_PaymentTypes.check'] = "Chèque";
$lang['_PaymentTypes.money_order'] = "Mandat";
$lang['_PaymentTypes.in_house_credit'] = "Crédit maison";
?>