<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyAutomation.!success.automation_updated'] = "Les paramètres d'automatisation ont été mis à jour avec succès!";
$lang['AdminCompanyAutomation.index.boxtitle_automation'] = "Automatisation";
$lang['AdminCompanyAutomation.index.field_automationsubmit'] = "Mettre à jour les paramètres ";
$lang['AdminCompanyAutomation.index.field_enabled'] = "Activé";
$lang['AdminCompanyAutomation.index.text_interval'] = "Intervalle ";
$lang['AdminCompanyAutomation.index.text_starttime'] = "Heure de départ";
$lang['AdminCompanyAutomation.index.text_task_lastran'] = "Exécution de la dernière tâche:";
$lang['AdminCompanyAutomation.index.no_results'] = "Il n'y a pas de tâches cron.";
$lang['AdminCompanyAutomation.index.no_cron_lastran'] = "Jamais";
$lang['AdminCompanyAutomation.index.text_cron_last_ran'] = "La dernière fois que la tâche Cron a été activée est le %1\$s."; // %1$s is the date that the cron last ran
$lang['AdminCompanyAutomation.index.text_cron_never_ran'] = "La tâche Cron n'as jamais été effectuée.";
$lang['AdminCompanyAutomation.getintervals.text_minutes'] = "minutes";
$lang['AdminCompanyAutomation.getintervals.text_hour'] = "heure";
$lang['AdminCompanyAutomation.getintervals.text_hours'] = "heures";
$lang['AdminCompanyAutomation.index.page_title'] = "Paramètres > Compagnie > Automation";
$lang['AdminCompanyAutomation.!success.task_cleared'] = "La tâche cron a été effacée.";
$lang['AdminCompanyAutomation.index.option_clear_task'] = "Effacer le verrouillage de tâche";
$lang['AdminCompanyAutomation.index.confirm_clear_task'] = "Êtes-vous sur de vouloir supprimer la protection de cette tache cron? Si cette tâche achoppe continuellement, il pourrais y avoir une cause sérieuse. Tentez d'activer la tache cron de façon manuelle, ou vérifiez les journaux cron pour en déterminer la cause.";
?>