<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyCurrencies.!success.setup_updated'] = "Les paramètres de configuration de la devise ont été mis à jour avec succès!";
$lang['AdminCompanyCurrencies.!success.add_created'] = "La devise %1\$s a été créée avec succès!"; // %1$s is the currency code
$lang['AdminCompanyCurrencies.!success.edit_updated'] = "La devise %1\$s a été mis à jour avec succès!"; // %1$s is the currency code
$lang['AdminCompanyCurrencies.!success.delete_deleted'] = "La devise %1\$s a été effacée avec succès!"; // %1$s is the currency code
$lang['AdminCompanyCurrencies.!success.rates_updated'] = "Les taux d'échange ont été mis à jour avec succès.";
$lang['AdminCompanyCurrencies.setup.tooltip_currency_pricing'] = "Cette option nécessite que la tarification du forfait soit définie dans la devise spécifiée pour être disponible pour la création de nouveaux services. Si cette option est décochée et que la tarification du package n'existe pas pour la devise, le prix sera calculé sur la base du taux de change de la devise par défaut. Les services de renouvellement préfèrent toujours les prix des forfaits dans la devise choisie, mais ils utiliseront le taux de change de la devise par défaut, si cela n'est pas spécifié pour le forfait.";
$lang['AdminCompanyCurrencies.setup.boxtitle_setup'] = "Configuration des devises";
$lang['AdminCompanyCurrencies.setup.heading_general'] = "Général";
$lang['AdminCompanyCurrencies.setup.field_default_currency'] = "Devise par défaut";
$lang['AdminCompanyCurrencies.setup.field_show_currency_code'] = "Voir le code de devise";
$lang['AdminCompanyCurrencies.setup.field_client_set_currency'] = "Permettre au client de choisir la devise";
$lang['AdminCompanyCurrencies.setup.heading_multicurrency'] = "Multi-devises";
$lang['AdminCompanyCurrencies.setup.field_multi_currency_package'] = "Utiliser le prix d'ensemble pour les nouveaux services seulement.";
$lang['AdminCompanyCurrencies.setup.field_exchange_rates_auto_update'] = "Mettre à jour les taux de change automatiquement";
$lang['AdminCompanyCurrencies.setup.field_last_updated'] = "Dernière mise à jour des taux";
$lang['AdminCompanyCurrencies.setup.field_exchange_rates_padding'] = "Gonflement du taux de change";
$lang['AdminCompanyCurrencies.setup.field_setupsubmit'] = "Mettre à jour les paramètres";
$lang['AdminCompanyCurrencies.active.boxtitle_active'] = "Devises actives";
$lang['AdminCompanyCurrencies.active.categorylink_addcurrency'] = "Ajouter une devise";
$lang['AdminCompanyCurrencies.active.no_results'] = "Il n'y a pas de devise active.";
$lang['AdminCompanyCurrencies.active.text_currency_code'] = "Code de devise (ISO 4217)";
$lang['AdminCompanyCurrencies.active.text_format'] = "Format";
$lang['AdminCompanyCurrencies.active.text_exchange_rate'] = "Taux de change";
$lang['AdminCompanyCurrencies.active.text_options'] = "Options";
$lang['AdminCompanyCurrencies.active.option_edit'] = "Editer";
$lang['AdminCompanyCurrencies.active.option_delete'] = "Effacer";
$lang['AdminCompanyCurrencies.active.confirm_delete'] = "Êtes-vous sur de vouloir effacer cette devise?";
$lang['AdminCompanyCurrencies.add.boxtitle_add'] = "Ajouter une devise";
$lang['AdminCompanyCurrencies.add.field_code'] = "Code de devise (ISO 4217)";
$lang['AdminCompanyCurrencies.add.field_format'] = "Format";
$lang['AdminCompanyCurrencies.add.field_prefix'] = "Préfixe du symbole";
$lang['AdminCompanyCurrencies.add.field_suffix'] = "Symbole suffixe";
$lang['AdminCompanyCurrencies.add.field_exchange_rate'] = "Taux d'échange";
$lang['AdminCompanyCurrencies.add.field_addsubmit'] = "Créer une devise";
$lang['AdminCompanyCurrencies.edit.boxtitle_edit'] = "Modifier la devise";
$lang['AdminCompanyCurrencies.edit.field_code'] = "Code de devise (ISO 4217)";
$lang['AdminCompanyCurrencies.edit.field_format'] = "Format";
$lang['AdminCompanyCurrencies.edit.field_prefix'] = "Symbole préfixe";
$lang['AdminCompanyCurrencies.edit.field_suffix'] = "Symbole du suffixe";
$lang['AdminCompanyCurrencies.edit.field_exchange_rate'] = "Taux de change";
$lang['AdminCompanyCurrencies.edit.field_editsubmit'] = "Éditer la devise";
$lang['AdminCompanyCurrencies.!cancel.field_cancel'] = "Annuler";
$lang['AdminCompanyCurrencies.setup.page_title'] = "Paramètres > Compagnie >  Devises > Configuration des devises";
$lang['AdminCompanyCurrencies.setup.field_exchange_rates_processor'] = "Processeur de taux de change";
$lang['AdminCompanyCurrencies.setup.no_exchange_updated'] = "Jamais";
$lang['AdminCompanyCurrencies.setup.open_parenthesis'] = "(";
$lang['AdminCompanyCurrencies.setup.closed_parenthesis'] = ")";
$lang['AdminCompanyCurrencies.active.page_title'] = "Paramètres > Compagnie > Devises > Devises actives";
$lang['AdminCompanyCurrencies.active.text_exchange_updated'] = "Dernière mise à jour";
$lang['AdminCompanyCurrencies.active.no_exchange_updated'] = "Jamais";
$lang['AdminCompanyCurrencies.add.page_title'] = "Paramètres > Compagnie > Devises > Ajouter une devise";
$lang['AdminCompanyCurrencies.edit.page_title'] = "Paramètres > Compagnie > Devises > Éditer les devises";
$lang['AdminCompanyCurrencies.add.confirm_add'] = "Êtes-vous sûr de vouloir créer cette monnaie? Le taux de change de cette devise sera écrasé lorsque les taux de change seront automatiquement mis à jour dans le système. Vous pouvez désactiver les mises à jour automatiques sous [Paramètres]> [Société]> [Devises]> [Configuration devise].";
$lang['AdminCompanyCurrencies.edit.confirm_edit'] = "Êtes-vous sûr que vous voulez mettre à jour cette devise? Le taux de change de cette devise sera écrasé lorsque les taux de change sont automatiquement mises à jour dans le système. Vous pouvez désactiver les mises à jour automatiques sous [Paramètres]> [Compagnie]> [Devises]> [Configuration des devises].";
$lang['AdminCompanyCurrencies.!tooltip.precision'] = "La précision correspond au nombre de chiffres significatifs après la virgule pris en charge par la devise.";
$lang['AdminCompanyCurrencies.active.text_precision'] = "Précision";
$lang['AdminCompanyCurrencies.add.field_precision'] = "Précision";
$lang['AdminCompanyCurrencies.edit.field_precision'] = "Précision";
$lang['AdminCompanyCurrencies.setup.field_exchange_rates_processor_key'] = "Clé d'API du processeur de taux de change";
$lang['AdminCompanyCurrencies.setup.tooltip_exchange_rates_processor_key'] = "Une clé API est requise pour extraire les taux de change du processeur sélectionné.";
?>