<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGateways.!success.manage_updated'] = "La passerelle a été correctement mis à jour.";
$lang['AdminCompanyGateways.!success.upgraded'] = "La passerelle a été mise à jour avec succès.";
$lang['AdminCompanyGateways.!success.uninstalled'] = "La passerelle a été désinstallée avec succès.";
$lang['AdminCompanyGateways.!success.installed'] = "La passerelle a été installée avec succès.";
$lang['AdminCompanyGateways.available.heading_merchant'] = "Marchand";
$lang['AdminCompanyGateways.available.heading_nonmerchant'] = "Non Marchant";
$lang['AdminCompanyGateways.available.text_author'] = "Auteur: ";
$lang['AdminCompanyGateways.available.text_author_url'] = "URL de l'auteur";
$lang['AdminCompanyGateways.available.text_supports'] = "Prise en charge:";
$lang['AdminCompanyGateways.available.text_merchantach'] = "ACH";
$lang['AdminCompanyGateways.available.text_merchantachoffsite'] = "Automated Clearing House (ACH) externe";
$lang['AdminCompanyGateways.available.text_merchantcc'] = "Carte de crédit";
$lang['AdminCompanyGateways.available.text_merchantccoffsite'] = "Cartes de crédit hors site";
$lang['AdminCompanyGateways.available.text_merchant_none'] = "Il n'y a pas de passerelle marchande disponible.";
$lang['AdminCompanyGateways.available.text_nonmerchant_none'] = "Il n'y a pas de passerelle non-marchande disponible.";
$lang['AdminCompanyGateways.available.btn_install'] = "Installer";
$lang['AdminCompanyGateways.installed.heading_merchant'] = "Marchand";
$lang['AdminCompanyGateways.installed.heading_nonmerchant'] = "Non-marchand";
$lang['AdminCompanyGateways.installed.text_author'] = "Auteur:";
$lang['AdminCompanyGateways.installed.text_author_url'] = "URL de l'auteur";
$lang['AdminCompanyGateways.installed.text_supports'] = "Supports:";
$lang['AdminCompanyGateways.installed.text_merchantach'] = "AHC";
$lang['AdminCompanyGateways.installed.text_merchantachoffsite'] = "ACH externe";
$lang['AdminCompanyGateways.installed.text_merchantcc'] = "Carte de crédit";
$lang['AdminCompanyGateways.installed.text_merchantccoffsite'] = "Carte de crédit hors site";
$lang['AdminCompanyGateways.installed.text_merchant_none'] = "Il n'y a pas de passerelle marchande installée.";
$lang['AdminCompanyGateways.installed.text_nonmerchant_none'] = "Il n'y a pas de passerelle non-marchande installée.";
$lang['AdminCompanyGateways.installed.btn_uninstall'] = "Désinstaller";
$lang['AdminCompanyGateways.installed.btn_manage'] = "Gérer";
$lang['AdminCompanyGateways.installed.btn_upgrade'] = "Mettre à jour";
$lang['AdminCompanyGateways.installed.confirm_uninstall'] = "Êtes vous sur de désinstaller cette passerelle?";
$lang['AdminCompanyGateways.manage.boxtitle_manage'] = "Gérer %1\$s"; // %1$s is the name of the gateway
$lang['AdminCompanyGateways.manage.heading_gateway'] = "Options de passerelle";
$lang['AdminCompanyGateways.manage.heading_currencies'] = "Devises acceptées";
$lang['AdminCompanyGateways.manage.text_addcurrency'] = "Ajouter une devise";
$lang['AdminCompanyGateways.manage.update_settings'] = "Mettre à jour les paramètres";
$lang['AdminCompanyGateways.available.page_title'] = "Paramètres > Compagnies > Passerelles > Disponible";
$lang['AdminCompanyGateways.available.signup_url'] = "Inscription";
$lang['AdminCompanyGateways.installed.page_title'] = "Paramètres > Compagnie > Passerelles > Installées";
$lang['AdminCompanyGateways.installed.signup_url'] = "Inscription";
$lang['AdminCompanyGateways.manage.page_title'] = "Paramètres > Compagnie > Passerelles > Gérer %1\$s"; // %1$s is the name of the gateway
$lang['AdminCompanyGateways.available.text_version'] = "(ver %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.installed.text_version'] = "(ver. %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.manage.text_in_use_by'] = "en utilisation par";
$lang['AdminCompanyGateways.!tab.installed'] = "Installé";
$lang['AdminCompanyGateways.!tab.available'] = "Disponible";
$lang['AdminCompanyGateways.available.boxtitle_gateway'] = "Passerelles";
$lang['AdminCompanyGateways.installed.boxtitle_gateway'] = "Passerelles";
?>