<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemApi.!notice.api_not_restrictive'] = "AVERTISSEMENT ! La société est la société avec laquelle l'utilisateur s'authentifie lors de la connexion. L'accès aux données d'autres sociétés n'est pas limité par les requêtes API qui prennent en charge cet accès.";
$lang['AdminSystemApi.!success.key_added'] = "L'utilisateur API a été ajouté avec succès.";
$lang['AdminSystemApi.!success.key_deleted'] = "L'utilisateur API a été supprimé avec succès.";
$lang['AdminSystemApi.!success.key_updated'] = "L'utilisateur API a été mis à jour avec succès.";
$lang['AdminSystemApi.index.boxtitle_api'] = "Accès API";
$lang['AdminSystemApi.index.categorylink_keyadd'] = "Ajouter un utilisateur API";
$lang['AdminSystemApi.index.heading_user'] = "Utilisateur";
$lang['AdminSystemApi.index.heading_key'] = "Clé";
$lang['AdminSystemApi.index.heading_company'] = "Société";
$lang['AdminSystemApi.index.heading_date'] = "Date créé";
$lang['AdminSystemApi.index.heading_options'] = "Options";
$lang['AdminSystemApi.index.option_edit'] = "Modifier";
$lang['AdminSystemApi.index.option_delete'] = "Supprimer";
$lang['AdminSystemApi.index.no_results'] = "Il n'y pas pas d'utilisateur API";
$lang['AdminSystemApi.index.confirm_delete'] = "Vraiment supprimer cet utilisateur API?";
$lang['AdminSystemApi.add.boxtitle_add'] = "Ajouter un utilisateur API";
$lang['AdminSystemApi.add.field_company'] = "Compagnie";
$lang['AdminSystemApi.add.field_user'] = "Utilisateur";
$lang['AdminSystemApi.add.field_notes'] = "Notes";
$lang['AdminSystemApi.add.field_apisubmit'] = "Ajouter un utilisateur";
$lang['AdminSystemApi.edit.boxtitle_edit'] = "Modifier utilisateur d'API ";
$lang['AdminSystemApi.edit.field_company'] = "Compagnie";
$lang['AdminSystemApi.edit.field_user'] = "Utilisateur";
$lang['AdminSystemApi.edit.field_notes'] = "Notes";
$lang['AdminSystemApi.edit.field_apisubmit'] = "Mettre à jour l'utilisateur";
$lang['AdminSystemApi.index.page_title'] = "Paramètres > Système > Accès API";
?>