<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemGeneral.!success.basic_updated'] = "Les paramètres d'installation de base ont été mis à jour avec succès!";
$lang['AdminSystemGeneral.!success.geoip_updated'] = "Les paramètres GeoIP ont été mis à jour avec succès!";
$lang['AdminSystemGeneral.!success.maintenance_updated'] = "Les paramètres de maintenance ont été mis à jours avec succès!";
$lang['AdminSystemGeneral.!success.license_updated'] = "Votre clé de licence a été mis à jour avec succès!";
$lang['AdminSystemGeneral.!success.addtype_created'] = "Le type de paiement \"%1\$s\" a été créé avec succès!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.!success.edittype_updated'] = "Le type de paiement \"%1\$s\" a été mis à jour avec succès!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.!success.deletetype_deleted'] = "Le type de paiement \"%1\$s\" a été supprimé avec succès!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.basic.boxtitle_basic'] = "Configuration de base";
$lang['AdminSystemGeneral.basic.field_tempdir'] = "Répertoire temporaire";
$lang['AdminSystemGeneral.basic.field_uploadsdir'] = "Répertoire des téléchargements";
$lang['AdminSystemGeneral.basic.field_basicsubmit'] = "Mettre à jour les paramètres";
$lang['AdminSystemGeneral.basic.text_writable'] = "Inscriptible";
$lang['AdminSystemGeneral.basic.text_unwritable'] = "Pas accessible en écriture";
$lang['AdminSystemGeneral.basic.text_day'] = "Jour";
$lang['AdminSystemGeneral.basic.text_days'] = "Jours";
$lang['AdminSystemGeneral.geoip.boxtitle_geoip'] = "GeoIP";
$lang['AdminSystemGeneral.geoip.text_setup'] = "GeoIP peut être activé ici, fournissant la fonctionnalité de services de localisation à Blesta. L'activation permettra certaines caractéristiques afin de profiter des services de localisation.";
$lang['AdminSystemGeneral.geoip.text_geolite'] = "GeoIP requiert que la base de donnée binaire GeoLite City soit téléchargée. Elle peut être récupérée à l'adresse <a href=\"%1\$s\">%1\$s</a>. Ce fichier doit être décompressé et téléversé à %2\$s"; // %1$s is the URL to the GeoIP database file, %2$s is the filesystem path to the GeoIP database file
$lang['AdminSystemGeneral.geoip.text_database_exists'] = "%1\$s existe."; // %1$s is a file system path to the GeoIP database file
$lang['AdminSystemGeneral.geoip.text_database_not_exists'] = "%1\$s n'existe pas."; // %1$s is a file system path to the GeoIP database file
$lang['AdminSystemGeneral.geoip.field_geoip_enabled'] = "Activer GeoIP";
$lang['AdminSystemGeneral.geoip.field_geoipsubmit'] = "Mettre à jour les paramètres";
$lang['AdminSystemGeneral.maintenance.boxtitle_maintenance'] = "Maintenance";
$lang['AdminSystemGeneral.maintenance.field_maintenancemode'] = "Activer le mode de maintenance";
$lang['AdminSystemGeneral.maintenance.field_maintenancereason'] = "Raison de la maintenance";
$lang['AdminSystemGeneral.maintenance.field_maintenancesubmit'] = "Mettre à jour les paramètres";
$lang['AdminSystemGeneral.license.boxtitle_license'] = "Clé de licence";
$lang['AdminSystemGeneral.license.field_license'] = "Clé de licence";
$lang['AdminSystemGeneral.license.field_licensesubmit'] = "Modifier les paramètres";
$lang['AdminSystemGeneral.paymenttypes.categorylink_addtype'] = "Créer un type de paiement";
$lang['AdminSystemGeneral.paymenttypes.boxtitle_types'] = "Types de paiement";
$lang['AdminSystemGeneral.paymenttypes.heading_name'] = "Nom";
$lang['AdminSystemGeneral.paymenttypes.heading_is_lang'] = "Utilise la définition de langage";
$lang['AdminSystemGeneral.paymenttypes.heading_options'] = "Options";
$lang['AdminSystemGeneral.paymenttypes.option_edit'] = "Modifier";
$lang['AdminSystemGeneral.paymenttypes.option_delete'] = "Effacer";
$lang['AdminSystemGeneral.paymenttypes.modal_delete'] = "La suppression de ce type de paiement entraînera toutes les transactions qui utilisent ce type de paiement pour être mis à «autre». Êtes-vous sûr de vouloir supprimer ce type de paiement?";
$lang['AdminSystemGeneral.paymenttypes.text_yes'] = "Oui";
$lang['AdminSystemGeneral.paymenttypes.text_no'] = "Non";
$lang['AdminSystemGeneral.paymenttypes.no_results'] = "Il n'y a pas de type de paiements.";
$lang['AdminSystemGeneral.addtype.boxtitle_addtype'] = "Créer le type de paiement";
$lang['AdminSystemGeneral.addtype.field_name'] = "Nom";
$lang['AdminSystemGeneral.addtype.field_is_lang'] = "Utilisation de la définition de langue";
$lang['AdminSystemGeneral.addtype.field_typesubmit'] = "Créer un type de paiement";
$lang['AdminSystemGeneral.edittype.boxtitle_edittype'] = "Changer le mode de paiement";
$lang['AdminSystemGeneral.edittype.field_name'] = "Nom";
$lang['AdminSystemGeneral.edittype.field_is_lang'] = "Utiliser la définition de langue";
$lang['AdminSystemGeneral.edittype.field_typesubmit'] = "Modifier le type de paiement";
$lang['AdminSystemGeneral.basic.page_title'] = "Paramètres > Système > Général > Paramètres de base";
$lang['AdminSystemGeneral.basic.field_log_days'] = "Politique de rotation";
$lang['AdminSystemGeneral.geoip.page_title'] = "Paramètres > Système > Général > Paramètres GeoIP";
$lang['AdminSystemGeneral.maintenance.page_title'] = "Paramètres > Système > Général > Maintenance";
$lang['AdminSystemGeneral.license.page_title'] = "Paramètres > Système > Général > Clé de license";
$lang['AdminSystemGeneral.paymenttypes.page_title'] = "Paramètres > Système > Général > Types de paiements";
$lang['AdminSystemGeneral.addtype.page_title'] = "Paramètres > Système > Général > Créer un type de paiement";
$lang['AdminSystemGeneral.edittype.page_title'] = "Paramètres > Système > Général > Éditer le type de paiement";
$lang['AdminSystemGeneral.basic.text_no_log'] = "Ne jamais permuter les journaux";
$lang['AdminSystemGeneral.!paymenttypes.is_lang'] = "Cochez cette case uniquement si vous avez ajouté une définition de langue pour ce type de paiement dans le fichier de langue personnalisé.";
$lang['AdminSystemGeneral.!error.geoip_mbstring_required'] = "L'extension mbstring est requise pour cette fonction.";
$lang['AdminSystemGeneral.basic.field_root_web_dir'] = "Répertoire racine Web";
$lang['AdminSystemGeneral.paymenttypes.heading_type'] = "Type";
$lang['AdminSystemGeneral.!paymenttypes.type'] = "Lorsqu'elles sont réglées sur débit, les transactions utilisant ce type de paiement sont considérées comme basées sur le revenu alors que le crédit n'est pas basé sur le revenu.";
$lang['AdminSystemGeneral.addtype.field_type'] = "Type";
$lang['AdminSystemGeneral.edittype.field_type'] = "Type";
$lang['AdminSystemGeneral.basic.field_logdir'] = "Répertoire de journal";
?>