<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemBackup.!success.backup_updated'] = "Les informations de sauvegarde ont été mis a jour avec succès.";
$lang['AdminSystemBackup.!success.sftp_test'] = "La connexion SFTP a été réalisée avec succès!";
$lang['AdminSystemBackup.!success.amazons3_test'] = "La connexion à AmazonS3 a été faite avec succès!";
$lang['AdminSystemBackup.!success.backup_uploaded'] = "La sauvegarde a été envoyée avec succès aux services distants configurés!";
$lang['AdminSystemBackup.!error.sftp_test'] = "La connexion SFTP a échoué! Veuillez valider vos paramètres et essayer de nouveau.";
$lang['AdminSystemBackup.!error.amazons3_test'] = "La connexion à AmazonS3 a échoué. Veuillez vérifier vos paramètres et essayer à nouveau. Notez que les connexions sont sensibles à la casse.";
$lang['AdminSystemBackup.ftp.boxtitle_backup'] = "FTP sécurisé";
$lang['AdminSystemBackup.ftp.field_host'] = "Nom d'hôte";
$lang['AdminSystemBackup.ftp.field_port'] = "Port";
$lang['AdminSystemBackup.ftp.field_username'] = "Nom d'utilisateur";
$lang['AdminSystemBackup.ftp.field_password'] = "Mot de passe";
$lang['AdminSystemBackup.ftp.field_path'] = "chemin";
$lang['AdminSystemBackup.ftp.field_rate'] = "Sauvegarde à chaque";
$lang['AdminSystemBackup.ftp.field_backupsubmit'] = "Mettre à jour les paramètres";
$lang['AdminSystemBackup.ftp.text_test'] = "Tester ces paramètres";
$lang['AdminSystemBackup.index.field_uploadbackup'] = "Forcer les sauvegardes hors-site";
$lang['AdminSystemBackup.!error.backup_frequency'] = "Fréquence de sauvegarde invalide.";
$lang['AdminSystemBackup.ftp.page_title'] = "Paramètres> Système> Sauvegarde> Secure FTP";
$lang['AdminSystemBackup.amazon.page_title'] = "Paramètres > Système > Sauvegarde > Amazon S3";
$lang['AdminSystemBackup.amazon.boxtitle_backup'] = "Amazon S3";
$lang['AdminSystemBackup.amazon.field_accesskey'] = "Clé d'accès";
$lang['AdminSystemBackup.amazon.field_secretkey'] = "Clé secrète";
$lang['AdminSystemBackup.amazon.field_bucket'] = "Bucket";
$lang['AdminSystemBackup.amazon.field_rate'] = "Sauvegarder chaque";
$lang['AdminSystemBackup.amazon.field_backupsubmit'] = "Mettre à jour les paramètres";
$lang['AdminSystemBackup.amazon.text_test'] = "Essayer ces paramètres";
$lang['AdminSystemBackup.index.page_title'] = "Paramètres > Système > Sauvegarde > Sur demande";
$lang['AdminSystemBackup.index.boxtitle_index'] = "A la demande";
$lang['AdminSystemBackup.index.field_downloadbackup'] = "Télécharger la sauvegarde";
$lang['AdminSystemBackup.index.text_note'] = "Ici, vous pouvez télécharger une copie de sauvegarde de votre base de données Blesta vers votre ordinateur ou l'envoyer automatiquement sur un serveur SFTP et/ou Amazon S3 préconfiguré.";
$lang['AdminSystemBackup.amazon.field_region'] = "Région";
?>