<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemUpgrade.index.boxtitle_upgrade'] = "Options de mise à jour";
$lang['AdminSystemUpgrade.index.field_upgradesubmit'] = "Mettre à jour les paramètres";
$lang['AdminSystemUpgrade.index.page_title'] = "Paramètres > Système > Options de mise à niveau";
$lang['AdminSystemUpgrade.index.no_results'] = "Les options de mise à niveau ne sont pas disponibles en ce moment.";
?>