<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyThemes.!error.import_file.missing'] = "Veuillez télécharger un thème à importer.";
$lang['AdminCompanyThemes.!error.import_file.theme_type_admin'] = "Le thème importé n'est pas un thème de l'interface administrateur.";
$lang['AdminCompanyThemes.!error.import_file.theme_type_client'] = "Le thème importé n'es pas un thème pour l'interface client. ";
$lang['AdminCompanyThemes.!success.themes_updated'] = "Le thème a été mis à jour avec succès.";
$lang['AdminCompanyThemes.!success.theme_deleted'] = "Le thème \"%1\$s\" a été supprimé avec succès."; // %1$s is the name of the theme
$lang['AdminCompanyThemes.!success.theme_updated'] = "Le thème \"%1\$s\" a été mis à jour avec succès."; // %1$s is the name of the theme
$lang['AdminCompanyThemes.!success.theme_added'] = "Le thème \"%1\$s\" a été ajouté avec succès."; // %1$s is the name of the theme
$lang['AdminCompanyThemes.index.page_title'] = "Paramètres > Compagnie > Apparence > Thèmes";
$lang['AdminCompanyThemes.index.boxtitle_themes'] = "Thèmes";
$lang['AdminCompanyThemes.index.categorylink_addtheme'] = "Ajouter un thème";
$lang['AdminCompanyThemes.index.field_themessubmit'] = "Choisir le modèle";
$lang['AdminCompanyThemes.index.heading_color'] = "Schéma de couleur";
$lang['AdminCompanyThemes.index.heading_name'] = "Nom";
$lang['AdminCompanyThemes.index.heading_options'] = "Options";
$lang['AdminCompanyThemes.index.option_edit'] = "Modifier";
$lang['AdminCompanyThemes.index.option_delete'] = "Effacer";
$lang['AdminCompanyThemes.index.option_export'] = "Exportation";
$lang['AdminCompanyThemes.index.no_results'] = "Il n'y a pas de thèmes de ce type.";
$lang['AdminCompanyThemes.index.confirm_deletetheme'] = "Êtes-vous sur de vouloir effacer ce thème?";
$lang['AdminCompanyThemes.!theme.tooltip_theme_header_bg_color'] = "Définit le dégradé de couleur de l'arrière-plan de l'en-tête.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_header_text_color'] = "Définit la couleur de texte / liens dans l'en-tête.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_navigation_background_color'] = "Définit la couleur de fond du menu de navigation.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_navigation_text_color'] = "Défini la couleur du texte du menu de navigation.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_navigation_text_hover_color'] = "Définit la couleur du texte des menus de navigation et de sous-navigation lors qu'en surbrillance.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_subnavigation_bg_color'] = "Définit le dégradé de couleur de l'en-tête de sous-navigation.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_subnavigation_text_color'] = "Définit la couleur du texte de l'en-tête de sous-navigation.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_subnavigation_text_active_color'] = "Définit la couleur du texte de l'en-tête de sous-navigation lorsqu'il est actif.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_widget_heading_bg_color'] = "Définit le dégradé de couleur d'arrière-plan de l'en-tête de la boîte à widgets.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_widget_icon_heading_bg_color'] = "Définit la couleur du dégradé de l'arrière-fond de la boîte widget ";
$lang['AdminCompanyThemes.!theme.tooltip_theme_box_text_color'] = "Définit la couleur du texte dans les en-têtes des widgets.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_text_shadow'] = "Définit la couleur de l'ombre du texte";
$lang['AdminCompanyThemes.!theme.tooltip_theme_actions_text_color'] = "Définit la couleur des liens";
$lang['AdminCompanyThemes.!theme.tooltip_theme_highlight_bg_color'] = "Définit la couleur de surbrillance (mouse-over) pour la pagination et les lignes de tableau.";
$lang['AdminCompanyThemes.!theme.tooltip_logo_url'] = "Adresse (URL) de l'image du logo de l'entête.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_page_title_background_color'] = "Définit la couleur du dégradé de l'arrière-plan du titre de la page.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_page_title_text_color'] = "Définit la couleur du titre de la page.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_navigation_text_active_color'] = "Définit la couleur de texte dans le menu de navigation lorsqu'il est actif.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_page_background_color'] = "Définit la couleur d'arrière-plan de la zone de contenu.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_link_color'] = "Définit la couleur des liens.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_link_settings_color'] = "Définit la couleur des liens dans la section Paramètres de la barre latérale.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_panel_header_background_color'] = "Définit la couleur du dégradé de l’entête du contenu de la page";
$lang['AdminCompanyThemes.!theme.tooltip_theme_panel_header_text_color'] = "Paramètre la couleur du texte de l'entête du contenu de la page.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_highlight_hover_color'] = "Définit la couleur de surbrillance (au survol) de diverses sections.";
$lang['AdminCompanyThemes.add.page_title'] = "Configuration > Compagnie > Apparence > Nouveau Thème";
$lang['AdminCompanyThemes.add.boxtitle_addtheme'] = "Nouveau thème";
$lang['AdminCompanyThemes.add.heading_options'] = "Créer des options de thème";
$lang['AdminCompanyThemes.add.heading_import'] = "Importer un thème";
$lang['AdminCompanyThemes.add.heading_manual'] = "Options de thème";
$lang['AdminCompanyThemes.add.add_type_import'] = "Importer un thème";
$lang['AdminCompanyThemes.add.add_type_manual'] = "Spécifier les options manuellement";
$lang['AdminCompanyThemes.add.field_import_file'] = "Importation d'un fichier thème";
$lang['AdminCompanyThemes.add.field_name'] = "Nom";
$lang['AdminCompanyThemes.add.field_addthemesubmit'] = "Créer un thème";
$lang['AdminCompanyThemes.add.field_theme_header_text_color'] = "Couleur du texte de l'entête";
$lang['AdminCompanyThemes.add.field_theme_navigation_background_color'] = "Couleur de l'arrière-plan de la navigation";
$lang['AdminCompanyThemes.add.field_theme_navigation_text_hover_color'] = "Couleur du texte de la navigation lorsque la souris est sur le texte";
$lang['AdminCompanyThemes.add.field_theme_subnavigation_bg_color'] = "Couleur de l'arrière plan de la sous-navigation";
$lang['AdminCompanyThemes.add.field_theme_subnavigation_text_color'] = "Couleur du texte de la sous-navigation";
$lang['AdminCompanyThemes.add.field_theme_subnavigation_text_active_color'] = "Couleur du texte actif de la sous-navigation";
$lang['AdminCompanyThemes.add.field_theme_widget_heading_bg_color'] = "Couleur d'arrière-plan du titre de la boite Widget";
$lang['AdminCompanyThemes.add.field_theme_widget_icon_heading_bg_color'] = "Couleur de fond de l'icône d'en-tête de la boîte de widget";
$lang['AdminCompanyThemes.add.field_theme_box_text_color'] = "Couleur de la boîte de texte";
$lang['AdminCompanyThemes.add.field_theme_text_shadow'] = "Couleur de l'ombre du texte";
$lang['AdminCompanyThemes.add.field_theme_actions_text_color'] = "Couleur du lien";
$lang['AdminCompanyThemes.add.field_theme_highlight_bg_color'] = "Couleur de surbrillance de l'arrière-plan";
$lang['AdminCompanyThemes.add.field_theme_header_bg_color'] = "Couleur de l’arrière-plan de l’entête. ";
$lang['AdminCompanyThemes.add.field_theme_navigation_text_color'] = "Couleur du texte de navigation";
$lang['AdminCompanyThemes.add.field_logo_url'] = "Logo de l'entête. ";
$lang['AdminCompanyThemes.add.field_theme_page_title_background_color'] = "Couleur d'arrière plan du titre de la page";
$lang['AdminCompanyThemes.add.field_theme_page_title_text_color'] = "Couleur du texte du titre de la page";
$lang['AdminCompanyThemes.add.field_theme_navigation_text_active_color'] = "Couleur du texte actif de navigation";
$lang['AdminCompanyThemes.add.field_theme_page_background_color'] = "Couleur de l'arrière plan de la page";
$lang['AdminCompanyThemes.add.field_theme_link_color'] = "Couleur du lien texte";
$lang['AdminCompanyThemes.add.field_theme_link_settings_color'] = "Couleur du texte du lien Paramètres";
$lang['AdminCompanyThemes.add.field_theme_panel_header_background_color'] = "Couleur de fond de l'entête de page";
$lang['AdminCompanyThemes.add.field_theme_panel_header_text_color'] = "Couleur du texte du contenu de l'en-tête de la page";
$lang['AdminCompanyThemes.add.field_theme_highlight_hover_color'] = "Couleur de l'arrière-plan";
$lang['AdminCompanyThemes.edit.page_title'] = "Paramètres > Compagnie > Aspect > Modifier le thème";
$lang['AdminCompanyThemes.edit.boxtitle_edittheme'] = "Modifier le thème";
$lang['AdminCompanyThemes.edit.field_name'] = "Nom";
$lang['AdminCompanyThemes.edit.field_editthemesubmit'] = "Mettre à jour le thème";
$lang['AdminCompanyThemes.edit.field_theme_header_text_color'] = "Couleur du texte de l'entête.";
$lang['AdminCompanyThemes.edit.field_theme_navigation_text_hover_color'] = "Couleur de survol du texte de la navigation";
$lang['AdminCompanyThemes.edit.field_theme_subnavigation_bg_color'] = "Couleur d'arrière-plan de la sous-navigation";
$lang['AdminCompanyThemes.edit.field_theme_subnavigation_text_color'] = "Couleur du texte de la sous-navigation";
$lang['AdminCompanyThemes.edit.field_theme_subnavigation_text_active_color'] = "Couleur du texte actif de sous-navigation";
$lang['AdminCompanyThemes.edit.field_theme_widget_heading_bg_color'] = "Couleur d'arrière plan de l'entête de la boîte Widget.";
$lang['AdminCompanyThemes.edit.field_theme_widget_icon_heading_bg_color'] = "Couleur de fond de l'icône d'en-tête de boîte de widget";
$lang['AdminCompanyThemes.edit.field_theme_box_text_color'] = "Couleur de la boîte de texte";
$lang['AdminCompanyThemes.edit.field_theme_text_shadow'] = "Couleur de l'ombre du texte";
$lang['AdminCompanyThemes.edit.field_theme_actions_text_color'] = "Couleur du texte de lien";
$lang['AdminCompanyThemes.edit.field_theme_highlight_bg_color'] = "Couleur de la surbrillance de l'arrière-plan";
$lang['AdminCompanyThemes.edit.field_theme_header_bg_color'] = "Couleur d'arrière plan de l’entête ";
$lang['AdminCompanyThemes.edit.field_theme_navigation_background_color'] = "Couleur d'arrière plan de la navigation";
$lang['AdminCompanyThemes.edit.field_theme_navigation_text_color'] = "Couleur du texte de navigation";
$lang['AdminCompanyThemes.edit.field_logo_url'] = "Logo d'entête";
$lang['AdminCompanyThemes.edit.field_theme_page_title_background_color'] = "Couleur de l'arrière plan du titre de la page";
$lang['AdminCompanyThemes.edit.field_theme_page_title_text_color'] = "Couleur du texte du titre de la page";
$lang['AdminCompanyThemes.edit.field_theme_navigation_text_active_color'] = "Couleur du texte actif de navigation.";
$lang['AdminCompanyThemes.edit.field_theme_page_background_color'] = "Couleur d'arrière-plan de la page";
$lang['AdminCompanyThemes.edit.field_theme_link_color'] = "Couleur du texte du lien";
$lang['AdminCompanyThemes.edit.field_theme_link_settings_color'] = "Couleur du texte du lien des paramètres";
$lang['AdminCompanyThemes.edit.field_theme_panel_header_background_color'] = "Couleur d'arrière plan du contenu de l'entête de page";
$lang['AdminCompanyThemes.edit.field_theme_panel_header_text_color'] = "Couleur du texte du contenu de page.";
$lang['AdminCompanyThemes.edit.field_theme_highlight_hover_color'] = "Couleur de surbrillance d'arrière-plan";
$lang['AdminCompanyThemes.!theme.tooltip_theme_box_shadow_color'] = "Définit la couleur des ombres de la boîte.";
$lang['AdminCompanyThemes.add.field_theme_box_shadow_color'] = "Couleur de l'ombre de la boîte";
$lang['AdminCompanyThemes.edit.field_theme_box_shadow_color'] = "Couleur de l'ombre de la boîte";
$lang['AdminCompanyThemes.!theme.tooltip_theme_highlight_navigation_text_color_top'] = "Définit la couleur du texte dans la navigation supérieure";
$lang['AdminCompanyThemes.!theme.tooltip_theme_highlight_navigation_hover_text_color_top'] = "Définit la couleur de surbrillance (survolée) du texte dans la navigation du haut.";
$lang['AdminCompanyThemes.add.field_theme_highlight_navigation_text_color_top'] = "Couleur du texte de navigation supérieure";
$lang['AdminCompanyThemes.add.field_theme_highlight_navigation_hover_text_color_top'] = "Couleur du texte actif dans le menu de navigation supérieur";
$lang['AdminCompanyThemes.edit.field_theme_highlight_navigation_text_color_top'] = "Couleur du texte de la navigation supérieure";
$lang['AdminCompanyThemes.edit.field_theme_highlight_navigation_hover_text_color_top'] = "Couleur du texte actif de la navigation supérieure";
?>