<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminLogin.index.field_password'] = "Mot de passe";
$lang['AdminLogin.index.field_rememberme'] = "Se souvenir de moi sur cet ordinateur.";
$lang['AdminLogin.index.field_loginsubmit'] = "Connexion";
$lang['AdminLogin.index.link_resetpassword'] = "Réinitialiser mon mot de passe";
$lang['AdminLogin.otp.field_password'] = "Mot de passe pour une fois";
$lang['AdminLogin.otp.field_loginsubmit'] = "Connexion";
$lang['AdminLogin.otp.link_login'] = "Annuler, Connexion";
$lang['AdminLogin.reset.title_adminarea'] = "%1\$s | Récupération du mot de passe"; // %1$s is the company name
$lang['AdminLogin.reset.field_resetsubmit'] = "Réinitialiser le mot de passe";
$lang['AdminLogin.reset.link_login'] = "Annuler, connexion";
$lang['AdminLogin.confirmreset.title_adminarea'] = "%1\$s | Confirmer la réinitialisation du mot de passe"; // %1$s is the company name
$lang['AdminLogin.confirmreset.field_new_password'] = "Nouveau mot de passe";
$lang['AdminLogin.confirmreset.field_confirm_password'] = "Confirmer le nouveau mot de passe";
$lang['AdminLogin.confirmreset.field_resetsubmit'] = "Établir le mot de passe";
$lang['AdminLogin.confirmreset.link_login'] = "Annuler, Connexion";
$lang['AdminLogin.!error.unknown_user'] = "Ce nom d'utilisateur n'est pas reconnu ou il est impossible de réinitialiser le mot de passe.";
$lang['AdminLogin.!success.reset_sent'] = "Un courriel de confirmation a été envoyé à l'adresse au dossier.";
$lang['AdminLogin.index.page_title'] = "Connexion";
$lang['AdminLogin.otp.page_title'] = "Connexion OTP";
$lang['AdminLogin.reset.page_title'] = "Réinitialiser le mot de passe";
$lang['AdminLogin.confirmreset.page_title'] = "Confirmer le changement de mot de passe.";
$lang['AdminLogin.setup.page_title'] = "Configuration initiale";
$lang['AdminLogin.setup.title_adminarea'] = "Configuration initiale"; // %1$s is the company name
$lang['AdminLogin.setup.field_license_key'] = "Clé de licence";
$lang['AdminLogin.setup.heading_create_account'] = "Créer votre compte de membre d'équipe";
$lang['AdminLogin.setup.field_first_name'] = "Prénom";
$lang['AdminLogin.setup.field_last_name'] = "Nom de famille";
$lang['AdminLogin.setup.field_username'] = "Nom d'utilisateur";
$lang['AdminLogin.setup.field_email'] = "Adresse courriel";
$lang['AdminLogin.setup.field_password'] = "Mot de passe";
$lang['AdminLogin.setup.field_confirm_password'] = "Confirmer le mot de passe";
$lang['AdminLogin.setup.field_enter_key_true'] = "J'ai une clé de licence à entrer";
$lang['AdminLogin.setup.field_enter_key_false'] = "Je veut commencer un essai gratuit de 30 jours";
$lang['AdminLogin.setup.field_submit'] = "Terminer";
$lang['AdminLogin.index.title_adminarea'] = "%1\$s | Section du personnel"; // %1$s is the company name
$lang['AdminLogin.index.field_username'] = "Nom d'usager";
$lang['AdminLogin.reset.field_username'] = "Nom d'utilisateur";
$lang['AdminLogin.!info.reset_password'] = "Entrez votre nom d'utilisateur ci-dessous et un lien vous sera envoyé par e-mail afin que vous puissiez définir un nouveau mot de passe.";
$lang['AdminLogin.!info.otp'] = "Une authentification à deux facteurs est requise pour cet utilisateur. Veuillez entrer votre mot de passe à usage unique (OTP) ci-dessous.";
$lang['AdminLogin.otp.title_adminarea'] = "%1\$s | Section du personnel"; // %1$s is the company name
?>