<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.heading_quicklinks'] = "Liens rapides";
$lang['AdminMain.index.no_quicklinks'] = "Aucun lien rapide n'as été défini.";
$lang['AdminMain.index.manage_widgets'] = "Gérer les widgets";
$lang['AdminMain.index.customize_dashboard'] = "Personnaliser tableau de bord";
$lang['AdminMain.managewidgets.text_version'] = "ver %1\$s"; // %1$s is the version number of the plugin
$lang['AdminMain.managewidgets.text_author'] = "Auteur:";
$lang['AdminMain.updatedashboard.text_layout'] = "Veuillez choisir une disposition ci-bas pour paramétrer votre tableau de bord.";
$lang['AdminMain.!error.delete_event.staff_id'] = "Seul le créateur de l'événement peut supprimer cet événement.";
$lang['AdminMain.!error.event_editable'] = "Seulement le créateur de l'événement peut l'effacer.";
$lang['AdminMain.!success.event_added'] = "L'événement a été ajouté avec succèes!";
$lang['AdminMain.!success.event_edited'] = "Cet événement a été mis à jour avec succès!";
$lang['AdminMain.!success.event_deleted'] = "L'événement a été effacé avec succès!";
$lang['AdminMain.index.page_title'] = "Tableau de bord";
$lang['AdminMain.managewidgets.text_widgets'] = "Faites glisser les widgets de la droite vers la gauche pour les ajouter à votre tableau de bord, ou de gauche à droite pour les supprimer.";
$lang['AdminMain.calendar.page_title'] = "Calendrier";
$lang['AdminMain.calendar.boxtitle_calendar'] = "Calendrier";
$lang['AdminMain.calendar.categorylink_addevent'] = "Créer un événement";
$lang['AdminMain.calendar.category_month'] = "Mois";
$lang['AdminMain.calendar.category_week'] = "Semaine";
$lang['AdminMain.calendar.category_day'] = "Jour";
$lang['AdminMain.getEvents.shared_event_title'] = "%2\$s %3\$s: %1\$s"; // %1$s is the event title, %2$s is the staff's first name, %3$s is the staff's last name
$lang['AdminMain.addevent.boxtitle_addevent'] = "Créer un événement";
$lang['AdminMain.addevent.field_title'] = "Titre";
$lang['AdminMain.addevent.field_start_date'] = "Date de départ";
$lang['AdminMain.addevent.field_end_date'] = "Date de fin";
$lang['AdminMain.addevent.field_shared'] = "Rendre cet événement visible par d'autres employés";
$lang['AdminMain.addevent.field_all_day'] = "Toute la journée";
$lang['AdminMain.addevent.field_addeventsubmit'] = "Créer un événement";
$lang['AdminMain.editevent.boxtitle_editevent'] = "Modifier un événement";
$lang['AdminMain.editevent.field_title'] = "Titre";
$lang['AdminMain.editevent.field_start_date'] = "Date de départ";
$lang['AdminMain.editevent.field_end_date'] = "Date de fin";
$lang['AdminMain.editevent.field_shared'] = "Faire de cet événement visible par d'autres employés";
$lang['AdminMain.editevent.field_all_day'] = "Toute la journée";
$lang['AdminMain.editevent.field_editeventsubmit'] = "Mettre à jour l'événement";
$lang['AdminMain.editevent.field_deleteeventsubmit'] = "Effacer l'événement";
$lang['AdminMain.editevent.confirm_delete'] = "Voulez-vous réellement effacer cet événement?";
?>