<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminReports.index.page_title'] = "Rapports de facturation";
$lang['AdminReports.index.box_title'] = "Rapports";
$lang['AdminReports.index.field_format'] = "Format";
$lang['AdminReports.index.field_report_type'] = "Type de rapport";
$lang['AdminReports.index.field_submit'] = "Exporter";
$lang['AdminReports.index.reports'] = "Générer";
$lang['AdminReports.index.customize'] = "Personnaliser";
?>