<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyClientOptions.!success.field_updated'] = "Le champ personnalisé du client a été mis à jour avec succès.";
$lang['AdminCompanyClientOptions.!success.field_created'] = "Le champ personnalisé du client a été créé avec succès.";
$lang['AdminCompanyClientOptions.!success.field_deleted'] = "Le champ personnalisé du client a été supprimé avec succès.";
$lang['AdminCompanyClientOptions.!success.requiredfields_updated'] = "Les champs requis ont été mis à jour avec succès.";
$lang['AdminCompanyClientoptions.customfields.page_title'] = "Paramètres> Société> Options client> Champs personnalisés du client> Parcourir";
$lang['AdminCompanyClientOptions.customfields.boxtitle_browse'] = "Parcourir les champs personnalisés du client";
$lang['AdminCompanyClientOptions.customfields.categorylink_addfield'] = "Créer un champ";
$lang['AdminCompanyClientOptions.customfields.text_name'] = "Nom";
$lang['AdminCompanyClientOptions.customfields.text_type'] = "Type";
$lang['AdminCompanyClientOptions.customfields.text_required'] = "Champs obligatoires";
$lang['AdminCompanyClientOptions.customfields.text_visible'] = "Visible pour les clients";
$lang['AdminCompanyClientOptions.customfields.text_read_only'] = "Lecture seule pour les clients";
$lang['AdminCompanyClientOptions.customfields.text_options'] = "Options";
$lang['AdminCompanyClientOptions.customfields.text_yes'] = "Oui";
$lang['AdminCompanyClientOptions.customfields.text_no'] = "Non";
$lang['AdminCompanyClientOptions.customfields.option_edit'] = "Modifier";
$lang['AdminCompanyClientOptions.customfields.option_delete'] = "Supprimer";
$lang['AdminCompanyClientOptions.customfields.confirm_delete'] = "La suppression de ce champ personnalisé supprimera toutes les données qui y sont stockées pour chaque client de ce groupe. Êtes-vous sûr de vouloir supprimer ce champ personnalisé?";
$lang['AdminCompanyClientOptions.customfields.no_results'] = "Il n'y a pas de champs personnalisés.";
$lang['AdminCompanyClientOptions.tooltip.is_lang'] = "Cochez cette case uniquement si vous avez ajouté une définition de langue pour ce champ personnalisé dans le fichier de langue personnalisé.";
$lang['AdminCompanyClientOptions.tooltip.read_only'] = "En cochant cette case, ce champ personnalisé ne pourra plus être modifié par le client.";
$lang['AdminCompanyClientoptions.addcustomfield.page_title'] = "Paramètres> Société> Options client> Champs personnalisés du client> Ajouter un champ personnalisé";
$lang['AdminCompanyClientOptions.addcustomfield.boxtitle_add'] = "Ajouter un champ personnalisé";
$lang['AdminCompanyClientOptions.addcustomfield.field_client_group_id'] = "Groupe de clients";
$lang['AdminCompanyClientOptions.addcustomfield.field_name'] = "Nom";
$lang['AdminCompanyClientOptions.addcustomfield.field_is_lang'] = "Le nom est une définition de langage";
$lang['AdminCompanyClientOptions.addcustomfield.field_type'] = "Type";
$lang['AdminCompanyClientOptions.addcustomfield.field_show_client'] = "Visible pour les clients";
$lang['AdminCompanyClientOptions.addcustomfield.field_read_only'] = "Lecture seule pour les clients";
$lang['AdminCompanyClientOptions.addcustomfield.field_required'] = "Champ obligatoire";
$lang['AdminCompanyClientOptions.addcustomfield.field_regex'] = "Expressions régulières personnalisé";
$lang['AdminCompanyClientOptions.addcustomfield.field_encrypted'] = "Crypter les valeurs";
$lang['AdminCompanyClientOptions.addcustomfield.field_addsubmit'] = "Ajouter un champ personnalisé";
$lang['AdminCompanyClientOptions.addcustomfield.field_checkbox_value'] = "Valeur";
$lang['AdminCompanyClientOptions.addcustomfield.categorylink_select'] = "Ajouter une option supplémentaire";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_value'] = "Valeur";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_option'] = "Nom de l'option";
$lang['AdminCompanyClientOptions.addcustomfield.text_remove'] = "Supprimer";
$lang['AdminCompanyClientoptions.editcustomfield.page_title'] = "Paramètres> Société> Options client> Champs personnalisés du client> Modifier le champ personnalisé";
$lang['AdminCompanyClientOptions.editcustomfield.boxtitle_edit'] = "Modifier le champ personnalisé";
$lang['AdminCompanyClientOptions.editcustomfield.field_name'] = "Nom";
$lang['AdminCompanyClientOptions.editcustomfield.field_is_lang'] = "Le nom est une définition de langage";
$lang['AdminCompanyClientOptions.editcustomfield.field_type'] = "Type";
$lang['AdminCompanyClientOptions.editcustomfield.field_show_client'] = "Visible pour les clients";
$lang['AdminCompanyClientOptions.editcustomfield.field_read_only'] = "Lecture seule pour les clients";
$lang['AdminCompanyClientOptions.editcustomfield.field_required'] = "Champ obligatoire";
$lang['AdminCompanyClientOptions.editcustomfield.field_regex'] = "Expression régulière personnalisée";
$lang['AdminCompanyClientOptions.editcustomfield.field_encrypted'] = "Crypter les valeurs";
$lang['AdminCompanyClientOptions.editcustomfield.field_editsubmit'] = "Modifier le champ personnalisé";
$lang['AdminCompanyClientOptions.editcustomfield.field_checkbox_value'] = "Valeur";
$lang['AdminCompanyClientOptions.editcustomfield.categorylink_select'] = "Ajouter une option supplémentaire";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_value'] = "Valeur";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_option'] = "Nom de l'option";
$lang['AdminCompanyClientOptions.editcustomfield.text_remove'] = "Supprimer";
$lang['AdminCompanyClientOptions.getRequired.no'] = "Non";
$lang['AdminCompanyClientOptions.getRequired.yes'] = "Oui";
$lang['AdminCompanyClientOptions.getRequired.regex'] = "Expression régulière personnalisée";
$lang['AdminCompanyClientoptions.requiredfields.page_title'] = "Paramètres> Société> Options client> Champs personnalisés du client> Champs obligatoires du client";
$lang['AdminCompanyClientOptions.requiredfields.boxtitle'] = "Champs obligatoires du client";
$lang['AdminCompanyClientOptions.requiredfields.description'] = "Vérifiez les champs qui devraient être obligatoires lors de la création ou de la mise à jour d'un client ou d'un contact.";
$lang['AdminCompanyClientOptions.requiredfields.field_company'] = "Société/Organisation";
$lang['AdminCompanyClientOptions.requiredfields.field_title'] = "Titre";
$lang['AdminCompanyClientOptions.requiredfields.field_address1'] = "Adresse 1";
$lang['AdminCompanyClientOptions.requiredfields.field_address2'] = "Adresse 2";
$lang['AdminCompanyClientOptions.requiredfields.field_city'] = "Ville";
$lang['AdminCompanyClientOptions.requiredfields.field_country'] = "Pays";
$lang['AdminCompanyClientOptions.requiredfields.field_state'] = "Etat/Province";
$lang['AdminCompanyClientOptions.requiredfields.field_zip'] = "Npa/Code postal";
$lang['AdminCompanyClientOptions.requiredfields.field_email'] = "E-mail";
$lang['AdminCompanyClientOptions.requiredfields.text_submit'] = "Mettre à jour les paramètres";
$lang['AdminCompanyClientOptions.requiredfields.field_first_name'] = "Prénom";
$lang['AdminCompanyClientOptions.requiredfields.field_last_name'] = "Nom";
$lang['AdminCompanyClientOptions.!notice.group_settings'] = "REMARQUE: ces paramètres s'appliquent uniquement aux groupes de clients qui héritent leurs paramètres de la société.";
$lang['AdminCompanyClientOptions.!tooltip.state'] = "Soyez prudent lorsque vous demandez qu'un État / une province soit sélectionné. Certains pays n'ont pas d'Etats. Les clients de ces pays ne pourraient pas enregistrer leurs coordonnées. Nous vous recommandons de ne pas rendre obligatoire ce champ.";
?>