<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminBilling.invoices.boxtitle_invoices'] = "Factures";
$lang['AdminBilling.invoices.heading_invoice'] = "Facture #";
$lang['AdminBilling.invoices.heading_recurinvoice'] = "Récurrent #";
$lang['AdminBilling.invoices.heading_client'] = "Client #";
$lang['AdminBilling.invoices.heading_amount'] = "Montant";
$lang['AdminBilling.invoices.heading_paid'] = "Payé";
$lang['AdminBilling.invoices.heading_due'] = "dû";
$lang['AdminBilling.invoices.heading_dateclosed'] = "Date fermeture";
$lang['AdminBilling.invoices.heading_datebilled'] = "Date Facturé";
$lang['AdminBilling.invoices.heading_datedue'] = "Date dû";
$lang['AdminBilling.invoices.heading_options'] = "Options";
$lang['AdminBilling.invoices.heading_term'] = "Terme
";
$lang['AdminBilling.invoices.heading_duration'] = "Durée";
$lang['AdminBilling.invoices.heading_count'] = "Compter
";
$lang['AdminBilling.invoices.category_open'] = "Ouvrir";
$lang['AdminBilling.invoices.category_drafts'] = "Brouillons";
$lang['AdminBilling.invoices.category_closed'] = "Fermé";
$lang['AdminBilling.invoices.category_voided'] = "Annulé
";
$lang['AdminBilling.invoices.category_pastdue'] = "Passé raison";
$lang['AdminBilling.invoices.category_recurring'] = "Récurrent";
$lang['AdminBilling.invoices.option_edit'] = "Éditer";
$lang['AdminBilling.invoices.option_view'] = "Voir";
$lang['AdminBilling.invoices.option_pay'] = "Payer";
$lang['AdminBilling.invoices.subtotal_w_tax'] = "%1\$s +taxe"; // %1$s is the sub total amount
$lang['AdminBilling.invoices.term_day'] = "%1\$s jour"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_week'] = "%1\$s semaine
"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_month'] = "%1\$s mois"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_year'] = "%1\$s année
"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_day_plural'] = "%1\$s jours"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_week_plural'] = "%1\$s semaines
"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_month_plural'] = "%1\$s mois"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.term_year_plural'] = "%1\$s années
"; // %1$s is the term (an integer)
$lang['AdminBilling.invoices.duration_finite'] = "%1\$s fois"; // %1$s is the number of times the recurring invoice will be created
$lang['AdminBilling.invoices.no_results'] = "Il n'y a pas des factures avec ce statut.
";
$lang['AdminBilling.services.boxtitle_services'] = "Services";
$lang['AdminBilling.services.heading_term'] = "Terme
";
$lang['AdminBilling.services.heading_dateadded'] = "Ajouté le";
$lang['AdminBilling.services.heading_daterenews'] = "Date de renouvellements";
$lang['AdminBilling.services.heading_datesuspended'] = "Date de suspension
";
$lang['AdminBilling.invoices.category_pending'] = "En attendant";
$lang['AdminBilling.transactions.boxtitle_transactions'] = "Transactions
";
$lang['AdminBilling.transactions.heading_client'] = "Client #";
$lang['AdminBilling.transactions.heading_type'] = "Type
";
$lang['AdminBilling.transactions.heading_amount'] = "Montant";
$lang['AdminBilling.transactions.heading_credit'] = "Crédité";
$lang['AdminBilling.transactions.heading_applied'] = "Appliqué
";
$lang['AdminBilling.transactions.heading_number'] = "Number";
$lang['AdminBilling.transactions.heading_date'] = "Date";
$lang['AdminBilling.transactions.heading_options'] = "Options
";
$lang['AdminBilling.transactions.category_approved'] = "Approuvé";
$lang['AdminBilling.transactions.category_declined'] = "Refusée";
$lang['AdminBilling.transactions.category_voided'] = "Annulé
";
$lang['AdminBilling.transactions.category_error'] = "Erreur";
$lang['AdminBilling.transactions.category_pending'] = "En attendant";
$lang['AdminBilling.transactions.category_refunded'] = "Remboursé
";
$lang['AdminBilling.transactions.category_returned'] = "Retourné
";
$lang['AdminBilling.transactions.option_edit'] = "Éditer
";
$lang['AdminBilling.transactions.no_results'] = "Il n'ya pas de transactions avec ce statut.";
$lang['AdminBilling.transactions.headingexpand_invoice'] = "Facture
";
$lang['AdminBilling.transactions.headingexpand_amount'] = "Montant";
$lang['AdminBilling.transactions.headingexpand_appliedon'] = "Appliqué le
";
$lang['AdminBilling.transactions.applied_no_results'] = "Cette transaction n'a pas été appliquée à aucun factures.
";
$lang['AdminBilling.invoices.headingexpand_paymenttype'] = "Type de paiement";
$lang['AdminBilling.invoices.headingexpand_amount'] = "Montant";
$lang['AdminBilling.invoices.headingexpand_applied'] = "Appliqué";
$lang['AdminBilling.invoices.headingexpand_appliedon'] = "Appliqué Le";
$lang['AdminBilling.invoices.headingexpand_options'] = "Options
";
$lang['AdminBilling.invoices.applied_no_results'] = "Cette facture n'a aucun transactions appliquées.";
$lang['AdminBilling.invoices.text_edit'] = "Éditer";
$lang['AdminBilling.!success.invoices_marked_printed'] = "Les factures sélectionnées ont été marquées comme imprimées.";
$lang['AdminBilling.!error.no_invoices_selected'] = "Aucune facture n'as été sélectionnée.";
$lang['AdminBilling.index.open_parethesis'] = "(";
$lang['AdminBilling.index.closed_parethesis'] = ")";
$lang['AdminBilling.index.page_title'] = "Survol de la facturation";
$lang['AdminBilling.index.manage_widgets'] = "Gérer les Widgets";
$lang['AdminBilling.index.customize_dashboard'] = "Personnalisez l'aperçu";
$lang['AdminBilling.index.heading_actions'] = "Mesures à prendre";
$lang['AdminBilling.index.no_actions'] = "Aucun élément d'action en attente.";
$lang['AdminBilling.index.action_printqueue'] = "Items en attente d'impression";
$lang['AdminBilling.index.action_batch'] = "Lot d'articles en attente";
$lang['AdminBilling.updatedashboard.text_layout'] = "Sélectionnez une présentation ci-dessous afin de personnaliser votre aperçu de facturation.";
$lang['AdminBilling.managewidgets.text_widgets'] = "Faites glisser les widgets de la droite vers la gauche pour les ajouter à votre aperçu de facturation, ou de gauche à droite pour les supprimer.";
$lang['AdminBilling.managewidgets.text_version'] = "version %1\$s"; // %1$s is the version number of the plugin
$lang['AdminBilling.managewidgets.text_author'] = "Auteur:";
$lang['AdminBilling.invoices.page_title'] = "Factures";
$lang['AdminBilling.services.page_title'] = "Services de facturation";
$lang['AdminBilling.services.heading_package'] = "Ensemble";
$lang['AdminBilling.services.heading_label'] = "Étiquette";
$lang['AdminBilling.services.heading_datecanceled'] = "Date d'annulation";
$lang['AdminBilling.services.category_active'] = "Actif";
$lang['AdminBilling.services.category_canceled'] = "Annulé";
$lang['AdminBilling.services.category_suspended'] = "Suspendu";
$lang['AdminBilling.services.category_pending'] = "En attente";
$lang['AdminBilling.services.text_never'] = "Jamais";
$lang['AdminBilling.services.no_results'] = "Il n'y a pas de service avec ce statut.";
$lang['AdminBilling.transactions.page_title'] = "Transactions de facturation";
$lang['AdminBilling.printqueue.page_title'] = "Queue d'impression de la facturation";
$lang['AdminBilling.printqueue.category_to_print'] = "Imprimer";
$lang['AdminBilling.printqueue.category_printed'] = "Imprimé précédemment";
$lang['AdminBilling.printqueue.boxtitle_printqueue'] = "Queue d'impression";
$lang['AdminBilling.printqueue.no_results_printed'] = "Il n'y a pas de factures imprimées précédemment.";
$lang['AdminBilling.printqueue.no_results_to_print'] = "Il n'y a pas de factures en attente d'impression.";
$lang['AdminBilling.printqueue.heading_invoice'] = "Facture #";
$lang['AdminBilling.printqueue.heading_client'] = "Client #";
$lang['AdminBilling.printqueue.heading_amount'] = "Montant";
$lang['AdminBilling.printqueue.heading_paid'] = "Payé";
$lang['AdminBilling.printqueue.heading_due'] = "Dû";
$lang['AdminBilling.printqueue.heading_datebilled'] = "Date de Facture";
$lang['AdminBilling.printqueue.heading_datedue'] = "Date d'échéance";
$lang['AdminBilling.printqueue.heading_deliverydatesent'] = "Date d'envoi";
$lang['AdminBilling.printqueue.text_printsubmit'] = "Imprimer";
$lang['AdminBilling.printqueue.text_marksubmit'] = "Marquer comme imprimé";
$lang['AdminBilling.batch.page_title'] = "La facturation par lots";
$lang['AdminBilling.batch.boxtitle_batch'] = "Lot";
$lang['AdminBilling.batch.no_passphrase'] = "Le traitement par lots manuel n'est pas activée.";
$lang['AdminBilling.batch.field_passphrase'] = "Mot de passe";
$lang['AdminBilling.batch.text_batchsubmit'] = "Traitement par lots";
$lang['AdminBilling.services.heading_client'] = "Client #";
$lang['AdminBilling.services.heading_options'] = "Options";
$lang['AdminBilling.services.option_manage'] = "Gérer";
$lang['AdminBilling.services.category_in_review'] = "En révision";
$lang['AdminBilling.services.category_scheduled_cancellation'] = "Prévu";
$lang['AdminBilling.serviceinfo.no_results'] = "Ce service n'as pas de détail.";
$lang['AdminBilling.!error.invalid_passphrase'] = "Le mot de passe saisi n'est pas valide.";
$lang['AdminBilling.services.option_delete'] = "Effacer";
$lang['AdminBilling.services.confirm_delete'] = "Êtes vous sur de vouloir effacer ce service?";
$lang['AdminBilling.batch.text_description'] = "Entrez un mot de passe pour traiter manuellement en lot les factures planifiées pour un auto-prélèvement avec un compte de paiement sauvegardé localement.";
$lang['AdminBilling.invoices.duration_infinite'] = "∞";
$lang['AdminBilling.!success.services_scheduled_cancel'] = "Les services sélectionnés ont été programmées avec succès à être annulé.";
$lang['AdminBilling.!success.services_scheduled_uncancel'] = "Les services sélectionnés ne sont plus programmés pour être annulé.";
$lang['AdminBilling.!error.future_cancel_date'] = "La date d'annulation prévue ne doit pas être dans le passé.";
$lang['AdminBilling.services.action.schedule_cancellation'] = "Programmez L'annulation";
$lang['AdminBilling.services.action.field_action_type_term'] = "Fin du contrat";
$lang['AdminBilling.services.action.field_action_type_date'] = "Date spécifique";
$lang['AdminBilling.services.action.field_action_type_none'] = "Ne pas annuler";
$lang['AdminBilling.services.field_actionsubmit'] = "Envoyer";
$lang['AdminBilling.transactions.heading_reference_id'] = "Référence #";
?>