<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemAutomation.!error.empty_cron_key'] = "Veuillez paramétrer une clé Cron.";
$lang['AdminSystemAutomation.!success.automation_updated'] = "Les paramètres d'automatisation ont été mis à jour avec succès!";
$lang['AdminSystemAutomation.!success.cron_key'] = "La clé de cron a été correctement mis à jour!";
$lang['AdminSystemAutomation.index.boxtitle_automation'] = "Automatisation";
$lang['AdminSystemAutomation.index.heading_status'] = "Statut cron";
$lang['AdminSystemAutomation.index.field_croncommand'] = "Commande cron";
$lang['AdminSystemAutomation.index.field_runcron'] = "Rouler cron manuellement";
$lang['AdminSystemAutomation.index.field_cron_key'] = "Clé Cron";
$lang['AdminSystemAutomation.index.field_cronkey_submit'] = "Mettre à jour la clé de tâche Cron";
$lang['AdminSystemAutomation.index.text_cron_last_ran'] = "La dernière tache Cron a été effectuée le %1\$s."; // %1$s is the date that the cron last ran
$lang['AdminSystemAutomation.index.text_cron_never_ran'] = "La tâche Cron n'as jamais été actionnée.";
$lang['AdminSystemAutomation.index.text_update_key'] = "Mettre à jour la clé Cron";
$lang['AdminSystemAutomation.index.text_generate_code'] = "Générer le code";
$lang['AdminSystemAutomation.index.note_cron_command'] = "Assurez-vous de mettre à jour la commande CRON pour indiquer où PHP est installé si l'installation diffère de ce qui est montré.";
$lang['AdminSystemAutomation.index.page_title'] = "Paramètres > Système > Automatisation";
$lang['AdminSystemAutomation.index.text_cron_currently_running'] = "La tâche cron fonctionne actuellement.";
?>