<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyModules.!success.upgraded'] = "Le module a été mis à jour avec succès.";
$lang['AdminCompanyModules.!success.installed'] = "Le module a été installé avec succès.";
$lang['AdminCompanyModules.!success.uninstalled'] = "Le module a été désinstallé avec succès.";
$lang['AdminCompanyModules.!success.module_updated'] = "Le module a été mis à jour avec succès.";
$lang['AdminCompanyModules.!success.group_added'] = "Le groupe a été ajouté avec succès.";
$lang['AdminCompanyModules.!success.group_updated'] = "Le groupe a été  mis à jour avec succès.";
$lang['AdminCompanyModules.!success.group_deleted'] = "Le groupe a été effacé avec succès.";
$lang['AdminCompanyModules.!success.row_added'] = "Le %1\$s a été ajouté avec succèes."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.!success.row_updated'] = "Le %1\$s a été mis à jour avec succès."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.!success.row_deleted'] = "Le %1\$s a été supprimé."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.available.text_author'] = "Auteur:";
$lang['AdminCompanyModules.available.text_author_url'] = "URL de l'auteur";
$lang['AdminCompanyModules.available.text_none'] = "Il n'y a pas de modules disponibles.";
$lang['AdminCompanyModules.available.btn_install'] = "Installer";
$lang['AdminCompanyModules.installed.text_author'] = "Auteur:";
$lang['AdminCompanyModules.installed.text_author_url'] = "URL de l'auteur";
$lang['AdminCompanyModules.installed.text_none'] = "Il n'y a pas de modules installés.";
$lang['AdminCompanyModules.installed.btn_uninstall'] = "Désinstaller ";
$lang['AdminCompanyModules.installed.btn_manage'] = "Gérer";
$lang['AdminCompanyModules.installed.btn_upgrade'] = "Mise à jour";
$lang['AdminCompanyModules.installed.confirm_uninstall'] = "Êtes-vous sur de vouloir désinstaller ce module?";
$lang['AdminCompanyModules.manage.boxtitle_manage'] = "Gérer %1\$s"; // %1$s is the name of the module
$lang['AdminCompanyModules.addgroup.boxtitle_add'] = "Ajouter %1\$s %2\$s groupe"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.addgroup.btn_add'] = "Ajouter un groupe";
$lang['AdminCompanyModules.addgroup.assigned'] = "%1\$s assignés"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.addgroup.available'] = "%1\$s disponibles."; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.addgroup.text_name'] = "Nom de groupe";
$lang['AdminCompanyModules.addgroup.text_order'] = "Ajouter une commande";
$lang['AdminCompanyModules.editgroup.boxtitle_edit'] = "Modifier le %1\$s %2\$s groupe"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editgroup.btn_edit'] = "Mettre à jour le Groupe";
$lang['AdminCompanyModules.editgroup.assigned'] = "%1\$s assignés"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.editgroup.available'] = "%1\$s disponibles"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.editgroup.text_name'] = "Nom du groupe";
$lang['AdminCompanyModules.editgroup.text_order'] = "Ajouter une commande";
$lang['AdminCompanyModules.available.page_title'] = "Paramètres > Compagnie > Modules > Disponibles";
$lang['AdminCompanyModules.installed.page_title'] = "Paramètres > Compagnie > Modules > Installé";
$lang['AdminCompanyModules.manage.page_title'] = "Paramètres > Compagnie > Modules > Gérer %1\$s"; // %1$s is the name of the module
$lang['AdminCompanyModules.addgroup.page_title'] = "Paramètres > Compagnie > Modules > Ajouter %1\$s %2\$s groupe"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editgroup.page_title'] = "Paramètres > Compagnie > Modules > Modifier {var1 var2} {} Groupe"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.addrow.page_title'] = "Paremètres > Société > Modules > Ajouter %1\$s %2\$s"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editrow.page_title'] = "Paramètres > Compagnie > Modules > Modifier %1\$s %2\$s"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.available.text_version'] = "(ver %1\$s)"; // %1$s is the module's version number
$lang['AdminCompanyModules.installed.text_version'] = "(ver. %1\$s)"; // %1$s is the module's version number
$lang['AdminCompanyModules.!tab.installed'] = "Installé";
$lang['AdminCompanyModules.!tab.available'] = "Disponible";
$lang['AdminCompanyModules.available.boxtitle_module'] = "Modules";
$lang['AdminCompanyModules.installed.boxtitle_installed'] = "Modules";
$lang['AdminCompanyModules.addgroup.force_limits'] = "Forcer les limites %1\$s"; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.addgroup.tooltip_force_limits'] = "Applique des limites strictes pour que le nombre de %1\$s ne dépasse jamais la limite."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editgroup.force_limits'] = "Forcer les limites %1\$s"; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editgroup.tooltip_force_limits'] = "Applique des limites strictes pour que le nombre de %1\$s ne dépasse jamais la limite."; // %1$s is the module row noun (e.g. Server)
?>