<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemHelp.index.heading_user_manual'] = "Guide de l'usager";
$lang['AdminSystemHelp.index.text_user_manual'] = "Curieux de savoir comment configurer Blesta, ou de profiter de quelques-unes des fonctionnalités les plus avancées? Consultez le manuel utilisateur.";
$lang['AdminSystemHelp.index.heading_dev_manual'] = "Manuel du développeur";
$lang['AdminSystemHelp.index.text_dev_manual'] = "Adapté aux besoins des développeurs, le manuel du développeur contient tout ce qu'il y a à savoir sur le développement de la plate-forme Blesta.";
$lang['AdminSystemHelp.index.heading_forums'] = "Forums Communautaires";
$lang['AdminSystemHelp.index.text_forums'] = "Les forums Blesta sont un centre de soutien axé sur la collectivité, où les utilisateurs soumettent des questions et des réponses allant du plus simple au plus complexe.";
$lang['AdminSystemHelp.index.page_title'] = "Paramètres > Système > Aide > Ressources";
$lang['AdminSystemHelp.boxtitle_help'] = "Ressources";
?>