<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMyinfo.!success.updated'] = "Les paramètres de compte ont été mis à jours avec succès.";
$lang['AdminMyinfo.!success.notices_updated'] = "Vos paramètres de notification ont été mis à jour.";
$lang['AdminMyinfo.gettabnames.text_index'] = "Compte";
$lang['AdminMyinfo.gettabnames.text_notices'] = "Avis";
$lang['AdminMyinfo.index.page_title'] = "Mon information";
$lang['AdminMyinfo.index.boxtitle_myinfo'] = "Mon information";
$lang['AdminMyinfo.index.field_username'] = "Nom d'utilisateur";
$lang['AdminMyinfo.index.field_firstname'] = "Prénom";
$lang['AdminMyinfo.index.field_lastname'] = "Nom de famille";
$lang['AdminMyinfo.index.field_email'] = "Courriel";
$lang['AdminMyinfo.index.field_mobileemail'] = "Courriel mobile";
$lang['AdminMyinfo.index.field_newpass'] = "Nouveau mot de passe";
$lang['AdminMyinfo.index.field_confirmpass'] = "Confirmez le mot de passe";
$lang['AdminMyinfo.index.field_twofactormode'] = "Authentification à deux facteurs";
$lang['AdminMyinfo.index.field_twofactorkey'] = "Clé à 2 facteurs";
$lang['AdminMyinfo.index.field_twofactorpin'] = "NIP à deux facteurs";
$lang['AdminMyinfo.index.field_groups'] = "Groupes du personnel";
$lang['AdminMyinfo.index.field_currentpass'] = "Mot de passe actuel";
$lang['AdminMyinfo.index.field_infosubmit'] = "Mise à jour compte";
$lang['AdminMyinfo.notices.heading_notices'] = "Avis par e-mail BCC";
$lang['AdminMyinfo.notices.field_noticesubmit'] = "Avis de mise à jour";
$lang['AdminMyinfo.notices.no_bcc_results'] = "Il n'y a pas d'avis BCC par courriels disponible pour votre groupe de membre du personnel.";
$lang['AdminMyinfo.index.field_otp'] = "Mot de passe à usage unique";
$lang['AdminMyinfo.index.note_otp'] = "Pour confirmer que votre authentification à deux facteurs est correctement configuré, entrez votre mot de passe unique généré.";
$lang['AdminMyinfo.notices.page_title'] = "Mes informations > Avis";
$lang['AdminMyinfo.notices.heading_subscription_notices'] = "Avis de souscription aux courriels";
$lang['AdminMyinfo.notices.no_subscription_results'] = "Il n'y a pas d'avis d'inscription à disposition de votre groupe de personnel.";
$lang['AdminMyinfo.index.field_language'] = "Langue";
?>