<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyTaxes.!success.basic_updated'] = "Les paramètres de base des taxes ont été mis à jour avec succès!";
$lang['AdminCompanyTaxes.!success.taxrule_created'] = "Le taux a bien été mis à jour!";
$lang['AdminCompanyTaxes.!success.taxrule_updated'] = "La règle des taxes a été ajoutée avec succès!";
$lang['AdminCompanyTaxes.countries.all'] = "-- Tous --";
$lang['AdminCompanyTaxes.states.all'] = "-- Tous --";
$lang['AdminCompanyTaxes.basic.boxtitle_basic'] = "Paramètres de base des taxes";
$lang['AdminCompanyTaxes.basic.field_taxid'] = "TVA taxe";
$lang['AdminCompanyTaxes.basic.field_addsubmit'] = "Mettre à jour les paramètres";
$lang['AdminCompanyTaxes.rules.no_results'] = "Il n'y a pas de règle fiscale de niveau %1\$s."; // %1$s is the tax level number
$lang['AdminCompanyTaxes.rules.categorylink_addrule'] = "Ajouter une règle de taxe";
$lang['AdminCompanyTaxes.rules.boxtitle_rules'] = "Règle de taxes";
$lang['AdminCompanyTaxes.rules.heading_level1'] = "Règles de niveau 1";
$lang['AdminCompanyTaxes.rules.heading_level2'] = "Règles de niveau 2";
$lang['AdminCompanyTaxes.rules.text_name'] = "Nom";
$lang['AdminCompanyTaxes.rules.text_type'] = "Type";
$lang['AdminCompanyTaxes.rules.text_amount'] = "Montant";
$lang['AdminCompanyTaxes.rules.text_country'] = "Pays";
$lang['AdminCompanyTaxes.rules.text_state'] = "État/Province";
$lang['AdminCompanyTaxes.rules.text_options'] = "Options";
$lang['AdminCompanyTaxes.rules.text_all'] = "Tous";
$lang['AdminCompanyTaxes.rules.option_edit'] = "Modifier";
$lang['AdminCompanyTaxes.add.boxtitle_add'] = "Ajouter une règle de taxe";
$lang['AdminCompanyTaxes.add.field_taxtype'] = "Type de taxe";
$lang['AdminCompanyTaxes.add.field_taxlevel'] = "Niveau de taxation";
$lang['AdminCompanyTaxes.add.field_level1'] = "Niveau 1";
$lang['AdminCompanyTaxes.add.field_level2'] = "Niveau 2";
$lang['AdminCompanyTaxes.add.field_name'] = "Nom de la taxe";
$lang['AdminCompanyTaxes.add.field_amount'] = "Montant";
$lang['AdminCompanyTaxes.add.field_country'] = "Pays";
$lang['AdminCompanyTaxes.add.field_state'] = "État/Province";
$lang['AdminCompanyTaxes.add.field_addsubmit'] = "Créer une règle";
$lang['AdminCompanyTaxes.edit.boxtitle_edit'] = "Modifier la règle des taxes";
$lang['AdminCompanyTaxes.edit.field_taxtype'] = "Type de taxe";
$lang['AdminCompanyTaxes.edit.field_taxlevel'] = "Niveau de taxes";
$lang['AdminCompanyTaxes.edit.field_level1'] = "Niveau 1";
$lang['AdminCompanyTaxes.edit.field_level2'] = "Niveau 2";
$lang['AdminCompanyTaxes.edit.field_name'] = "Nom de la taxe";
$lang['AdminCompanyTaxes.edit.field_amount'] = "Montant";
$lang['AdminCompanyTaxes.edit.field_country'] = "Pays";
$lang['AdminCompanyTaxes.edit.field_state'] = "État/Province";
$lang['AdminCompanyTaxes.edit.field_editsubmit'] = "Modifier la règle";
$lang['AdminCompanyTaxes.basic.page_title'] = "Paramètres > Compagnie > Taxes > Paramètres de base des taxes";
$lang['AdminCompanyTaxes.basic.field_enable_tax'] = "Activer les taxes";
$lang['AdminCompanyTaxes.basic.field_cascade_tax'] = "Cascade des taxes";
$lang['AdminCompanyTaxes.basic.field_setup_fee_tax'] = "Taxer les frais d'installation";
$lang['AdminCompanyTaxes.basic.field_cancelation_fee_tax'] = "Taxer les frais d'annulation";
$lang['AdminCompanyTaxes.rules.page_title'] = "Paramètres > Compagnie > Taxes > Règles de taxes";
$lang['AdminCompanyTaxes.add.page_title'] = "Paramètres  > Compagnie > Taxes > Ajout d'une règle de taxe";
$lang['AdminCompanyTaxes.edit.page_title'] = "Paramètres > Compagnie > Taxes > Éditer la règle des taxes";
$lang['AdminCompanyTaxes.basic.note_enable_tax'] = "Cochez cette option pour activer les taxes pour cette compagnie.";
$lang['AdminCompanyTaxes.basic.note_cascade_tax'] = "Si cette option est activée, le niveau de taxe 1 sera d'abord évalué sur le total de la facture, puis le niveau de taxe 2 sur ce nouveau total, y compris le niveau de taxe 1. Il en résulte une taxe sur les taxes. Autrement, le niveau de taxe 1 et le niveau de taxe 2 sont évalués uniquement sur le total de la facture avant taxe.";
$lang['AdminCompanyTaxes.basic.note_setup_fee_tax'] = "Si activé, les frais de mise en service seront taxés.";
$lang['AdminCompanyTaxes.basic.note_cancelation_fee_tax'] = "Si activé, les frais d'annulation seront taxés.";
$lang['AdminCompanyTaxes.!tooltip.note_taxtype'] = "Inclusif fera apparaitre la taxe comme étant partie intégrante du total. Exclusif listera la taxe séparément et ne l'inclura pas dans le total. ";
$lang['AdminCompanyTaxes.!success.rule_deleted'] = "La règle de taxe a été effacée avec succès.";
$lang['AdminCompanyTaxes.rules.option_delete'] = "Effacer";
$lang['AdminCompanyTaxes.rules.confirm_delete'] = "Êtes-vous sur de vouloir effacer cette règle de taxe?";
?>