<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSettings.company.category_company'] = "Compagnie";
$lang['AdminSettings.company.category_system'] = "Système";
$lang['AdminSettings.company.boxtitle_settings'] = "Paramètres";
$lang['AdminSettings.company.heading_general'] = "Général";
$lang['AdminSettings.company.heading_billing'] = "Facturation/Paiement";
$lang['AdminSettings.company.text_billing'] = "Configurer les options de facturation et de personnalisation, les paiements automatiques, avis de paiement, et des coupons.";
$lang['AdminSettings.company.heading_emails'] = "Courriels";
$lang['AdminSettings.company.text_emails'] = "Configurer les paramètres de courriel, modifier des modèles de courriels, et de créer et de gérer les signatures de courriel.";
$lang['AdminSettings.company.heading_currencies'] = "Devises";
$lang['AdminSettings.company.heading_clientgroups'] = "Groupes client";
$lang['AdminSettings.company.text_clientgroups'] = "Tous les clients font partie d'un groupe, qui détermine quand le client est facturé, généré et plus encore. Créer et gérer les groupes de clients et les paramètres.";
$lang['AdminSettings.company.heading_automation'] = "Automatisation";
$lang['AdminSettings.company.text_automation'] = "L'accès et le contrôle des tâches automatisées dans Blesta.";
$lang['AdminSettings.company.heading_modules'] = "Modules";
$lang['AdminSettings.company.text_modules'] = "Installez et gérez les modules, qui sont utilisés pour l'approvisionnement et la gestion des services.";
$lang['AdminSettings.company.heading_gateways'] = "Passerelles de paiement";
$lang['AdminSettings.company.text_gateways'] = "Activer et désactiver les systèmes de paiement marchands et non-marchands pour l'acceptation du paiement.";
$lang['AdminSettings.company.heading_taxes'] = "Taxes";
$lang['AdminSettings.company.text_taxes'] = "Activation ou désactivation d'une taxe, configurer un identifiant de taxe (VATIN), et création d'une simple taxe ou d'une taxe multi-niveaux.";
$lang['AdminSettings.company.heading_plugins'] = "Plugins";
$lang['AdminSettings.company.text_plugins'] = "Installer, désinstaller et gérer les plugins qui ajoutent et personnalisent les fonctionnalités de base de Blesta.";
$lang['AdminSettings.system.category_company'] = "Compagnie";
$lang['AdminSettings.system.category_system'] = "Système";
$lang['AdminSettings.system.boxtitle_settings'] = "Paramètres";
$lang['AdminSettings.system.heading_general'] = "Général";
$lang['AdminSettings.system.text_general'] = "Configurer les paramètres de l'ensemble du système, compris l'activation de mode maintenance , la base de données GeoIP, ou mettre à jour votre clé de licence.";
$lang['AdminSettings.system.heading_companies'] = "Compagnies";
$lang['AdminSettings.system.text_companies'] = "Ajouter ou mettre à jour les compagnies.";
$lang['AdminSettings.system.heading_backup'] = "Sauvegarde";
$lang['AdminSettings.system.heading_api'] = "Accès API";
$lang['AdminSettings.system.text_api'] = "Contrôler l'accès à l'API de cette installation.";
$lang['AdminSettings.system.heading_marketplace'] = "Marché";
$lang['AdminSettings.system.text_marketplace'] = "Naviguer et  télécharger des plugins, modules, des passerelles, et bien plus encore sur le Marché Blesta.";
$lang['AdminSettings.system.heading_automation'] = "Automatisation";
$lang['AdminSettings.system.text_automation'] = "Déterminez votre tâche Cron ou les informations de tâches planifiées.";
$lang['AdminSettings.system.heading_staff'] = "Personnel";
$lang['AdminSettings.system.text_staff'] = "Créer ou modifier les comptes du personnel et les autorisations. Les employés ont accès à la zone d'administration de Blesta.";
$lang['AdminSettings.system.heading_upgrade'] = "Options de mise à niveau";
$lang['AdminSettings.system.text_upgrade'] = "Afficher les informations de mise à jour et téléchargements.";
$lang['AdminSettings.system.heading_help'] = "Aide";
$lang['AdminSettings.system.text_help'] = "Voir l'aide pour votre installation de Blesta.";
$lang['AdminSettings.company.page_title'] = "Paramètres";
$lang['AdminSettings.system.page_title'] = "Paramètres";
$lang['AdminSettings.company.text_currencies'] = "Mettre à jour et ajouter des devises, paramétrer la devise par défaut, configurer les multiples devises, et de configurer des taux de change.";
$lang['AdminSettings.system.text_backup'] = "Configurer des sauvegardes automatiques en utilisant SFTP ou Amazon S3 ou téléchargez une copie sur votre ordinateur local.";
$lang['AdminSettings.company.heading_lookandfeel'] = "Apparence";
$lang['AdminSettings.company.text_lookandfeel'] = "Personnaliser l'apparence de Blesta en gérant les thèmes de couleur ou en mettant à jour le modèle d’interface client.";
$lang['AdminSettings.company.text_general'] = "Configurer la localisation, les options d'internationalisation, et les types de contact client.";
$lang['AdminSettings.company.heading_clientoptions'] = "Options client";
$lang['AdminSettings.company.text_clientoptions'] = "Créer et gérer des champs personnalisés pour les clients et sélectionner les champs obligatoires pour les clients.";
?>