<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSearch.!notice.results_truncated'] = "Le nombre de résultats ont été tronqués. Vous pourriez préciser votre recherche.";
$lang['AdminSearch.index.page_title'] = "Résultats de recherche pour \"%1\$s\""; // %1$s is the criteria being searched for
$lang['AdminSearch.index.boxtitle_search'] = "Résultats de recherche pour \"%1\$s\""; // %1$s is the criteria being searched for
$lang['AdminSearch.clients.heading'] = "Clients";
$lang['AdminSearch.clients.heading_client_id'] = "ID client";
$lang['AdminSearch.clients.heading_group'] = "Groupe";
$lang['AdminSearch.clients.heading_name'] = "Nom";
$lang['AdminSearch.clients.heading_company'] = "Compagnie";
$lang['AdminSearch.clients.heading_address'] = "Adresse";
$lang['AdminSearch.clients.heading_email'] = "Couriel";
$lang['AdminSearch.clients.no_results'] = "Il n'y a pas de clients qui correspondent aux critères de recherche.";
$lang['AdminSearch.invoices.heading'] = "Factures";
$lang['AdminSearch.invoice.heading_invoice'] = "Facture #";
$lang['AdminSearch.invoice.heading_client_id'] = "ID client";
$lang['AdminSearch.invoice.heading_amount'] = "Options";
$lang['AdminSearch.invoice.heading_paid'] = "Payé";
$lang['AdminSearch.invoice.heading_due'] = "Du";
$lang['AdminSearch.invoice.heading_date_closed'] = "Date de fermeture";
$lang['AdminSearch.invoice.heading_date_billed'] = "Date facturé";
$lang['AdminSearch.invoice.heading_date_due'] = "Date due";
$lang['AdminSearch.invoice.heading_sent'] = "Envoyé";
$lang['AdminSearch.invoice.heading_status'] = "Statut";
$lang['AdminSearch.invoice.option_view'] = "Voir";
$lang['AdminSearch.invoices.status_open'] = "Ouvert";
$lang['AdminSearch.invoices.status_closed'] = "Fermé";
$lang['AdminSearch.invoices.status_void'] = "Annulé";
$lang['AdminSearch.invoices.status_draft'] = "Brouillon";
$lang['AdminSearch.invoices.status_sent'] = "Envoyé";
$lang['AdminSearch.invoices.status_unsent'] = "Non envoyé";
$lang['AdminSearch.invoice.no_results'] = "Il n'y a pas de facture qui correspond aux critères de recherche. ";
$lang['AdminSearch.transactions.heading'] = "Transactions";
$lang['AdminSearch.transactions.heading_client_id'] = "ID client";
$lang['AdminSearch.transactions.heading_type'] = "Type";
$lang['AdminSearch.transactions.heading_amount'] = "Montant";
$lang['AdminSearch.transactions.heading_credited'] = "Crédité";
$lang['AdminSearch.transactions.heading_applied'] = "Appliqué";
$lang['AdminSearch.transactions.heading_number'] = "Numéro";
$lang['AdminSearch.transactions.heading_status'] = "Statut";
$lang['AdminSearch.transactions.heading_date'] = "Date";
$lang['AdminSearch.transactions.heading_options'] = "Options";
$lang['AdminSearch.transactions.option_edit'] = "Modifier";
$lang['AdminSearch.transactions.no_results'] = "Il n'y a pas de transactions qui répondent aux critères de recherche.";
$lang['AdminSearch.packages.heading'] = "Ensembles";
$lang['AdminSearch.packages.heading_package_id'] = "ID d'ensemble";
$lang['AdminSearch.packages.heading_name'] = "Nom";
$lang['AdminSearch.packages.heading_module'] = "Module";
$lang['AdminSearch.packages.heading_quantity'] = "Quantité";
$lang['AdminSearch.packages.heading_status'] = "Statut";
$lang['AdminSearch.packages.no_results'] = "Il n'y a pas d'ensemble qui correspondent aux critères de recherche.";
$lang['AdminSearch.services.heading'] = "Services";
$lang['AdminSearch.services.heading_client_id'] = "ID client";
$lang['AdminSearch.services.heading_package'] = "Ensemble";
$lang['AdminSearch.services.heading_term'] = "Termes";
$lang['AdminSearch.services.heading_date_added'] = "Date de création";
$lang['AdminSearch.services.heading_date_renews'] = "Date de renouvellement";
$lang['AdminSearch.services.heading_status'] = "Statut";
$lang['AdminSearch.services.text_never'] = "Jamais";
$lang['AdminSearch.services.no_results'] = "Il n'y a pas de services qui répondent aux critères de recherche.";
$lang['AdminSearch.services.heading_client'] = "Client";
?>