<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemStaff.!success.staff_added'] = "Ce membre du personnel a été ajouté avec succès!";
$lang['AdminSystemStaff.!success.staff_updated'] = "Ce membre du personnel a été mis à jour avec succès!";
$lang['AdminSystemStaff.!success.group_added'] = "Le groupe d'employés, \"%1\$s\", a été créé avec succès!"; // %1$s is the name of the staff group
$lang['AdminSystemStaff.!success.group_updated'] = "Le groupe d'employés \"%1\$s\" a été mis à jour avec succès!"; // %1$s is the name of the staff group
$lang['AdminSystemStaff.!success.group_deleted'] = "Le groupe de membres du personnel, \"%1\$s\", a été effacé avec succès!"; // %1$s is the name of the staff group
$lang['AdminSystemStaff.manage.boxtitle_manage'] = "Gérer l'équipe";
$lang['AdminSystemStaff.manage.category_active'] = "Actif";
$lang['AdminSystemStaff.manage.category_inactive'] = "Inactif";
$lang['AdminSystemStaff.manage.categorylink_addstaff'] = "Ajouter du personnel";
$lang['AdminSystemStaff.manage.heading_name'] = "Nom";
$lang['AdminSystemStaff.manage.heading_email'] = "Courriel";
$lang['AdminSystemStaff.manage.heading_options'] = "Options";
$lang['AdminSystemStaff.manage.no_results'] = "Il n'y a pas de membre du personnel avec ce statut.";
$lang['AdminSystemStaff.manage.confirm_deactivate'] = "Vraiment désactiver ce employé?";
$lang['AdminSystemStaff.manage.confirm_reactivate'] = "Vous souhaitez vraiment réactiver ce membre du personnel?";
$lang['AdminSystemStaff.manage.option_edit'] = "Modifier";
$lang['AdminSystemStaff.manage.option_deactivate'] = "Désactiver";
$lang['AdminSystemStaff.manage.option_reactivate'] = "Réactiver";
$lang['AdminSystemStaff.groups.option_delete'] = "Effacer";
$lang['AdminSystemStaff.add.boxtitle_addstaff'] = "Ajouter un membre du personnel";
$lang['AdminSystemStaff.add.heading_contact'] = "Informations de contact";
$lang['AdminSystemStaff.add.heading_authentication'] = "Authentification";
$lang['AdminSystemStaff.add.heading_groups'] = "Groupes";
$lang['AdminSystemStaff.add.field_firstname'] = "Prénom";
$lang['AdminSystemStaff.add.field_lastname'] = "nom de famille";
$lang['AdminSystemStaff.add.field_email'] = "Courriel";
$lang['AdminSystemStaff.add.field_username'] = "Nom d'utilisateur";
$lang['AdminSystemStaff.add.field_username_username'] = "Entrez un nom d'utilisateur";
$lang['AdminSystemStaff.add.field_username_email'] = "Utiliser l'adresse courriel comme nom d'utilisateur";
$lang['AdminSystemStaff.add.field_password'] = "Mot de passe";
$lang['AdminSystemStaff.add.field_confirmpass'] = "Confirmer le mot de passe";
$lang['AdminSystemStaff.add.field_twofactormode'] = "Deux facteurs d'authentification";
$lang['AdminSystemStaff.add.field_twofactorkey'] = "Clé à deux facteurs";
$lang['AdminSystemStaff.add.field_twofactorpin'] = "NIP à deux facteurs";
$lang['AdminSystemStaff.add.text_membergroups'] = "Groupes de Membres";
$lang['AdminSystemStaff.add.text_availablegroups'] = "Groupes disponibles";
$lang['AdminSystemStaff.edit.boxtitle_editstaff'] = "Modifier l'employée
";
$lang['AdminSystemStaff.edit.heading_contact'] = "Information de contact";
$lang['AdminSystemStaff.edit.heading_authentication'] = "Authentification";
$lang['AdminSystemStaff.edit.heading_groups'] = "Groupes";
$lang['AdminSystemStaff.edit.field_firstname'] = "Prénom";
$lang['AdminSystemStaff.edit.field_lastname'] = "Nom de famille";
$lang['AdminSystemStaff.edit.field_username'] = "Nom d'utilisateur";
$lang['AdminSystemStaff.edit.field_email'] = "Courriel";
$lang['AdminSystemStaff.edit.field_password'] = "Nouveau mot de passe";
$lang['AdminSystemStaff.edit.field_confirmpass'] = "Confirmer le mot de passe";
$lang['AdminSystemStaff.edit.field_twofactormode'] = "Authentification à deux facteurs";
$lang['AdminSystemStaff.edit.field_twofactorkey'] = "Clé à 2 facteurs";
$lang['AdminSystemStaff.edit.field_twofactorpin'] = "NIP à deux facteurs";
$lang['AdminSystemStaff.edit.text_membergroups'] = "Groupes de membres";
$lang['AdminSystemStaff.edit.text_availablegroups'] = "Groupes disponibles";
$lang['AdminSystemStaff.groups.boxtitle_groups'] = "Groupes du personnel";
$lang['AdminSystemStaff.groups.categorylink_addgroup'] = "Créer groupe";
$lang['AdminSystemStaff.groups.heading_name'] = "Nom";
$lang['AdminSystemStaff.groups.heading_company_name'] = "Nom de compagnie";
$lang['AdminSystemStaff.groups.heading_staff'] = "Quantité de membre du personnel";
$lang['AdminSystemStaff.groups.heading_options'] = "Options";
$lang['AdminSystemStaff.groups.no_results'] = "Il n'y a pas de groupes de membre du personnel.";
$lang['AdminSystemStaff.groups.option_edit'] = "Modifier";
$lang['AdminSystemStaff.groups.modal_delete'] = "Êtes-vous sur de vouloir effacer ce groupe de membre du personnel?";
$lang['AdminSystemStaff.addgroup.boxtitle_addgroup'] = "Créer le groupe";
$lang['AdminSystemStaff.addgroup.field_name'] = "Nom";
$lang['AdminSystemStaff.addgroup.field_company'] = "Compagnie";
$lang['AdminSystemStaff.addgroup.field_groupsubmit'] = "Créer un groupe";
$lang['AdminSystemStaff.addgroup.heading_general'] = "Général";
$lang['AdminSystemStaff.addgroup.heading_permissions'] = "Liste de contrôle d'accès";
$lang['AdminSystemStaff.editgroup.boxtitle_editgroup'] = "Modifier le groupe";
$lang['AdminSystemStaff.editgroup.field_name'] = "Nom";
$lang['AdminSystemStaff.editgroup.field_company'] = "Compagnie";
$lang['AdminSystemStaff.editgroup.field_groupsubmit'] = "Modifier le groupe";
$lang['AdminSystemStaff.editgroup.heading_general'] = "Général";
$lang['AdminSystemStaff.editgroup.heading_permissions'] = "Liste de contrôle d'accès";
$lang['AdminSystemStaff.editgroup.dialog_confirm_edit_assigned'] = "Vous êtes présentement assigné à ce groupe de membre du personnel. Tout changement que vous effectuerez prendra effet immédiatement et vous pourriez ne plus être en mesure d'accéder cette section. Êtes-vous sûr de vouloir effectuer ces changements?";
$lang['AdminSystemStaff.manage.page_title'] = "Paramètres> Système> Personnel> Gérer Personnel";
$lang['AdminSystemStaff.add.page_title'] = "Paramètres > Système > Personne > Ajouter un membre du personnel";
$lang['AdminSystemStaff.edit.page_title'] = "Paramètres > Système > Personnel > Modifier le personnel";
$lang['AdminSystemStaff.groups.page_title'] = "Paramètres > Système > Personnel > Groupe de membres du personnel";
$lang['AdminSystemStaff.!groups.text_separator'] = "/";
$lang['AdminSystemStaff.!groups.text_group_start'] = "(";
$lang['AdminSystemStaff.!groups.text_group_end'] = ")";
$lang['AdminSystemStaff.addgroup.page_title'] = "Paramètres > Système > Personne > Créer groupe";
$lang['AdminSystemStaff.addgroup.heading_email_notices'] = "Envoyer les courriels BCC d'avis";
$lang['AdminSystemStaff.addgroup.text_check_all'] = "Tout sélectionner";
$lang['AdminSystemStaff.addgroup.text_uncheck_all'] = "Tout désélectionner ";
$lang['AdminSystemStaff.editgroup.page_title'] = "Paramètres > Système > Personnel > Modifier un groupe";
$lang['AdminSystemStaff.editgroup.heading_email_notices'] = "Avis par e-mail BCC";
$lang['AdminSystemStaff.add.field_addsubmit'] = "Créer personnel";
$lang['AdminSystemStaff.edit.field_editsubmit'] = "Modifier le personnel";
$lang['AdminSystemStaff.addgroup.heading_subscription_email_notices'] = "Avis d'abonnement aux courriels";
$lang['AdminSystemStaff.editgroup.heading_subscription_email_notices'] = "Avis d'abonnements courriel";
$lang['AdminSystemStaff.addgroup.field_session_lock'] = "Déconnexion sur changement d'adresse IP";
$lang['AdminSystemStaff.editgroup.field_session_lock'] = "Déconnexion lors d'un changement d'adresse IP";
?>