<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminDialog.confirm.text_yes'] = "Oui";
$lang['AdminDialog.confirm.text_no'] = "Non";
$lang['AdminDialog.password.field_modal_password'] = "Mot de passe";
$lang['AdminDialog.password.field_modal_password_copied'] = "J'ai copié ce mot de passe à un endroit sûr";
$lang['AdminDialog.password.btn_generate'] = "Générer";
$lang['AdminDialog.password.btn_modal_password'] = "Mot de passe";
$lang['AdminDialog.password.btn_cancel'] = "Annuler";
$lang['AdminDialog.password.btn_use_password'] = "Utiliser un mot de passe";
?>