<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyPlugins.!success.uninstalled'] = "Le plugin a été désinstallé avec succès.";
$lang['AdminCompanyPlugins.!success.upgraded'] = "Le plugin a été mis à jour avec succès.";
$lang['AdminCompanyPlugins.!error.setting_controller_invalid'] = "Le contrôleur de paramètres spécifié n'existe pas pour ce plugin.";
$lang['AdminCompanyPlugins.available.text_author'] = "Auteur:";
$lang['AdminCompanyPlugins.available.btn_install'] = "Installer";
$lang['AdminCompanyPlugins.available.text_none'] = "Il n'y a pas de plugin disponible.";
$lang['AdminCompanyPlugins.installed.text_author'] = "Auteur:";
$lang['AdminCompanyPlugins.installed.confirm_uninstall'] = "Voulez-vous vraiment désinstaller ce plugin?";
$lang['AdminCompanyPlugins.installed.btn_uninstall'] = "Désinstaller";
$lang['AdminCompanyPlugins.installed.btn_manage'] = "Gérer";
$lang['AdminCompanyPlugins.installed.btn_upgrade'] = "Mettre à jour";
$lang['AdminCompanyPlugins.installed.text_none'] = "Il n'y a aucun plugin d'installé";
$lang['AdminCompanyPlugins.available.page_title'] = "Paramètres > Compagnie > Plugins > Disponible";
$lang['AdminCompanyPlugins.installed.page_title'] = "Paramètres > Compagnie > Plugins > Installés";
$lang['AdminCompanyPlugins.available.text_version'] = "(ver %1\$s)"; // %1$s is the version number of the plugin
$lang['AdminCompanyPlugins.installed.text_version'] = "(ver %1\$s)"; // %1$s is the version number of the plugin
$lang['AdminCompanyPlugins.!success.installed'] = "Le plugin a été installé avec succès. Il peut avoir enregistré des autorisations ACL pour diverses ressources. Vous devrez peut-être accorder à votre groupe d'employés l'accès à ces autorisations pour pouvoir accéder à ces ressources.";
$lang['AdminCompanyPlugins.!success.enabled'] = "Le plugin a été activé avec succès.";
$lang['AdminCompanyPlugins.!success.disabled'] = "Le plugin a été désactivé avec succès.";
$lang['AdminCompanyPlugins.installed.confirm_disable'] = "Vous souhaitez vraiment désactiver ce plugin?";
$lang['AdminCompanyPlugins.installed.confirm_enable'] = "Vous voulez vraiment activer ce plugin?";
$lang['AdminCompanyPlugins.installed.btn_disable'] = "Désactiver";
$lang['AdminCompanyPlugins.installed.btn_enable'] = "Permettre";
$lang['AdminCompanyPlugins.!tab.installed'] = "Installé";
$lang['AdminCompanyPlugins.!tab.available'] = "Disponible";
$lang['AdminCompanyPlugins.available.boxtitle_plugins'] = "Plugins";
$lang['AdminCompanyPlugins.installed.boxtitle_plugin'] = "Plugins";
?>