<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ApiKeys.!error.key.generate'] = "Échec de génération de la clé.";
$lang['ApiKeys.!error.company_id.exists'] = "La compagnie donnée n'existe pas";
$lang['ApiKeys.!error.user.valid'] = "L'utilisateur API ou la clé semblent invalides. ";
$lang['ApiKeys.!error.user.unique'] = "L'utilisateur de l'API existe déjà pour l'entreprise donnée.";
$lang['ApiKeys.!error.user.format'] = "S'il vous plait entrez un nom d'utilisateur API entre 3 et 64 caractères";
?>