<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AppController.lang.dir'] = "ltr";
$lang['AppController.!error.unauthorized_access'] = "Vous n'êtes pas autorisés à accéder cette ressource";
$lang['AppController.modal.text_close'] = "Fermer";
$lang['AppController.tooltip.text'] = "?";
$lang['AppController.structure.text_myinfo'] = "Mes Infos";
$lang['AppController.structure.text_settings'] = "Paramètres";
$lang['AppController.structure.text_logout'] = "Quitter";
$lang['AppController.!error.invalid_csrf'] = "Le jeton de formulaire est invalide.";
$lang['AppController.message.close'] = "x";
$lang['AppController.structure.text_maintenance'] = "Le mode de maintenance est actuellement activé et les clients ne peuvent pas se connecter. Cliquez ici pour changer.";
$lang['AppController.structure.text_search_placeholder'] = "%1\$s..."; // %1$s is the search type
$lang['AppController.client_structure.default_title'] = "Mon compte";
$lang['AppController.client_structure.text_return_to_portal'] = "Retourner au portail";
$lang['AppController.client_structure.text_logout'] = "Déconnexion";
$lang['AppController.dates.day_sun'] = "Dimanche";
$lang['AppController.dates.day_mon'] = "Lundi";
$lang['AppController.dates.day_tue'] = "Mardi";
$lang['AppController.dates.day_wed'] = "Mercredi";
$lang['AppController.dates.day_thu'] = "Jeudi";
$lang['AppController.dates.day_fri'] = "Vendredi";
$lang['AppController.dates.day_sat'] = "Samedi";
$lang['AppController.dates.dayabbr_sun'] = "Dim";
$lang['AppController.dates.dayabbr_mon'] = "Lun";
$lang['AppController.dates.dayabbr_tue'] = "Mar";
$lang['AppController.dates.dayabbr_wed'] = "Mer";
$lang['AppController.dates.dayabbr_thur'] = "Jeu";
$lang['AppController.dates.dayabbr_fri'] = "Ven";
$lang['AppController.dates.dayabbr_sat'] = "Dim";
$lang['AppController.dates.month_jan'] = "Janvier";
$lang['AppController.dates.month_feb'] = "Février";
$lang['AppController.dates.month_mar'] = "Mars";
$lang['AppController.dates.month_apr'] = "Avril";
$lang['AppController.dates.month_may'] = "Mai";
$lang['AppController.dates.month_jun'] = "Juin";
$lang['AppController.dates.month_jul'] = "Juillet";
$lang['AppController.dates.month_aug'] = "Aout";
$lang['AppController.dates.month_sep'] = "Septembre";
$lang['AppController.dates.month_oct'] = "Octobre";
$lang['AppController.dates.month_nov'] = "Novembre";
$lang['AppController.dates.month_dec'] = "Décembre";
$lang['AppController.dates.monthabbr_jan'] = "Jan";
$lang['AppController.dates.monthabbr_feb'] = "Fev";
$lang['AppController.dates.monthabbr_mar'] = "Mar";
$lang['AppController.dates.monthabbr_apr'] = "Avr";
$lang['AppController.dates.monthabbr_may'] = "Mai";
$lang['AppController.dates.monthabbr_jun'] = "Juin";
$lang['AppController.dates.monthabbr_jul'] = "Juil";
$lang['AppController.dates.monthabbr_aug'] = "Aou";
$lang['AppController.dates.monthabbr_sep'] = "Sep";
$lang['AppController.dates.monthabbr_oct'] = "Oct";
$lang['AppController.dates.monthabbr_nov'] = "Nov";
$lang['AppController.dates.monthabbr_dec'] = "Dec";
$lang['AppController.!success.license_updated'] = "Votre licence a été revalidée avec succès. Veuillez vous identifier.";
$lang['AppController.!success.license_key_updated'] = "Votre clé de licence a été mis à jour avec succès. S'il vous plaît vous connecter";
$lang['AppController.select.please'] = "-- Veuillez choisir --";
$lang['AppController.modal.text_confirm'] = "Veuillez confirmer";
$lang['AppController.client_structure.text_update_account'] = "Gérer le compte";
$lang['AppController.sreader.dropdown'] = "la liste déroulante inversé";
$lang['AppController.sreader.navigation'] = "Basculer la navigation";
$lang['AppController.client_structure.staff_as_client_note'] = "Retour au portail employé";
$lang['AppController.client_structure.text_login'] = "Connection";
$lang['AppController.graphs.control_label.stacked'] = "Empilé";
$lang['AppController.graphs.control_label.stream'] = "Flux";
$lang['AppController.graphs.control_label.expanded'] = "Étendu";
$lang['AppController.graphs.control_label.grouped'] = "Groupé";
$lang['AppController.graphs.label.total'] = "Total";
?>