<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Backup.!error.driver.support'] = "Le pilote de la base de données n'est pas supporté.";
$lang['Backup.!error.temp_dir.writable'] = "Impossible d'écrire dans le répertoire temp";
$lang['Backup.frequencies.hour'] = "Heure";
$lang['Backup.frequencies.hours'] = "%1\$s heures"; // %1$s is the number of hours
$lang['Backup.frequencies.day'] = "Jour";
$lang['Backup.frequencies.days'] = "%1\$s jours"; // %1$s is the number of days
$lang['Backup.!error.amazons3_failed'] = "La sauvegarde via AmazonS3 a échoué.";
$lang['Backup.frequencies.never'] = "Jamais";
$lang['Backup.!error.ftp_failed'] = "La sauvegarde SFTP a échoué.";
?>