<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientGroups.!error.name.empty'] = "Veuillez spécifier un nom de groupe.";
$lang['ClientGroups.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['ClientGroups.!error.color.length'] = "La longueur de la couleur ne peut excéder 16 caractères.";
$lang['ClientGroups.!error.group_id.exists'] = "ID de groupe de clients invalide.";
?>