<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientInvoices.index.page_title'] = "Factures du Client # %1\$s"; // %1$s is the client ID number
$lang['ClientInvoices.index.category_open'] = "Ouvert";
$lang['ClientInvoices.index.category_closed'] = "Fermé";
$lang['ClientInvoices.index.categorylink_make_payment'] = "Faire un paiement";
$lang['ClientInvoices.index.boxtitle_invoices'] = "Factures";
$lang['ClientInvoices.index.heading_invoice'] = "Facture #";
$lang['ClientInvoices.index.heading_amount'] = "Montant";
$lang['ClientInvoices.index.heading_paid'] = "Payé";
$lang['ClientInvoices.index.heading_due'] = "Dû";
$lang['ClientInvoices.index.heading_dateclosed'] = "Date fermé";
$lang['ClientInvoices.index.heading_datebilled'] = "Date facturé";
$lang['ClientInvoices.index.heading_datedue'] = "Date d'échéance";
$lang['ClientInvoices.index.heading_options'] = "Options";
$lang['ClientInvoices.index.option_view'] = "Voir";
$lang['ClientInvoices.index.option_pay'] = "Payer";
$lang['ClientInvoices.index.no_results'] = "Vous n'avez pas de factures %1\$s."; // %1$s is the language for the invoice category type (e.g. Open, Closed)
$lang['ClientInvoices.applied.heading_paymenttype'] = "Type de paiement";
$lang['ClientInvoices.applied.heading_amount'] = "Montant";
$lang['ClientInvoices.applied.heading_applied'] = "Appliqué";
$lang['ClientInvoices.applied.heading_appliedon'] = "Appliqué le";
$lang['ClientInvoices.applied.no_results'] = "Cette facture ne comporte pas de transactions.";
?>