<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientContacts.!success.contact_deleted'] = "Le contact %1\$s %2\$s a été effacé avec succès!"; // %1$s is the contact's first name, %2$s is the contact's last name
$lang['ClientContacts.!success.contact_updated'] = "Le contact a été mis à jour avec succès!";
$lang['ClientContacts.!success.contact_added'] = "Le contact est créé avec succès!";
$lang['ClientContacts.index.page_title'] = "Client #%1\$s Contacts"; // %1$s is the client ID number
$lang['ClientContacts.index.create_contact'] = "Ajouter un contact";
$lang['ClientContacts.index.boxtitle_contacts'] = "Contacts";
$lang['ClientContacts.index.heading_name'] = "Nom";
$lang['ClientContacts.index.heading_email'] = "Courriel";
$lang['ClientContacts.index.heading_type'] = "Type";
$lang['ClientContacts.index.heading_options'] = "Options";
$lang['ClientContacts.index.option_edit'] = "Gérer";
$lang['ClientContacts.index.option_delete'] = "Effacer";
$lang['ClientContacts.index.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer ce contact?";
$lang['ClientContacts.add.page_title'] = "Client #%1\$s Ajouter contact"; // %1$s is the client ID number
$lang['ClientContacts.add.boxtitle_create'] = "Ajouter un contact";
$lang['ClientContacts.add.heading_settings'] = "Paramètres additionnels";
$lang['ClientContacts.add.field_contact_type'] = "Type de contact";
$lang['ClientContacts.add.field_addsubmit'] = "Créer contact";
$lang['ClientContacts.edit.page_title'] = "Client #%1\$s Modifier contact"; // %1$s is the client ID number
$lang['ClientContacts.edit.boxtitle_edit'] = "Modifier le contact";
$lang['ClientContacts.edit.heading_settings'] = "Paramètres additionnels. ";
$lang['ClientContacts.edit.field_contact_type'] = "Type de contact";
$lang['ClientContacts.edit.field_editsubmit'] = "Mettre à jour le contact";
$lang['ClientContacts.setcontactview.text_none'] = "Aucun";
$lang['ClientContacts.contact_info.heading_contact'] = "Information de contact";
$lang['ClientContacts.contact_info.field_contact_id'] = "Copier les informations de contact de";
$lang['ClientContacts.contact_info.field_first_name'] = "Prénom";
$lang['ClientContacts.contact_info.field_last_name'] = "Nom de famille";
$lang['ClientContacts.contact_info.field_company'] = "Compagnie";
$lang['ClientContacts.contact_info.field_address1'] = "Adresse 1";
$lang['ClientContacts.contact_info.field_address2'] = "Adresse 2";
$lang['ClientContacts.contact_info.field_city'] = "Ville";
$lang['ClientContacts.contact_info.field_country'] = "Pays";
$lang['ClientContacts.contact_info.field_state'] = "État";
$lang['ClientContacts.contact_info.field_zip'] = "ZIP/Code postal";
$lang['ClientContacts.contact_info.field_email'] = "Courriel";
$lang['ClientContacts.phone_numbers.heading_phone'] = "Numéros de téléphone";
$lang['ClientContacts.phone_numbers.field_phonetype'] = "Type";
$lang['ClientContacts.phone_numbers.field_phonelocation'] = "Endroit";
$lang['ClientContacts.phone_numbers.field_phonenumber'] = "Nombre";
$lang['ClientContacts.phone_numbers.text_remove'] = "Enlever";
$lang['ClientContacts.index.no_results'] = "Vous n'avez pas de contacts. Pour ajouter votre premier contact, cliquez sur le bouton \"Ajouter un contact\"";
$lang['ClientContacts.!info.no_contacts'] = "Vous n'avez aucun contact, veuillez ajouter votre premier ci dessous.";
$lang['ClientContacts.contact_info.text_select_contact'] = "Vous pouvez sélectionner un contact existant pour pré-remplir ce formulaire.";
$lang['ClientContacts.phone_numbers.field_phoneoptions'] = "Options";
$lang['ClientContacts.phone_numbers.categorylink_number'] = "Ajouter";
$lang['ClientContacts.add.heading_contact'] = "Information de contact";
$lang['ClientContacts.add.heading_authentication'] = "Authentification";
$lang['ClientContacts.add.field_enable_login'] = "Permettre la connexion";
$lang['ClientContacts.add.field_username'] = "Nom d'utilisateur";
$lang['ClientContacts.add.field_new_password'] = "Nouveau mot de passe";
$lang['ClientContacts.add.field_confirm_password'] = "Confirmer le mot de passe";
$lang['ClientContacts.add.heading_permissions'] = "Permissions";
$lang['ClientContacts.edit.heading_contact'] = "Informations de contact";
$lang['ClientContacts.edit.heading_authentication'] = "Authentification";
$lang['ClientContacts.edit.field_enable_login'] = "Permettre la connexion";
$lang['ClientContacts.edit.field_username'] = "Nom d'utilisateur";
$lang['ClientContacts.edit.field_new_password'] = "Nouveau mot de passe";
$lang['ClientContacts.edit.field_confirm_password'] = "Confirmer le mot de passe";
$lang['ClientContacts.edit.heading_permissions'] = "Permissions";
$lang['ClientContacts.tooltip.client_invoices'] = "Affiche les factures sur le tableau de bord, ainsi que les alertes d'avis de paiement.";
$lang['ClientContacts.tooltip.client_services'] = "Afficher les services au tableau de bord, et permettre leur gestion.";
$lang['ClientContacts.tooltip.client_transactions'] = "Afficher les transactions au tableau de bord.";
$lang['ClientContacts.tooltip.client_contacts'] = "Permettre la gestion des contacts.";
$lang['ClientContacts.tooltip.client_accounts'] = "Permettre la gestion des comptes de paiement.";
$lang['ClientContacts.tooltip._invoice_delivery'] = "Permettre la modification et la visualisation du mode de livraison de la facture.";
$lang['ClientContacts.tooltip._credits'] = "Permettre au crédits du compte d'être visualisés.";
$lang['ClientContacts.contact_info.field_title'] = "Titre";
?>