<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Companies.!error.company_id.in_use'] = "Cette compagnie est présentement en utilisation et ne peut être effacé.";
$lang['Companies.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['Companies.!error.name.empty'] = "Veuillez entrer un nom.";
$lang['Companies.!error.name.length'] = "La longueur du nom ne doit pas dépasser 64 caractères.";
$lang['Companies.!error.hostname.unique'] = "Ce nom d'hôte a déjà été pris par une autre société.";
$lang['Companies.!error.phone.length'] = "La longueur du numéro de téléphone ne doit pas dépasser 64 chiffres.";
$lang['Companies.!error.fax.length'] = "La longueur du numéro de fax ne peut excéder 64 caractères.";
$lang['Companies.!error.private_key_passphrase.valid'] = "La phrase secrète entrée est invalide.";
$lang['Companies.!error.inv_format.format'] = "Le format de facture ne peut pas entrer en conflit avec le format de facture brouillon.";
$lang['Companies.!error.inv_format.contains'] = "Le format de facture doit contenir {num}.";
$lang['Companies.!error.inv_draft_format.format'] = "Le format de facture brouillon ne peut entrer en conflit avec le format de facture.";
$lang['Companies.!error.inv_draft_format.contains'] = "Le format de facture brouillon doit contenir {num}.";
$lang['Companies.!error.inv_start.number'] = "La valeur de départ pour la facturation doit être un nombre.";
$lang['Companies.!error.inv_increment.number'] = "La valeur de l'incrémentation des factures doit être un nombre.";
$lang['Companies.!error.inv_pad_size.number'] = "La taille d'espacement de la facture doit être un nombre.";
$lang['Companies.!error.inv_pad_str.length'] = "Le caractère d'espacement de la facture doit être un seul caractère.";
$lang['Companies.!error.hostname.valid'] = "Veuillez entrer un nom d'hôte valide.";
$lang['Companies.!error.hostname.length'] = "Le nom d'hôte ne peut pas dépasser 255 caractères.";
$lang['Companies.!error.quota.allowed'] = "Il n'y a pas de licences d'entreprises additionnelle disponible. Veuillez vous connecter à votre compte à account.blesta.com ou contacter les ventes afin d'acheter des licences supplémentaires d'entreprise.";
$lang['Companies.!error.inv_proforma_format.format'] = "Le format de facture pro forma ne peut entrer en conflit avec le format de brouillon de facture.";
$lang['Companies.!error.inv_proforma_format.contains'] = "La facture pro forma doit comprendre {num}.";
$lang['Companies.!error.inv_proforma_start.number'] = "La valeur de départ de la facture Pro Forma doit être un nombre.";
?>