<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Countries.!error.alpha2.format'] = "Le code de pays Alpha2 doit être 2 lettres.";
$lang['Countries.!error.alpha2.in_use'] = "Le code de pays Alpha2, %1\$s, est déjà utilisé."; // %1$s is the alpha2 country code
$lang['Countries.!error.alpha2.exists'] = "Code alpha2 invalide.";
$lang['Countries.!error.alpha3.format'] = "Le code de pays Alpha3 doit être de 3 caractères.";
$lang['Countries.!error.alpha3.in_use'] = "Le code de pays Alpha3 %1\$s, est déjà pris."; // %1$s is the alpha3 country code
$lang['Countries.!error.name.format'] = "Veuillez entrer un nom.";
?>