<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Coupons.getAmountTypes.amount'] = "Montant";
$lang['Coupons.getAmountTypes.percent'] = "Pourcent ";
$lang['Coupons.!error.code.empty'] = "Veuillez entrer un code de coupon.";
$lang['Coupons.!error.code.length'] = "La longueur du code de coupon ne doit pas dépasser 64 caractères.";
$lang['Coupons.!error.package_group_id.length'] = "L'ID du groupe de packages ne doit pas dépasser 10 caractères.";
$lang['Coupons.!error.used_qty.format'] = "La quantité utilisée doit être un nombre.";
$lang['Coupons.!error.used_qty.length'] = "La longueur de la quantité utilisée ne doit pas dépasser 10 caractères.";
$lang['Coupons.!error.max_qty.format'] = "La quantité maximale doit être un nombre.";
$lang['Coupons.!error.max_qty.length'] = "La longueur de la quantité maximale ne peut excéder 10 caractères.";
$lang['Coupons.!error.start_date.format'] = "Format de date de démarrage invalide.";
$lang['Coupons.!error.end_date.format'] = "Format de date de fin invalide.";
$lang['Coupons.!error.status.format'] = "Statut invalide.";
$lang['Coupons.!error.recurring.format'] = "La récurrence doit être un nombre.";
$lang['Coupons.!error.recurring.length'] = "La récurrence ne doit pas dépasser 1 caractère.";
$lang['Coupons.!error.coupon_id.exists'] = "ID de coupon invalide";
$lang['Coupons.!error.packages[].exists'] = "Au moins un des ensembles auquel vous assignez ce coupon est invalide. ";
$lang['Coupons.!error.amounts.exists'] = "Une seule devise de chaque type peut être appliqué comme un rabais à ce coupon.";
$lang['Coupons.!error.amounts[][currency].length'] = "Le code de devise doit avoir 3 caractères.";
$lang['Coupons.!error.amounts[][amount].format'] = "Chaque valeur de rabais doit être un nombre.";
$lang['Coupons.!error.amounts[][type].format'] = "Type de montant invalide.";
$lang['Coupons.!error.company_id.exists'] = "ID de compagnie fourni invalide.";
$lang['Coupons.!error.max_qty.exceeded'] = "La quantité utilisée ne doit pas excéder la quantité maximale.";
$lang['Coupons.!error.limit_recurring.format'] = "La limite de récurrence doit être un nombre.";
$lang['Coupons.!error.limit_recurring.length'] = "La limite de la longueur de la récurrence ne doit pas dépasser 1 caractère.";
$lang['Coupons.!error.apply_package_options.format'] = "Si le coupon s'applique aux options configurables, il doit être réglé sur 1 ou 0.";
$lang['Coupons.!error.code.unique'] = "Le code de coupon est actuellement défini sur un autre coupon et ne peut pas être réutilisé.";
$lang['Coupons.!error.internal_use_only.format'] = "Pour que le coupon soit destiné à un usage interne uniquement, il doit être réglé sur 1 ou 0.";
?>