<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cron.index.attempt_all'] = "Tentative d'exécution des tâches pour %1\$s."; // %1$s is the company name
$lang['Cron.index.completed_all'] = "Toutes les tâches ont été complétées.";
$lang['Cron.index.attempt_all_system'] = "Tentative d'exécution de toutes les tâches du système.";
$lang['Cron.index.completed_all_system'] = "Toutes les tâches système ont été complétées.";
$lang['Cron.applycredits.attempt'] = "Tenter d'appliquer les crédits aux factures ouvertes.";
$lang['Cron.applycredits.completed'] = "La tâche d'ajout des crédits est terminée.";
$lang['Cron.applycredits.apply_none'] = "Il n'y a pas de factures auxquelles des crédits peuvent être appliqués.";
$lang['Cron.autodebitinvoices.attempt'] = "Tentative d'auto-débit des factures ouvertes.";
$lang['Cron.autodebitinvoices.completed'] = "La tâche de débit automatique des factures est terminée.";
$lang['Cron.autodebitinvoices.charge_attempt'] = "Tentative d'auto débit du client # %1\$s pour toutes les factures ouvertes pour un montant de %2\$s."; // %1$s is the client ID, %2$s is the amount due
$lang['Cron.autodebitinvoices.charge_failed'] = "Incapable de traiter le paiement.";
$lang['Cron.autodebitinvoices.charge_success'] = "Traitement du paiement complété avec succès.";
$lang['Cron.cardexpirationreminders.attempt'] = "Tentative d'envoi des rappels d'expiration de cartes.";
$lang['Cron.cardexpirationreminders.completed'] = "La tâche des rappels d'expiration des cartes est terminée.";
$lang['Cron.cardexpirationreminders.failed'] = "L'avis d'expiration pour le contact %1\$s %2\$s du client #%3\$s n'a pas pu être envoyé."; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID
$lang['Cron.cardexpirationreminders.success'] = "Livré avec succès le rappel d'expiration pour le contact %1\$s %2\$s du client #%3\$s."; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID
$lang['Cron.suspendservices.attempt'] = "Tentative de suspension des services en souffrance.";
$lang['Cron.suspendservices.completed'] = "La tâche de suspension de services a été complétée.";
$lang['Cron.suspendservices.suspend_error'] = "Le service #%1\$s du client %2\$s ne peut être suspendu."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.suspendservices.suspend_success'] = "Le service #%1\$s du client %2\$s a été suspendu."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.unsuspendservices.attempt'] = "Tentative de lever la suspension des services suspendus payés.";
$lang['Cron.unsuspendservices.completed'] = "La tâche de réactivation des services a été complétée.";
$lang['Cron.unsuspendservices.unsuspend_error'] = "Le service #%1\$s du client %2\$s ne peut être rétabli. "; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.unsuspendservices.unsuspend_success'] = "Le service #%1\$s du client %2\$s a été réactivé."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.cancelscheduledservices.attempt'] = "Tentative d'annulation des services planifiés.";
$lang['Cron.cancelscheduledservices.completed'] = "La tâche d'annulation de services programmés a été complétée.";
$lang['Cron.cancelscheduledservices.cancel_error'] = "Le service #%1\$s du client #%2\$s ne peut pas être annulé."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.cancelscheduledservices.cancel_success'] = "Le service #%1\$s du client #%2\$s a été annulé."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.addpaidpendingservices.attempt'] = "Tentative de provision pour services payés en attente.";
$lang['Cron.addpaidpendingservices.completed'] = "La tâche de paiement des services en attente est terminée.";
$lang['Cron.addpaidpendingservices.service_error'] = "Le service en attente #%1\$s du client #%2\$s n'as pu être activé."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.addpaidpendingservices.service_success'] = "Le service en attente #%1\$s du client #%2\$s est maintenant actif."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.!error.cron.failed'] = "Cron n'as pu écrire au journal.";
$lang['Cron.!error.task_execution.failed'] = "Erreur: %1\$s %2\$s"; // %1$s is the error message that occurred, %2$s is the stack trace
$lang['Cron.applycredits.apply_failed'] = "Impossible d'appliquer les crédits en attente pour le client #%1\$s."; // %1$s is the client ID
$lang['Cron.applycredits.apply_success'] = "Les crédits de la transaction %1\$s pour le client #%2\$s à la facture #%3\$s pour un montant de  %4\$s ont été appliqués avec succès."; // %1$s is the transaction number, %2$s is the client ID, %3$s is the invoice ID, and %4$s is the amount applied
$lang['Cron.suspendservices.suspension_reason'] = "Défaut de paiement";
?>