<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Currencies.!error.code.length'] = "Le code de devise doit être de 3 lettres tel que défini dans la norme ISO 4217.";
$lang['Currencies.!error.code.exists'] = "Le code de devise %1\$s et l'ID de compagnie %2\$s est déjà pris."; // %1$s is the currency code, %2$s is the company ID number
$lang['Currencies.!error.company_id.exists'] = "ID de société non valide";
$lang['Currencies.!error.format.format'] = "Format de devise incorrect.";
$lang['Currencies.!error.prefix.length'] = "Le préfixe ne peut excéder 10 caractères.";
$lang['Currencies.!error.suffix.length'] = "Le suffixe de devise ne peut excéder 10 caractères.";
$lang['Currencies.!error.exchange_rate.format'] = "Le taux de change doit être un nombre.";
$lang['Currencies.!error.exchange_updated.format'] = "La date de mise à jour de l'échange n'est pas dans un format valide.";
$lang['Currencies.!error.currency_code.in_use'] = "La devise %1\$s est en cours d'utilisation et ne peut pas être supprimé."; // %1$s is the currency code
$lang['Currencies.!error.currency_code.is_default'] = "La devise %1\$s est celle par défaut et ne peut être supprimée."; // %1$s is the currency code
$lang['Currencies.!error.processor.invalid'] = "Processeur de taux de change invalide.";
$lang['Currencies.!error.processor.empty'] = "Aucun convertisseur de taux d'échange a été paramétré. ";
$lang['Currencies.!error.precision.format'] = "La précision de la devise doit être un nombre compris entre 0 et 4 inclus.";
?>