<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['EmailGroups.!error.action.empty'] = "Veuillez entrer une action.";
$lang['EmailGroups.!error.action.length'] = "La longeur de l'action ne peut excéder 64 caractères.";
$lang['EmailGroups.!error.action.unique'] = "Une action de ce nom existe déjà.";
$lang['EmailGroups.!error.type.format'] = "Type non valide.";
$lang['EmailGroups.!error.group_id.exists'] = "ID de groupe de courriel invalide.";
$lang['EmailGroups.!error.notice_type.valid'] = "Le type de notification doit être défini sur bcc ou sur A.";
?>