<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Encryption.!error.current_passphrase.empty'] = "Veuillez entrer la phrase clé privée actuelle.";
$lang['Encryption.!error.current_passphrase.matches'] = "La phrase secrète actuelle est invalide.";
$lang['Encryption.!error.private_key_passphrase.empty'] = "Veuillez entrer une nouvelle clé privée.";
$lang['Encryption.!error.confirm_new_passphrase.matches'] = "Le nouveau mot de passe ne concorde pas.";
$lang['Encryption.!error.agree.empty'] = "Vous devez accepter que vous avez enregistré ce mot de passe dans un endroit sûr.";
?>