<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GatewayPayments.!error.gateway.exists'] = "La passerelle n'existe pas ou n'est pas activée. ";
$lang['GatewayPayments.!error.transaction_id.exists'] = "La transaction n'as pu être trouvée pour ce client.";
$lang['GatewayPayments.!error.account_id.exists'] = "Le compte de paiement n'as pu être trouvé pour ce client.";
$lang['GatewayPayments.!error.contact_id.exists'] = "Le contact n'a pas pu être trouvé pour ce client.";
$lang['GatewayPayments.!error.type.valid'] = "Ce type de paiement n'est pas supporté par cette passerelle.";
$lang['GatewayPayments.!error.type.instance'] = "La passerelle ne supporte pas les paiements de cette sorte.";
$lang['GatewayPayments.!error.reference_id.store'] = "La passerelle de paiement n'as pu enregistrer le compte de paiement.";
$lang['GatewayPayments.!error.reference_id.update'] = "La passerelle de paiement n'as pu mettre à jour le compte de paiement.";
$lang['GatewayPayments.!error.reference_id.remove'] = "La passerelle de paiement n'as pu enlever le compte de paiement.";
$lang['GatewayPayments.!error.response_status'] = "La passerelle de paiement renvoyé une réponse inattendue.";
$lang['GatewayPayments.!error.gateway.declined'] = "Le paiement a été refusé.";
$lang['GatewayPayments.!error.gateway.error'] = "La passerelle de paiement a renvoyé une erreur lors du traitement de la demande.";
?>