<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GatewayManager.!error.company_id.valid'] = "ID de compagnie invalide.";
$lang['GatewayManager.!error.class.valid'] = "Classe invalide.";
$lang['GatewayManager.!error.name.valid'] = "Le nom est invalide.";
$lang['GatewayManager.!error.version.valid'] = "Version invalide";
$lang['GatewayManager.!error.currencies[].exists'] = "Au moins une devise n'est pas acceptée par cette passerelle.";
$lang['GatewayManager.!error.currencies[].in_use'] = "Au moins une devise est présentement en utilisation par une autre passerelle.";
?>