<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Invoices.getPricingPeriods.day'] = "Jour";
$lang['Invoices.getPricingPeriods.week'] = "Semaine";
$lang['Invoices.getPricingPeriods.month'] = "Mois";
$lang['Invoices.getPricingPeriods.year'] = "Année";
$lang['Invoices.getDeliveryMethods.email'] = "Courriel";
$lang['Invoices.getDeliveryMethods.paper'] = "Papier";
$lang['Invoices.getDeliveryMethods.interfax'] = "InterFax";
$lang['Invoices.getDeliveryMethods.postalmethods'] = "PostalMethods";
$lang['Invoices.!error.invoice_id.exists'] = "ID de facture invalide.";
$lang['Invoices.!error.invoice_recur_id.exists'] = "invalide ID du facture récurrente.";
$lang['Invoices.!error.method.exists'] = "Vous devez définir au moins un mode de livraison.";
$lang['Invoices.!error.delivery.empty'] = "Veuillez entrer une méthone de livraison de facture.";
$lang['Invoices.!error.delivery.length'] = "La méthode de livraison de facture ne peut excéder 32 caractères.";
$lang['Invoices.!error.id_format.empty'] = "Aucun format d'ID n'est défini pour les factures.";
$lang['Invoices.!error.id_format.length'] = "Le format d'identification pour les factures ne doit pas dépasser 64 caractères.";
$lang['Invoices.!error.id_value.valid'] = "Impossible de déterminer la valeur de l'ID facture.";
$lang['Invoices.!error.id.amount_applied'] = "Cette facture ne peut être mise à jour parce qu'un montant a déjà été appliqué.";
$lang['Invoices.!error.client_id.exists'] = "Invalid ID client.";
$lang['Invoices.!error.date_billed.format'] = "La date de facturation est dans un format de date invalide.";
$lang['Invoices.!error.date_due.format'] = "La date d'échéance est dans un format de date non valide.";
$lang['Invoices.!error.date_closed.format'] = "La date de fermeture est dans format invalide.";
$lang['Invoices.!error.date_autodebit.format'] = "La date d'échéance est dans un format de date non valide.";
$lang['Invoices.!error.status.format'] = "Statut invalide.";
$lang['Invoices.!error.currency.length'] = "Le code de devise ne doit dépasser 3 caractères.";
$lang['Invoices.!error.delivery.exists'] = "Le type de méthode de livraison fourni n'existe pas.";
$lang['Invoices.!error.term.format'] = "Le terme doit être un nombre";
$lang['Invoices.!error.term.bounds'] = "Les termes doit être entre 1 et 65535.";
$lang['Invoices.!error.period.format'] = "Cette période est invalide.";
$lang['Invoices.!error.duration.format'] = "La durée n'est pas valide.";
$lang['Invoices.!error.date_renews.format'] = "La date de renouvellement de la facture récurrente doit être un format de date valide.";
$lang['Invoices.!error.date_last_renewed.format'] = "La dernière facture automatique doit avoir un format de date valide";
$lang['Invoices.!error.invoice_id.draft'] = "La facture donnée n'est pas un brouillon de facture, et ne peut donc pas être supprimé.";
$lang['Invoices.!error.lines[][id].exists'] = "Invalid ID de l'élément de ligne.";
$lang['Invoices.!error.lines[][service_id].exists'] = "ID de service invalide.";
$lang['Invoices.!error.lines[][description].empty'] = "S'il vous plaît entrer une description pour la ligne d'élément.";
$lang['Invoices.!error.lines[][qty].format'] = "La quantité doit être un nombre.";
$lang['Invoices.!error.lines[][qty].minimum'] = "Veuillez entrer une quantité de 1 ou plus.";
$lang['Invoices.!error.lines[][amount].format'] = "Le coût unitaire doit être un nombre.";
$lang['Invoices.!error.lines[][tax].format'] = "La ligne d'item taxable doit être un «vrai» ou «faux»";
$lang['Invoices.!line_item.service_cancel_fee_description'] = "%1\$s - %2\$s Frais d'annulation"; // %1$s is the name of the package, %2$s is the name of the service
$lang['Invoices.!line_item.service_setup_fee_description'] = "Frais d'installation du package et service"; // %1$s is the name of the package, %2$s is the name of the service
$lang['Invoices.!line_item.coupon_line_item_description_amount'] = "Coupon %1\$s"; // %1$s is the coupon code
$lang['Invoices.!line_item.coupon_line_item_description_percent'] = "Coupon %1\$s - %2\$s%%"; // %1$s is the coupon code, %2$s is the coupon discount percentage, the two percent symbols (%%) must both be used together to display a single percent symbol
$lang['Invoices.!error.date_due.after_billed'] = "La date d'échéance doit être la journée de la facturation ou après.";
$lang['Invoices.!line_item.recurring_renew_description'] = "%1\$s (%2\$s - %3\$s)"; // %1$s is the line item description, %2$s is the invoice's renew date, %3$s is the invoice's next renew date
$lang['Invoices.status.active'] = "Actif";
$lang['Invoices.status.draft'] = "Brouillon";
$lang['Invoices.status.void'] = "Annulé";
$lang['Invoices.!line_item.service_renew_description'] = "%5\$s%1\$s - %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the package, %2$s is the name of the service, %3$s is the service's renew date, %4$s is the service's next renew date, %5$s is the addon identifier set only for addon services
$lang['Invoices.!line_item.service_prorated_upgrade_description'] = "Mise à jour au Pro Rata de %1\$s à %2\$s - %3\$s (%4\$s - %5\$s)"; // %1$s is the current package name, %2$s is the new package name, %3$s is the service name, %4$s is the current date, %5$s is the service's next renew date
$lang['Invoices.status.proforma'] = "Pro Forma";
$lang['Invoices.types.standard'] = "Standard";
$lang['Invoices.types.proforma'] = "Pro Forma";
$lang['Invoices.!line_item.service_option_renew_description'] = "? %1\$s - %2\$s"; // %1$s is the package option label, %2$s is the service option name
$lang['Invoices.!line_item.service_option_setup_fee_description'] = "? %1\$s - %2\$s Frais d'installation"; // %1$s is the package option label, %2$s is the service option name
$lang['Invoices.!line_item.service_prorated_upgrade_description_onetime'] = "Mise à niveau au prorata de %1\$s à %2\$s - %3\$s"; // %1$s is the current package name, %2$s is the new package name, %3$s is the service name
$lang['Invoices.!line_item.service_option_prorated_upgrade_description'] = "Mise à niveau au prorata de %1\$s de %2\$s à %3\$s (%4\$s - %5\$s)"; // %1$s is the service option label name, %2$s is the current service option value, %3$s is the new service option value, %4$s is the current date, %5$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_upgrade_description_onetime'] = "↳ Mise à jour au Pro Rata de %1\$s,  de %2\$s à %3\$s"; // %1$s is the service option label name, %2$s is the current service option value, %3$s is the new service option value
$lang['Invoices.!line_item.service_option_prorated_upgrade_qty_description'] = "? Mise à niveau au prorata de %1\$s de %2\$sx %3\$s à %4\$sx %5\$s (%6\$s - %7\$s)"; // %1$s is the service option label name, %2$s is the old service option quantity, %3$s is the current service option value, %4$s is the new service option quantity, %5$s is the new service option value, %6$s is the current date, %7$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_upgrade_qty_description_onetime'] = "? Mise à niveau au prorata de %1\$s de %2\$sx %3\$s vers %4\$sx %5\$s"; // %1$s is the service option label name, %2$s is the old service option quantity, %3$s is the current service option value, %4$s is the new service option quantity, %5$s is the new service option value
$lang['Invoices.!line_item.service_option_prorated_addition_description'] = "? Ajout au prorata de %1\$s %2\$s (%3\$s - %4\$s)"; // %1$s is the service option label name, %2$s is the service option value, %3$s is the current date, %4$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_addition_description_onetime'] = "? Ajout au prorata de %1\$s %2\$s"; // %1$s is the service option label name, %2$s is the service option value
$lang['Invoices.!line_item.service_option_prorated_addition_qty_description'] = "? Ajout au prorata de %1\$s %2\$sx %3\$s (%4\$s - %5\$s)"; // %1$s is the service option label name, %2$s is the service option quantity, %3$s is the service option value, %4$s is the current date, %5$s is the service's next renew date
$lang['Invoices.!line_item.service_option_prorated_addition_qty_description_onetime'] = "? Ajout au prorata de %1\$s %2\$s x %3\$s"; // %1$s is the service option label name, %2$s is the service option quantity, %3$s is the service option value
$lang['Invoices.!line_item.prorated_credit'] = "Crédit au prorata";
$lang['Invoices.!note_private.service_cancel_date'] = "Service #%1\$s annulé %2\$s."; // %1$s is the service ID, %2$s is the formatted service cancellation date and time
$lang['Invoices.!note_private.removed_lines'] = "Retirer ligne produit";
$lang['Invoices.!note_private.line_item'] = "- %1\$s @ %2\$s: %3\$s"; // %1$s is the line item quantity, %2$s is the unit price, %3$s is the line item description
$lang['Invoices.!error.autodebit.valid'] = "Veuillez choisir d'autoriser ou non le débit automatique pour cette facture.";
?>