<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Languages.!error.code.valid'] = "La langue par défaut 'en_us' ne peut être enlevé.";
$lang['Languages.!error.code.format'] = "Le code de langue n'est pas formaté de façon appropriée.";
$lang['Languages.!error.code.unique'] = "Ce code de langue existe déjà pour cette compagnie.";
$lang['Languages.!error.company_id.format'] = "L'ID de compagnie semble invalide.";
$lang['Languages.!error.name.format'] = "Le champ du nom de la langue ne peut être vide.";
?>