<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Logs.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['Logs.!error.to_address.empty'] = "Adresse de destination manquante.";
$lang['Logs.!error.from_address.empty'] = "de l'adresse est Manquer ";
$lang['Logs.!error.from_name.empty'] = "Nom de provenance manquant.";
$lang['Logs.!error.subject.empty'] = "Sujet manquant.";
$lang['Logs.!error.sent.format'] = "Envoyé doit être un nombre.";
$lang['Logs.!error.sent.length'] = "\"Envoyé\" ne peut dépasser 1 caractère.";
$lang['Logs.!error.staff_id.empty'] = "ID d'équipe manquant.";
$lang['Logs.!error.module_id.exists'] = "ID de module invalide.";
$lang['Logs.!error.gateway_id.exists'] = "ID de passerelle invalide.";
$lang['Logs.!error.direction.format'] = "Type de direction invalide.";
$lang['Logs.!error.url.empty'] = "URL manquant.";
$lang['Logs.!error.status.format'] = "Type de statut invalide";
$lang['Logs.!error.group.empty'] = "Groupe manquant.";
$lang['Logs.!error.group.maxlength'] = "La longeur du groupe ne peut excéder 8 caractères.";
$lang['Logs.!error.user_id.empty'] = "ID d'utilisateur manquant.";
$lang['Logs.!error.ip_address.empty'] = "Adresse IP manquante.";
$lang['Logs.!error.ip_address.length'] = "L'adresse IP ne doit pas dépasser 39 caractères.";
$lang['Logs.!error.contact_id.empty'] = "ID de contact manquant.";
$lang['Logs.!error.type.format'] = "Type invalide.";
$lang['Logs.!error.account_id.empty'] = "ID de compte manquant.";
$lang['Logs.!error.first_name.empty'] = "Le prénom ne peut être vide.";
$lang['Logs.!error.last_name.empty'] = "Le nom de famille ne peut être vide. ";
$lang['Logs.!error.run_id.exists'] = "ID de tâche Cron invalide.";
$lang['Logs.!error.event.maxlength'] = "La longueur de l'événement ne peut pas dépasser 32 caractères.";
$lang['Logs.!error.group.unique'] = "L'ID de tâche cron et le groupe ont déjà été prises.";
$lang['Logs.!error.group.betweenlength'] = "Le groupe doit avoir entre 1 et 32 caractères de long.";
$lang['Logs.!error.start_date.format'] = "Format de date de départ invalide. ";
$lang['Logs.!error.end_date.format'] = "Format de date de fin invalide.";
$lang['Logs.!error.deletelog_datetime'] = "Format de date invalide.";
$lang['Logs.!error.user_log_exists.empty'] = "L'utilisateur à l'adresse IP fournie n'existe pas.";
$lang['Logs.!error.result.format'] = "Le résultat de connexion doit être soit «réussi» ou «échec».";
$lang['Logs.!error.client_id.exists'] = "ID client invalide.";
$lang['Logs.!error.fields.empty'] = "Champs de journalisation manquant.";
$lang['Logs.!error.by_user_id.exists'] = "Invalide par l'ID utilisateur.";
$lang['Logs.!error.date_changed.valid'] = "Date de changement invalide";
?>