<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ModuleManager.!error.company_id.valid'] = "ID de compagnie invalide.";
$lang['ModuleManager.!error.class.valid'] = "La classe est invalide.";
$lang['ModuleManager.!error.name.valid'] = "Le nom est invalide.";
$lang['ModuleManager.!error.version.valid'] = "Version invalide.";
$lang['ModuleManager.!error.name.empty'] = "Vous devez spécifier un nom pour le groupe.";
$lang['ModuleManager.!error.module_rows[].valid'] = "Un ou plusieurs des lignes spécifiées n'appartiennent pas à ce module.";
$lang['ModuleManager.!error.module_row_id.assigned_package'] = "La ligne ne peut pas être supprimée car il appartient à un ou plusieurs ensembles.";
$lang['ModuleManager.!error.module_group_id.assigned_package'] = "Le groupe ne peut être effacé car il appartiens à un ou plusieurs ensembles.";
$lang['ModuleManager.!error.module_row_id.assigned_service'] = "La ligne ne peut pas être supprimée car elle appartient à un ou plusieurs services.";
$lang['ModuleManager.!error.module_id.assigned_package'] = "Le module ne peut être désinstallé car il est en utilisation par un ou plusieurs ensembles actifs.";
$lang['ModuleManager.!error.module_id.assigned_service'] = "Le module ne peut être désinstallé car il est utilisé par un ou plusieurs services actifs. ";
$lang['ModuleManager.!error.force_limits.valid'] = "La question de savoir s'il faut imposer des limites strictes doit être fixée à 0 ou 1.";
?>