<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageGroups.!error.name.empty'] = "Veuillez spécifier un nom du groupe d'ensembles.";
$lang['PackageGroups.!error.type.format'] = "Type de groupe invalide.";
$lang['PackageGroups.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['PackageGroups.!error.parents.format'] = "Au moins un ID de groupe parent donné est un groupe non-standard disponible pour une utilisation en tant que parent.";
$lang['PackageGroups.gettypes.standard'] = "Standard";
$lang['PackageGroups.gettypes.addon'] = "Add-on";
$lang['PackageGroups.!error.allow_upgrades.format'] = "Pour que les forfaits puissent être mis à niveau/déclassés cela doit être mis à 1 ou à 0.";
?>