<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageOptionGroups.!error.company_id.exists'] = "S'il vous plaît spécifier un ID d'entreprise valide.";
$lang['PackageOptionGroups.!error.name.empty'] = "Veuillez spécifier un nom de groupe.";
$lang['PackageOptionGroups.!error.name.length'] = "Le nom du groupe ne peut excéder 128 caractères. ";
$lang['PackageOptionGroups.!error.group_id.exists'] = "ID de groupe d'options de forfait non valide.";
?>