<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Packages.!error.package_id.exists'] = "L'ensemble ne peut être effacé parce qu'un service l'utilise présentement.";
$lang['Packages.!error.name.empty'] = "S'il vous plaît entrez un nom de paquet.";
$lang['Packages.!error.qty.format'] = "Quantité doit être un nombre.";
$lang['Packages.!error.taxable.format'] = "Taxable doit être un nombre";
$lang['Packages.!error.taxable.length'] = "La longueur du champ ne doit pas dépasser 1 caractère.";
$lang['Packages.!error.status.format'] = "Statut invalide.";
$lang['Packages.!error.email_content[][lang].empty'] = "Veuillez entrer une langue.";
$lang['Packages.!error.email_content[][lang].length'] = "La langue ne peut excéder 5 caractères.";
$lang['Packages.!error.groups[].exists'] = "ID de groupe de forfait non valide.";
$lang['Packages.!error.groups[].valid'] = "Le groupe d'ensemble choisi n'appartient pas à l'entreprise donnée.";
$lang['Packages.getPricingPeriods.day'] = "Jour";
$lang['Packages.getPricingPeriods.week'] = "Semaine";
$lang['Packages.getPricingPeriods.month'] = "Mois";
$lang['Packages.getPricingPeriods.year'] = "Année";
$lang['Packages.getPricingPeriods.onetime'] = "Une seule fois";
$lang['Packages.getStatusTypes.active'] = "Actif";
$lang['Packages.getStatusTypes.inactive'] = "Inactif";
$lang['Packages.getStatusTypes.restricted'] = "Restreint";
$lang['Packages.!error.pricing[][term].format'] = "Le terme doit être un nombre.";
$lang['Packages.!error.pricing[][term].length'] = "La durée du terme ne peut pas dépasser 5 caractères.";
$lang['Packages.!error.pricing[][period].format'] = "Type de période invalide.";
$lang['Packages.!error.pricing[][price].format'] = "Le prix doit être un chiffre.";
$lang['Packages.!error.pricing[][setup_fee].format'] = "Les frais de mise en service doit être un nombre.";
$lang['Packages.!error.pricing[][cancel_fee].format'] = "Les frais d'annulation doivent être un nombre. ";
$lang['Packages.!error.pricing[][currency].format'] = "Le code de devise doit être de 3 caractères.";
$lang['Packages.!error.pricing[][id].format'] = "ID de prix du forfait non valide.";
$lang['Packages.getPricingPeriods.day_plural'] = "Jours";
$lang['Packages.getPricingPeriods.week_plural'] = "Semaines";
$lang['Packages.getPricingPeriods.month_plural'] = "Mois";
$lang['Packages.getPricingPeriods.year_plural'] = "Années";
$lang['Packages.getPricingPeriods.onetime_plural'] = "Une fois";
$lang['Packages.!error.company_id.exists'] = "Compagnie fournie invalide.";
$lang['Packages.!error.module_id.exists'] = "Module invalide.";
$lang['Packages.!error.module_row.format'] = "Ligne de module donnée invalide.";
$lang['Packages.!error.pricing[][term].valid'] = "Le terme doit être plus grand que 0.";
$lang['Packages.!error.module_group.format'] = "Groupe de module invalide";
$lang['Packages.!error.option_groups[].valid'] = "Groupe d'options de forfait configurable donné non valide.";
$lang['Packages.!error.single_term.valid'] = "Terme unique doit être 1 ou 0.";
$lang['Packages.!error.pricing[][term].deletable'] = "Le terme ne peut pas être supprimé car il est utilisé par un ou plusieurs services.";
$lang['Packages.!error.prorata_day.format'] = "Le jour de Pro Rata doit être entre 1 et 28.";
$lang['Packages.!error.prorata_cutoff.format'] = "La journée de coupure au Pro Rata doit être entre 1 et 28.";
$lang['Packages.!error.email_content.parse'] = "Erreur d'analyse du modèle: %1\$s"; // %1$s is the parse error generated
$lang['Packages.!error.module_id.changed'] = "Le module ne peut pas être modifié car un ou plusieurs services utilisent déjà ce forfait.";
$lang['Packages.!error.plugins[].valid'] = "Plugin invalide donné.";
?>