<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageOptions.!error.company_id.exists'] = "Identifiant de compagnie invalide";
$lang['PackageOptions.!error.label.empty'] = "Veuillez entrer une étiquette";
$lang['PackageOptions.!error.label.length'] = "L'étiquette ne peut dépasser 128 caractères de long.";
$lang['PackageOptions.!error.name.empty'] = "Veuillez entrer un nom pour cette option.";
$lang['PackageOptions.!error.name.length'] = "Le nom ne peut excéder 128 caractères en longueur.";
$lang['PackageOptions.!error.values.count'] = "Il ne peut y avoir qu'une seule entrée de valeur d'option pour les types de cases à cocher, de quantité, de texte, de zone de texte ou de mot de passe.";
$lang['PackageOptions.!error.values[][step].valid'] = "Une valeur d'étape ne peut être définie que pour le type quantité et doit être égale ou supérieure à 1.";
$lang['PackageOptions.!error.values[][min].valid'] = "Une valeur limite minimale ne peut être définie que pour le type de la quantité, et doit être une valeur de 0 ou plus.";
$lang['PackageOptions.!error.values[][max].valid'] = "La valeur limite maximale ne peut être réglé que pour le type de quantité, et doit être une valeur de 1 ou plus.";
$lang['PackageOptions.!error.values[][name].empty'] = "Veuillez entrer un nom pour cette option.";
$lang['PackageOptions.!error.values[][name].length'] = "La nom de la valeur de l'option ne peut dépasser 128 caractères.";
$lang['PackageOptions.!error.values[][value].length'] = "La valeur de l'option ne peut excéder 255 caractères.";
$lang['PackageOptions.!error.groups.exists'] = "Au moins un des ID de groupe d'options de forfait donnés n'existe pas ou n'appartient pas à la même société.";
$lang['PackageOptions.!error.option_id.exists'] = "ID d'option de d'ensemble invalide.";
$lang['PackageOptions.!error.values[][pricing][][term].format'] = "Le terme doit être un nombre";
$lang['PackageOptions.!error.values[][pricing][][term].length'] = "La longueur du terme ne peut excéder 5 caractères.";
$lang['PackageOptions.!error.values[][pricing][][term].valid'] = "Le terme doit être plus grand que 0.";
$lang['PackageOptions.!error.values[][pricing][][period].format'] = "Type de période invalide.";
$lang['PackageOptions.!error.values[][pricing][][price].format'] = "Le prix doit être un nombre.";
$lang['PackageOptions.!error.values[][pricing][][setup_fee].format'] = "Les frais d'installation doit être un nombre.";
$lang['PackageOptions.!error.values[][pricing][][currency].format'] = "Le code de devise doit être de 3 caractères.";
$lang['PackageOptions.gettypes.checkbox'] = "Checkbox";
$lang['PackageOptions.gettypes.select'] = "Déroulant";
$lang['PackageOptions.gettypes.quantity'] = "Quantité";
$lang['PackageOptions.gettypes.radio'] = "Radio";
$lang['PackageOptions.getfields.label_quantity'] = "x %1\$s %2\$s"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.getfields.label_quantity_setup'] = "x %1\$s %2\$s + %3\$s installation"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.getfields.label_radio'] = "%1\$s (%2\$s)"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.getfields.label_radio_setup'] = "%1\$s (%2\$s + %3\$s d'installation)"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.getfields.label_select'] = "%1\$s (%2\$s)"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.getfields.label_select_setup'] = "%1\$s (%2\$s + %3\$s de frais d'installation)"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.getfields.label_checkbox'] = "%1\$s (%2\$s)"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.getfields.label_checkbox_setup'] = "%1\$s (%2\$s + %3\$s de frais d'installation)"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.!error.type.valid'] = "Veuillez sélectionner un type d'option.";
$lang['PackageOptions.!error.values[][id].exists'] = "ID de valeur d'option de forfait non valide.";
$lang['PackageOptions.!error.values[][pricing][][id].exists'] = "ID de prix des options de forfait non valide.";
$lang['PackageOptions.!error.values.select_value'] = "Au moins une valeur d'option contient des caractères spéciaux non valides.";
$lang['PackageOptions.gettypes.text'] = "Texte";
$lang['PackageOptions.gettypes.textarea'] = "Zone de texte";
$lang['PackageOptions.gettypes.password'] = "Mot de passe";
$lang['PackageOptions.getfields.label_text'] = "%1\$s"; // %1$s is the option price
$lang['PackageOptions.getfields.label_text_setup'] = "%1\$s + %2\$s configuration"; // %1$s is the option price, %2$s is the setup fee
$lang['PackageOptions.getfields.label_password'] = "%1\$s"; // %1$s is the option price
$lang['PackageOptions.getfields.label_password_setup'] = "%1\$s + %2\$s configuration"; // %1$s is the option price, %2$s is the setup fee
$lang['PackageOptions.getfields.label_textarea'] = "%1\$s"; // %1$s is the option price
$lang['PackageOptions.getfields.label_textarea_setup'] = "%1\$s + %2\$s mise en service"; // %1$s is the option price, %2$s is the setup fee
?>