<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Permissions.!error.group_id.exists'] = "Le groupe de permission mentionné n'existe pas.";
$lang['Permissions.!error.alias.empty'] = "La permission doit avoir un alias.";
$lang['Permissions.!error.action.empty'] = "La permission doit avoir une action.";
$lang['Permissions.!error.plugin_id.exists'] = "Le plugin spécifié pour cette permission n'existe pas.";
$lang['Permissions.!error.level.group_empty'] = "Le niveau doit être soit \"personnel\" ou \"client\".";
$lang['Permissions.!error.alias.group_empty'] = "Le groupe de permission doit avoir un alias.";
$lang['Permissions.!error.plugin_id.group_exists'] = "Le plugin spécifié pour ce groupe d'autorisation n'existe pas.";
$lang['Permissions.!error.name.empty'] = "L'autorisation doit avoir un nom.";
$lang['Permissions.!error.name.group_empty'] = "Le groupe de permissions doit avoir un nom.";
?>