<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PluginManager.!error.dir.empty'] = "S'il vous plaît entrez le répertoire du plugin.";
$lang['PluginManager.!error.dir.length'] = "Le répertoire du plugin ne peut dépasser 64 caractères en longueur. ";
$lang['PluginManager.!error.company_id.exists'] = "ID de compagnie invalide";
$lang['PluginManager.!error.name.empty'] = "Veuillez entrer un nom pour le plugin.";
$lang['PluginManager.!error.author.empty'] = "Veuillez spécifier l'auteur du plugin. ";
$lang['PluginManager.!error.version.empty'] = "S'il vous plaît entrez la version du plugin.";
$lang['PluginManager.!error.version.length'] = "La longueur de la version plug-in ne peut pas dépasser 16 caractères.";
$lang['PluginManager.!error.event.empty'] = "S'il vous plaît entrer un événement.";
$lang['PluginManager.!error.event.length'] = "L'événement ne peut excéder 32 caractères en longueur.";
$lang['PluginManager.!error.callback.empty'] = "Veuillez spécifier un rappel.";
$lang['PluginManager.!error.action.empty'] = "Veuillez entrer une action.";
$lang['PluginManager.!error.action.length'] = "La longueur de l'action ne peut excéder 32 caractères.";
$lang['PluginManager.!error.uri.empty'] = "Veuillez entrer un URI.";
$lang['PluginManager.!error.name.action_empty'] = "Veuillez entrer un nom d'action";
$lang['PluginManager.!error.action.unique'] = "L'action et l'URI doivent être uniques pour ce plugin.";
?>