<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Pricings.!error.term.format'] = "Les termes doivent être un nombre.";
$lang['Pricings.!error.term.length'] = "La longueur du terme ne peut excéder 5 caractères.";
$lang['Pricings.!error.term.valid'] = "Le terme doit être supérieur à 0.";
$lang['Pricings.!error.period.format'] = "Type de période invalide.";
$lang['Pricings.!error.price.format'] = "Le prix doit être un nombre.";
$lang['Pricings.!error.setup_fee.format'] = "Les frais d'installation doivent être un nombre.";
$lang['Pricings.!error.cancel_fee.format'] = "Les frais d'annulation doivent être un nombre.";
$lang['Pricings.!error.currency.format'] = "Le code de devise doit être de 3 caractères.";
$lang['Pricings.getPeriods.day'] = "Jour";
$lang['Pricings.getPeriods.week'] = "Semaine";
$lang['Pricings.getPeriods.month'] = "Mois";
$lang['Pricings.getPeriods.year'] = "Année";
$lang['Pricings.getPeriods.onetime'] = "Une seule fois";
$lang['Pricings.getPeriods.day_plural'] = "Jours";
$lang['Pricings.getPeriods.week_plural'] = "Semaines";
$lang['Pricings.getPeriods.month_plural'] = "Mois";
$lang['Pricings.getPeriods.year_plural'] = "Années";
$lang['Pricings.getPeriods.onetime_plural'] = "Une fois";
?>