<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ReportManager.!error.type.valid'] = "Veuillez choisir un type de rapport valide.";
$lang['ReportManager.!error.format.valid'] = "Veuillez sélectionner un format de rapport valide.";
$lang['ReportManager.!error.temp_dir.writable'] = "Le répertoire temporaire n'est pas accessible en écriture ou le rapport ne peut y être écrit.";
$lang['ReportManager.getformats.csv'] = "CSV";
$lang['ReportManager.!error.name.valid'] = "Le rapport doit avoir un nom.";
$lang['ReportManager.!error.query.empty'] = "Le rapport doit avoir une requête.";
$lang['ReportManager.!error.query.valid'] = "Une seule requête est autorisée et il doit s'agir d'une requête SELECT.";
$lang['ReportManager.!error.date_created.format'] = "Date de création est un format non valide.";
$lang['ReportManager.reportfieldtypes.text'] = "Texte";
$lang['ReportManager.reportfieldtypes.select'] = "Sélectionner";
$lang['ReportManager.reportfieldtypes.date'] = "Date";
$lang['ReportManager.reportrequiredtypes.no'] = "Non";
$lang['ReportManager.reportrequiredtypes.yes'] = "Oui";
$lang['ReportManager.reportrequiredtypes.custom'] = "Expression régulière personnalisée";
$lang['ReportManager.getformats.json'] = "JSON";
?>