<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ServiceInvoices.!error.service_id.exists'] = "ID de service invalide ";
$lang['ServiceInvoices.!error.invoice_id.exists'] = "ID de facture invalide.";
?>