<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ServiceChanges.!error.id.exists'] = "ID de modification de service non valide.";
$lang['ServiceChanges.!error.service_id.exists'] = "ID de service invalide";
$lang['ServiceChanges.!error.invoice_id.exists'] = "ID de facture invalide.";
$lang['ServiceChanges.!error.invoice_id.unique'] = "L'ID de facture est déjà défini pour un changement de service et ne peut pas être défini à nouveau.";
$lang['ServiceChanges.!error.status.valid'] = "S'il vous plait sélectionnez un statut valide";
$lang['ServiceChanges.status.pending'] = "En attente";
$lang['ServiceChanges.status.completed'] = "Complété";
$lang['ServiceChanges.status.error'] = "Erreur";
$lang['ServiceChanges.status.canceled'] = "Annulé";
?>