<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Staff.!error.user_id.exists'] = "ID d'utilisateur invalide.";
$lang['Staff.!error.user_id.unique'] = "L'ID de personnel %1\$s est déjà utilisé."; // %1$s is the staff user ID number
$lang['Staff.!error.first_name.empty'] = "S'il vous plaît, entrez un prénom.";
$lang['Staff.!error.last_name.empty'] = "S'il vous plaît entrez un nom de famille.";
$lang['Staff.!error.email.format'] = "Veuillez entrer une adresse courriel valide.";
$lang['Staff.!error.status.format'] = "Statut invalide.";
$lang['Staff.!error.groups[].format'] = "Il y a un ou plusieurs ID de groupe invalide.";
$lang['Staff.!error.groups.unique_company'] = "Seul un groupe d'employés par entreprise peut être attribué à un membre du personnel";
$lang['Staff.!error.staff_id.format'] = "L'ID de personnel doit être un nombre.";
$lang['Staff.!error.company_id.format'] = "L'ID de compagnie doit être un nombre.";
$lang['Staff.!error.uri.empty'] = "Veuillez entrer un URI.";
$lang['Staff.!error.title.empty'] = "Veuillez entrer un titre.";
$lang['Staff.!error.order.format'] = "La clé de tri doit être un nombre.";
$lang['Staff.!error.order.length'] = "La longueur de l'ordre de tri ne peut excéder 5 caractères.";
$lang['Staff.!error.staff_group_id.exists'] = "L'ID du groupe du staff est invalide.";
$lang['Staff.!error.staff_id.exists'] = "ID de personnel invalide.";
$lang['Staff.!error.action.exists'] = "Le groupe d'action courriel %1\$s n'existe pas."; // %1$s is the name of the email group action
$lang['Staff.!error.action[].exists'] = "Au moins l'une des actions de groupe de courriel n'existe pas.";
?>