<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['States.!error.code.format'] = "Le code d'état doit être alphanumérique tel que défini dans la norme ISO 3166-2.";
$lang['States.!error.country_alpha2.format'] = "pays Alpha2  doit être de 2 caractères alphabétiques.";
$lang['States.!error.country_alpha2.in_use'] = "Le code de pays alpha 2 %1\$s et le code de subdivision %2\$s sont déjà pris."; // %1$s is the alpha2 country code, %2$s is the state code
$lang['States.!error.name.format'] = "Veuillez entrer le nom de l’état.";
?>