<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SystemRequirements.!error.php.minimum'] = "PHP version %1\$s ou plus récente est requise. Votre version: %2\$s."; // %1$s is the minimum version of PHP (i.e. 5.1.3), %2$s is the current version
$lang['SystemRequirements.!warning.mcrypt.recommended'] = "L'extension mcrypt est recommandée pour de meilleures performances.";
$lang['SystemRequirements.!warning.gmp.recommended'] = "L'extension GMP est hautement recommandée pour une meilleure performance.";
$lang['SystemRequirements.!warning.cache_writable.recommended'] = "Pour une meilleure performance, assurez-vous que le serveur web peut écrire à %1\$s "; // %1$s is the absolute path to the cache directory
$lang['SystemRequirements.!warning.imap.recommended'] = "L'extension IMAP est requise pour envoyer et recevoir des courriels par SMTP et IMAP.";
$lang['SystemRequirements.!warning.zlib.recommended'] = "L'extension zlib est hautement recommandée pour une meilleure performance.";
$lang['SystemRequirements.!warning.mbstring.recommended'] = "L'extension mbstring est requise par certaines fonctionnalités optionnelles.";
$lang['SystemRequirements.!warning.gd.recommended'] = "L'extension gd est recommandé pour un meilleur support pour les images durant la création des PDF.";
$lang['SystemRequirements.!warning.libxml.recommended'] = "L'extension libxml est fortement recommandé car elle peut être nécessaire pour l'interface avec certains systèmes.";
$lang['SystemRequirements.!warning.mailparse.recommended'] = "L'extension mailparse est requise pour décrypter les emails entrant";
$lang['SystemRequirements.!error.config_writable.minimum'] = "Le fichier de configuration (%1\$s) et le répertoire (%2\$s) doivent être accessibles en écriture par le serveur Web."; // %1$s is the absolute path to the config file, %2$s is the absolute path to the config directory
$lang['SystemRequirements.!warning.simplexml.recommended'] = "L'extension simplexml est fortement recommandée car elle peut être nécessaire pour s'interfacer avec certains systèmes.";
$lang['SystemRequirements.!error.extension.minimum'] = "L'extension '%1\$s' est requise."; // %1$s is the minimum version of the extension required
$lang['SystemRequirements.!warning.iconv.recommended'] = "L'extension iconv est requise pour le codage et le décodage de caractères spéciaux.";
?>