<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SystemEvents.!error.event.empty'] = "Veuillez saisir un nom d'événement.";
$lang['SystemEvents.!error.event.length'] = "L'événement ne doit pas dépasser %1\$s caractères."; // %1$s is the maximum number of characters allowed
$lang['SystemEvents.!error.observer.valid'] = "Veuillez fournir un responsable joignable, par espace de nommage ou par chemin d'accès au système de fichiers.";
?>