<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Taxes.!error.company_id.exists'] = "ID d'entreprise invalide.";
$lang['Taxes.!error.level.format'] = "Le niveau de taxe doit être un nombre.";
$lang['Taxes.!error.level.length'] = "La longueur du niveau de taxes ne peut excéder 2 caractères.";
$lang['Taxes.!error.name.length'] = "Le nom de la taxe ne peut excéder 64 caractères.";
$lang['Taxes.!error.amount.format'] = "Le montant doit être un nombre.";
$lang['Taxes.!error.type.format'] = "Type de taxe invalide.";
$lang['Taxes.!error.status.format'] = "Statut invalide.";
$lang['Taxes.!error.tax_id.exists'] = "ID de taxe invalide.";
$lang['Taxes.getTaxStatus.active'] = "Actif";
$lang['Taxes.getTaxStatus.inactive'] = "Inactif";
$lang['Taxes.getTaxTypes.inclusive'] = "Inclusif";
$lang['Taxes.getTaxTypes.exclusive'] = "Exclusif";
$lang['Taxes.!error.country.valid'] = "Pays n'est pas un code de pays ISO 3166-1 valide.";
$lang['Taxes.!error.state.valid'] = "L'état n'est pas un code de subdivision ISO 3166-2 valide.";
?>