<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Themes.!error.id.exists'] = "Le thème sélectionné n'existe pas.";
$lang['Themes.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['Themes.!error.company_id.isset'] = "Seulement les thèmes reliés aux compagnies peuvent être effacés.";
$lang['Themes.!error.company_id.set'] = "Seuls les thèmes spécifiques à l'entreprise peuvent être mis à jour.";
$lang['Themes.!error.name.empty'] = "Veuillez entrer un nom pour le thème.";
$lang['Themes.!error.name.length'] = "Le nom du thème ne peut excéder 64 caractères en longueur.";
$lang['Themes.!error.colors.exist'] = "S'il vous plaît entrer un code hexadécimal à 6 caractères valide pour chaque couleur.";
$lang['Themes.!error.type.format'] = "Le type de thème donné est invalide.";
$lang['Themes.type.admin'] = "Personnel";
$lang['Themes.type.client'] = "Client";
?>