<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Users.!error.username.empty'] = "Veuillez entrer un nom d'utilisateur.";
$lang['Users.!error.username.unique'] = "Ce nom d'utilisateur est déjà utilisé";
$lang['Users.!error.current_password.matches'] = "Mot de passe invalide.";
$lang['Users.!error.new_password.format'] = "Veuillez entrer un mot de passe ayant au minimum 6 caractères.";
$lang['Users.!error.new_password.matches'] = "Les mots de passe ne concordent pas.";
$lang['Users.!error.two_factor_mode.format'] = "Mode d'identification a deux facteurs invalide.";
$lang['Users.!error.username.auth'] = "Aucun résultat trouvé pour cette combinaison utilisateur / mot de passe.";
$lang['Users.!error.otp.auth'] = "Le mot de passe unique entré est invalide.";
$lang['Users.!error.user_id.exists'] = "ID d'utilisateur invalide.";
$lang['Users.!error.username.attempts'] = "Trop de tentative de connexion détectées.";
$lang['Users.!error.clients.exist'] = "L'utilisateur ne peut pas être supprimé, car il y a au moins un client attribué à l'utilisateur.";
$lang['Users.!error.two_factor_key.format'] = "Clé à deux facteurs invalide.";
$lang['Users.!error.username.company'] = "Vous n'êtes pas autorisé à vous connecter à cet emplacement.";
?>