<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CmsManagePlugin.!success.plugin_updated'] = "Le portail a été mis à jour avec succès.";
$lang['CmsManagePlugin.index.page_title'] = "Portail > Gérer";
$lang['CmsManagePlugin.index.boxtitle_portal'] = "Portail";
$lang['CmsManagePlugin.index.field_title'] = "Titre de la page d'index";
$lang['CmsManagePlugin.index.field_tags'] = "Étiquettes disponibles";
$lang['CmsManagePlugin.index.field_content'] = "Contenu de la page d'index";
$lang['CmsManagePlugin.index.field_submit'] = "Mettre à jour la page";
?>