<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CmsPages.!error.uri.empty'] = "Veuillez entrer le chemin complet de la page.";
$lang['CmsPages.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['CmsPages.!error.title.empty'] = "Veuillez entrer un titre de page.";
?>