<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Signup.index.header_login_or_signup'] = "S'inscrire ou se connecter";
$lang['Signup.index.link_resetpassword'] = "Réinitialiser mon mot de passe";
$lang['Signup.index.login_or_signup_note'] = "Si vous avez déjà un compte chez nous, veuillez vous connecter pour ajouter cette commande à votre compte existant.";
$lang['Signup.index.login_note'] = "Vous aurez la possibilité de confirmer votre commande après vous être connecté.";
$lang['Signup.index.signup_note'] = "Vous aurez la possibilité de confirmer votre commande après avoir créé un compte.";
$lang['Signup.index.client_note'] = "Cette commande sera ajoutée au compte suivant.";
$lang['Signup.index.logout_btn'] = "Se déconnecter";
$lang['Signup.index.continue_btn'] = "Continuer vos achats";
$lang['Signup.index.checkout_btn'] = "Commander & Payer";
$lang['Signup.index.configure_btn'] = "Continuer";
$lang['Signup.index.field_agree_tos'] = "J'ai lu et accepté les <a href=\"%1\$s\" target=\"_blank\"> conditions d'utilisation </a>."; // %1$s is the URI to the terms and conditions
$lang['Signup.index.heading_client'] = "Informations client";
$lang['Signup.index.heading_contact'] = "Informations de contact";
$lang['Signup.index.heading_billing'] = "Informations de facturation";
$lang['Signup.index.heading_authentication'] = "Authentification";
$lang['Signup.index.heading_settings'] = "Autres paramètres";
?>