<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Summary.index.have_coupon'] = "Utiliser un coupon";
$lang['Summary.index.coupon'] = "Coupon";
$lang['Summary.index.coupon_btn'] = "Échanger";
$lang['Summary.index.heading_summary'] = "Récapitulatif de la commande";
$lang['Summary.index.summary_note'] = "Toutes les taxes applicables seront calculées après votre inscription ou connexion.";
$lang['Summary.index.table_description'] = "Description";
$lang['Summary.index.table_price'] = "Prix unitaire";
$lang['Summary.index.empty_cart'] = "Vider le panier";
$lang['Summary.index.heading_paymethods'] = "Mode de paiement";
$lang['Summary.index.paymethods_note'] = "Veuillez sélectionner votre mode de paiement souhaité.";
?>