<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Thesslstore.expiration_reminder_name'] = "Rappel d'expiration de certificat SSL";
$lang['AdminCompanyEmails.templates.Thesslstore.expiration_reminder_desc'] = "Avis envoyé avant 30 jours d'expiration du certificat.";
?>