<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TheSSLStorePlugin.name'] = "Plugin TheSSLStore";
$lang['TheSSLStorePlugin.getCronTasks.tss_order_sync_name'] = "Synchronisation de commande SSL";
$lang['TheSSLStorePlugin.getCronTasks.tss_order_sync_desc'] = "Ce cron est requis pour synchroniser les mises à jour de l'état de la commande et de l'expiration du certificat à partir du magasin SSL.";
$lang['TheSSLStorePlugin.getCronTasks.tss_expiration_reminder_name'] = "Rappel d'expiration de certificat SSL";
$lang['TheSSLStorePlugin.getCronTasks.tss_expiration_reminder_desc'] = "Un rappel sera envoyé 30 jours avant la date d'expiration du certificat.";
?>