<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DefaultInvoice.name'] = "Défaut";
$lang['DefaultInvoice.page_of'] = "Page %1\$s de %2\$s"; // %1$s is the current page number, %2$s is the total number of pages
$lang['DefaultInvoice.terms_heading'] = "Termes";
$lang['DefaultInvoice.type_active'] = "FACTURE";
$lang['DefaultInvoice.type_draft'] = "FACTURE - BROUILLON";
$lang['DefaultInvoice.type_void'] = "FACTURE - ANNULÉ";
$lang['DefaultInvoice.invoice_id_code'] = "Numéro du facture:";
$lang['DefaultInvoice.client_id_code'] = "Numéro de client:";
$lang['DefaultInvoice.tax_id'] = "Taxe ID/VATIN:";
$lang['DefaultInvoice.date_billed'] = "Date de facturation:";
$lang['DefaultInvoice.date_due'] = "Date d'échéance:";
$lang['DefaultInvoice.notes_heading'] = "Notes";
$lang['DefaultInvoice.subtotal_heading'] = "Sous-total";
$lang['DefaultInvoice.tax_heading'] = "%1\$s (%2\$s%%)"; // %1$s is the tax name, %2$s is the tax rate, %% escapes the percent (%) sign so it can be displayed
$lang['DefaultInvoice.total_heading'] = "Total";
$lang['DefaultInvoice.lines_description'] = "Description";
$lang['DefaultInvoice.lines_quantity'] = "Quantité";
$lang['DefaultInvoice.lines_unit_price'] = "Prix Unitaire";
$lang['DefaultInvoice.lines_cost'] = "Coût";
$lang['DefaultInvoice.watermark_paid'] = "PAYÉ";
$lang['DefaultInvoice.client_tax_id'] = "ID de taxe client /TVA:";
$lang['DefaultInvoice.type_proforma'] = "FACTURE PRO FORMA";
$lang['DefaultInvoice.payments_heading'] = "Paiements";
$lang['DefaultInvoice.payments_applied_date'] = "Date appliqué";
$lang['DefaultInvoice.payments_type_name'] = "Type";
$lang['DefaultInvoice.payments_transaction_id'] = "Numéro de transaction";
$lang['DefaultInvoice.payments_applied_amount'] = "Montant appliqué";
$lang['DefaultInvoice.balance_heading'] = "Balance";
$lang['DefaultInvoice.proforma_id_code'] = "Numéro de Pro Forma";
$lang['DefaultInvoice.draft_id_code'] = "Numéro de brouillon:";
?>