<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Coingate.name'] = "CoinGate.com";
$lang['Coingate.app_id'] = "ID APP";
$lang['Coingate.api_key'] = "Clé API";
$lang['Coingate.api_secret'] = "Secret API";
$lang['Coingate.coingate_environment'] = "Environnement CoinGate";
$lang['Coingate.environment.sandbox'] = "sandbox";
$lang['Coingate.environment.live'] = "En direct";
$lang['Coingate.receive_currency'] = "Devise de paiement";
$lang['Coingate.receive_currency_note'] = "Devise que vous souhaitez recevoir lorsque vous effectuez un retrait sur CoinGate. Veuillez noter que si vous choisissez EUR ou USD, il vous sera demandé de vérifier votre activité avant d'effectuer un retrait chez CoinGate.";
$lang['Coingate.environment_note'] = "Activer \"sandbox\" pour tester sur sandbox.coingate.com. Veuillez noter que pour le mode sandbox, vous devez générer des informations d'identification d'API distinctes sur sandbox.coingate.com. Les informations d'identification d'API générées sur coingate.com ne fonctionneront pas en mode sandbox.";
$lang['Coingate.buildprocess.submit'] = "CoinGate.com";
$lang['Coingate.receive_currency.usd'] = "Dollars US \$";
$lang['Coingate.receive_currency.btc'] = "Bitcoin ?";
$lang['Coingate.receive_currency.eur'] = "Euros €";
$lang['Coingate.!error.app_id.empty'] = "L'ID APP ne peut pas être vide.";
$lang['Coingate.!error.api_key.empty'] = "La clé API ne peut pas être vide";
$lang['Coingate.!error.api_secret.empty'] = "Le secret de l'API ne peut pas être vide";
$lang['Coingate.!error.payment.invalid'] = "La transaction n'est pas valide et n'a pas pu être traitée.";
$lang['Coingate.!error.payment.canceled'] = "La transaction est annulée et n'a pas pu être traitée.";
$lang['Coingate.!error.payment.expired'] = "La transaction a expiré et n'a pas pu être traitée.";
$lang['Coingate.!error.failed.response'] = "La transaction n'a pas pu être traitée.";
?>