<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.status_updated'] = "Les commandes sélectionnées ont été mises à jour avec succès.";
$lang['AdminMain.!success.settings_updated'] = "Vos paramètres de commande ont été mis à jour avec succès.";
$lang['AdminMain.index.boxtitle_order'] = "Commandes";
$lang['AdminMain.index.no_results'] = "Il n'y a pas de commandes de ce type.";
$lang['AdminMain.index.category_accepted'] = "Accepté";
$lang['AdminMain.index.category_fraud'] = "Fraude";
$lang['AdminMain.index.heading_order_number'] = "Commande #";
$lang['AdminMain.index.heading_client_id_code'] = "ID Client";
$lang['AdminMain.index.heading_invoice_id_code'] = "Facture #";
$lang['AdminMain.index.heading_total'] = "Total";
$lang['AdminMain.index.heading_paid'] = "Payé";
$lang['AdminMain.index.heading_date_added'] = "Date commandé";
$lang['AdminMain.index.field_ordersubmit'] = "Mise à jour des commandes";
$lang['AdminMain.orderinfo.fraudreport_heading'] = "Rapport de fraude";
$lang['AdminMain.orderinfo.fraudreport_heading_key'] = "Clé";
$lang['AdminMain.orderinfo.fraudreport_heading_value'] = "Valeur";
$lang['AdminMain.orderinfo.applied_heading'] = "Transactions";
$lang['AdminMain.orderinfo.applied_heading_paymenttype'] = "Type de paiement";
$lang['AdminMain.orderinfo.applied_heading_amount'] = "Montant";
$lang['AdminMain.orderinfo.applied_heading_applied'] = "Appliqué";
$lang['AdminMain.orderinfo.applied_heading_appliedon'] = "Appliqué le";
$lang['AdminMain.orderinfo.applied_heading_options'] = "Options";
$lang['AdminMain.orderinfo.applied_option_edit'] = "Editer";
$lang['AdminMain.orderinfo.applied_no_results'] = "Il n'y a pas de transactions appliquées à cet commande.";
$lang['AdminMain.orderinfo.services_heading'] = "Services";
$lang['AdminMain.orderinfo.services_heading_package'] = "Ensemble";
$lang['AdminMain.orderinfo.services_heading_label'] = "Étiquette";
$lang['AdminMain.orderinfo.services_heading_term'] = "Termes";
$lang['AdminMain.orderinfo.services_heading_dateadded'] = "Date d'ajout";
$lang['AdminMain.orderinfo.services_heading_daterenews'] = "Date de renouvellement";
$lang['AdminMain.orderinfo.services_heading_options'] = "Options";
$lang['AdminMain.orderinfo.services_option_manage'] = "Gérer";
$lang['AdminMain.orderinfo.services_text_never'] = "Jamais";
$lang['AdminMain.orderinfo.services_no_results'] = "Il n'y a pas de services dans cette commande.";
$lang['AdminMain.settings.heading_notifications'] = "Notifications de commande";
$lang['AdminMain.settings.field_email_notice'] = "Courriel";
$lang['AdminMain.settings.field_email_notice_never'] = "Ne pas envoyer";
$lang['AdminMain.settings.field_email_notice_manual'] = "Envoyer seulement si une approbation manuelle est requise";
$lang['AdminMain.settings.field_email_notice_always'] = "Toujours envoyer";
$lang['AdminMain.settings.field_mobile_notice'] = "Portable";
$lang['AdminMain.settings.field_mobile_notice_never'] = "Ne pas envoyer";
$lang['AdminMain.settings.field_mobile_notice_manual'] = "Envoyer seulement si une approbation manuelle est requise";
$lang['AdminMain.settings.field_mobile_notice_always'] = "Toujours envoyer";
$lang['AdminMain.settings.submit_settings'] = "Mettre à jour les paramètres";
$lang['AdminMain.settings.submit_cancel'] = "Retour à la liste des commandes";
$lang['AdminMain.index.category_canceled'] = "Annulé";
$lang['AdminMain.index.field_markas'] = "Marquer comme:";
$lang['AdminMain.index.text_location'] = "Localisation";
$lang['AdminMain.index.category_pending'] = "En revue";
?>