<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Order.received_name'] = "Commandes reçues";
$lang['AdminCompanyEmails.templates.Order.received_desc'] = "Message envoyé lorsqu'une commande est reçue.";
$lang['AdminCompanyEmails.templates.Order.received_mobile_name'] = "Commande reçue (Mobile)";
$lang['AdminCompanyEmails.templates.Order.received_mobile_desc'] = "Avis envoyé quand une commande est reçue et destinée pour les appareils mobiles.";
?>