<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminForms.!success.settings_saved'] = "Les paramètres ont été sauvegardés avec succès";
$lang['AdminForms.!success.form_added'] = "Le formulaire a été ajouté avec succès.";
$lang['AdminForms.!success.form_delete'] = "Le formulaire a été effacé avec succès.";
$lang['AdminForms.!success.form_edited'] = "Le formulaire a été mis à jour avec succès.";
$lang['AdminForms.index.page_title'] = "Système de commande";
$lang['AdminForms.settings.page_title'] = "Système de commande";
$lang['AdminForms.add.page_title'] = "Système de commande";
$lang['AdminForms.edit.page_title'] = "Système d'achat";
$lang['AdminForms.index.boxtitle_order'] = "Système de commande";
$lang['AdminForms.index.tab_forms'] = "Formulaires de commande";
$lang['AdminForms.index.tab_settings'] = "Paramètres";
$lang['AdminForms.index.order_form_add'] = "Ajouter un formulaire de commande";
$lang['AdminForms.index.order_forms_no_results'] = "Il n'y a pas de formulaire de commande à ce moment.";
$lang['AdminForms.index.heading_name'] = "Nom";
$lang['AdminForms.index.heading_label'] = "Étiquette";
$lang['AdminForms.index.heading_template'] = "Modèle";
$lang['AdminForms.index.heading_type'] = "Type";
$lang['AdminForms.index.heading_date_added'] = "Date ajouté";
$lang['AdminForms.index.heading_status'] = "Statut";
$lang['AdminForms.index.heading_options'] = "Options";
$lang['AdminForms.index.option_edit'] = "Modifier";
$lang['AdminForms.index.option_delete'] = "Effacer";
$lang['AdminForms.index.text_confirm_delete'] = "Vraiment effacer ce bon de commande?";
$lang['AdminForms.index.field_status_active'] = "Actif";
$lang['AdminForms.index.field_status_inactive'] = "Inactif";
$lang['AdminForms.add.boxtitle_order'] = "Système de commandes - Ajouter un formulaire";
$lang['AdminForms.add.field_name'] = "Nom";
$lang['AdminForms.add.field_label'] = "Étiquette";
$lang['AdminForms.add.field_type'] = "Type";
$lang['AdminForms.add.field_allow_coupons'] = "Permettre les coupons";
$lang['AdminForms.add.field_manual_review'] = "Exiger une révision manuelle et une approbation de toutes les commandes";
$lang['AdminForms.add.field_require_ssl'] = "Forcer les connections sécures (HTTPS)";
$lang['AdminForms.add.field_require_captcha'] = "Exiger une vérification humaine pour toutes les inscriptions.";
$lang['AdminForms.add.field_require_tos'] = "Acceptation des conditions de service requis";
$lang['AdminForms.add.field_tos_url'] = "URL des conditions de service";
$lang['AdminForms.add.field_status'] = "Statut";
$lang['AdminForms.add.field_status_active'] = "Actif";
$lang['AdminForms.add.field_status_inactive'] = "Inactif";
$lang['AdminForms.add.field_template'] = "Modèle";
$lang['AdminForms.add.field_client_group_id'] = "Groupe client par défaut";
$lang['AdminForms.add.tooltip_client_group'] = "Le groupe nouvel abonné va être assigné par défaut au client.";
$lang['AdminForms.add.field_addsubmit'] = "Ajouter le formulaire";
$lang['AdminForms.add.heading_basic'] = "Base";
$lang['AdminForms.edit.boxtitle_order'] = "Système de commande - Modification de formulaire";
$lang['AdminForms.edit.field_name'] = "Nom";
$lang['AdminForms.edit.field_label'] = "Étiquette";
$lang['AdminForms.edit.field_type'] = "Type";
$lang['AdminForms.edit.field_allow_coupons'] = "Permettre les coupons";
$lang['AdminForms.edit.field_manual_review'] = "Exiger une révision et approbation maneulle de toutes les commandes";
$lang['AdminForms.edit.field_require_ssl'] = "Forcer les connexions sécures (HTTPS)";
$lang['AdminForms.edit.field_require_tos'] = "Exiger l'acceptation des termes de services";
$lang['AdminForms.edit.field_require_captcha'] = "Requiert un défi de validation humaine pour tous les nouveaux comptes.";
$lang['AdminForms.edit.field_tos_url'] = "Adresse des Termes de services";
$lang['AdminForms.edit.field_status'] = "Statut";
$lang['AdminForms.edit.field_status_active'] = "Actif";
$lang['AdminForms.edit.field_status_inactive'] = "Inactif";
$lang['AdminForms.edit.field_template'] = "Gabarit";
$lang['AdminForms.edit.field_client_group_id'] = "Groupe client par défaut";
$lang['AdminForms.edit.tooltip_client_group'] = "Les nouvelles inscriptions du groupe de clients par défaut à partir de ce formulaire seront affectées a";
$lang['AdminForms.edit.field_addsubmit'] = "Éditer le formulaire";
$lang['AdminForms.edit.heading_basic'] = "De base";
$lang['AdminForms.meta.text_membergroups'] = "Groupes assignés";
$lang['AdminForms.meta.text_availablegroups'] = "Groupes disponibles";
$lang['AdminForms.meta.heading_package_groups'] = "Groupes d'ensembles";
$lang['AdminForms.meta.heading_package_group'] = "Groupe d'ensemble";
$lang['AdminForms.meta.heading_currencies'] = "Devises";
$lang['AdminForms.meta.heading_gateways'] = "Passerelles";
$lang['AdminForms.settings.boxtitle_order'] = "Système de commande";
$lang['AdminForms.settings.basic_heading'] = "Options de base";
$lang['AdminForms.settings.field_default_form'] = "Formulaire de commande par défaut";
$lang['AdminForms.settings.field_captcha'] = "Vérification humaine";
$lang['AdminForms.settings.field_captcha_none'] = "Aucun";
$lang['AdminForms.settings.field_captcha_recaptcha'] = "reCaptcha";
$lang['AdminForms.settings.antifraud_heading'] = "Anti-Fraude";
$lang['AdminForms.settings.field_antifraud'] = "Type";
$lang['AdminForms.settings.field_antifraud.none'] = "Aucun";
$lang['AdminForms.settings.field_save'] = "Enregistrer les paramètres";
$lang['AdminForms.add.template_preview'] = "Prévisualiser";
$lang['AdminForms.edit.template_preview'] = "Prévisualiser";
$lang['AdminForms.add.field_description'] = "Description";
$lang['AdminForms.add.field_visibility'] = "Visibilité";
$lang['AdminForms.edit.field_description'] = "Description";
$lang['AdminForms.edit.field_visibility'] = "Visibilité";
$lang['AdminForms.settings.field_recaptcha_shared_key'] = "Clé partagée reCaptcha";
$lang['AdminForms.settings.default_form.none'] = "Aucun - Afficher la liste";
$lang['AdminForms.settings.field_recaptcha_pub_key'] = "Clé reCaptcha du site";
$lang['AdminForms.settings.field_antifraud_frequency'] = "Fréquence anti-fraude";
$lang['AdminForms.settings.field_antifraud_frequency.always'] = "Exécuter des contrôles de fraude pour toutes les commandes et les inscriptions des clients";
$lang['AdminForms.settings.field_antifraud_frequency.new'] = "Exécuter des contrôles de fraude pour les inscriptions des clients uniquement";
$lang['AdminForms.meta.text_drag_and_drop'] = "Glisser et déposez les groupes ici";
$lang['AdminForms.meta.tooltip_text_membergroups'] = "Les groupes de forfait apparaîtront sur le formulaire de commande dans l'ordre indiqué ici.";
$lang['AdminForms.settings.embed_code_heading'] = "Code intégré";
$lang['AdminForms.settings.field_tags'] = "Mots clés";
$lang['AdminForms.settings.field_embed_code'] = "Formulaire de commande code intégré";
$lang['AdminForms.settings.marketing_heading'] = "Marketing";
$lang['AdminForms.settings.field_marketing_default'] = "Marketing par e-mail du client";
$lang['AdminForms.settings.field_marketing_default.true'] = "L'option de recevoir du marketing par email sera sélectionnée par défaut


";
$lang['AdminForms.settings.field_marketing_default.false'] = "L'option de recevoir du marketing par e-mail doit être sélectionnée par le client.";
$lang['AdminForms.settings.tooltip_marketing_default_true'] = "Cette option sera affichée sur la page d'inscription du client, sélectionné pour les inclure dans le marketing par e-mail.";
$lang['AdminForms.settings.tooltip_marketing_default_false'] = "Cette option sera affichée sur la page d'inscription du client, désélectionnée pour les exclure du marketing par e-mail.";
?>