<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.!success.coupon_applied'] = "Le coupon a été appliquée avec succès.";
$lang['Cart.!success.item_removed'] = "Cet item a été retiré de votre panier.";
$lang['Cart.!success.all_items_removed'] = "Tous les items ont été retirés de votre panier d'achat.";
$lang['Cart.!error.coupon_applied'] = "Le coupon n'as pu être appliqué.";
$lang['Cart.index.quantity'] = "%1\$s @"; // %1\$s is the quantity value being ordered
$lang['Cart.index.totals.discount'] = "Rabais:";
$lang['Cart.index.totals.subtotal'] = "Sous-total:";
$lang['Cart.index.totals.total'] = "Montant dû:";
?>