<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Checkout.!error.invalid_agree_tos'] = "Vous devez confirmer votre acceptation des termes et conditions.";
$lang['Checkout.!error.no_payment_info'] = "Vous devez sélectionner une méthode de paiement pour continuer.";
$lang['Checkout.index.description_invoice'] = "Facture #%1\$s"; // %1$s is the invoice number
$lang['Checkout.setcontactview.text_none'] = "Aucun";
$lang['Checkout.getpaymentaccounts.paymentaccount_cc'] = "Comptes de cartes de crédit";
$lang['Checkout.getpaymentaccounts.paymentaccount_ach'] = "Comptes ACH";
$lang['Checkout.getpaymentaccounts.account_name'] = "%1\$s %2\$s - %3\$s x%4\$s"; // %1$s is the account first name, %2$s is the account last name, %3$s is the account type (card type or bank account type), %4$s is the last 4 of the account
$lang['Checkout.index.field_agree_tos'] = "J'ai lu et j'accepte les <a href=\"%1\$s\" target=\"_blank\"> termes et conditions</a>"; // %1$s is the URI to the terms and conditions
$lang['Checkout.index.totals.setup_fee'] = "Frais d'installation:";
$lang['Checkout.index.totals.discount'] = "Rabais:";
$lang['Checkout.index.totals.subtotal'] = "Sous-total:";
$lang['Checkout.index.totals.tax'] = "%1\$s (%2\$s%%):"; // %1$s is the tax name, %2$s is the tax percentage
$lang['Checkout.index.totals.total'] = "Total à payer";
$lang['Checkout.contact_info.field_first_name'] = "Prénom";
$lang['Checkout.contact_info.field_last_name'] = "Nom de famille";
$lang['Checkout.contact_info.field_address1'] = "Adresse 1";
$lang['Checkout.contact_info.field_address2'] = "Adresse 2";
$lang['Checkout.contact_info.field_city'] = "Ville";
$lang['Checkout.contact_info.field_country'] = "Pays";
$lang['Checkout.contact_info.field_state'] = "État";
$lang['Checkout.contact_info.field_zip'] = "Code postal / ZIP";
$lang['Checkout.contact_info.field_email'] = "Courriel";
$lang['Checkout.cc_info.field_number'] = "Nombre";
$lang['Checkout.cc_info.field_security'] = "Code de sécurité";
$lang['Checkout.cc_info.field_expiration'] = "Date d'expiration";
$lang['Checkout.cc_info.field_savedetails'] = "Sauvegarder les détails de paiement";
$lang['Checkout.cc_info.tooltip_savedetails'] = "Les détails de paiement sauvegardés peuvent être utilisés dans le futur sans avoir a entrer vos informations à nouveau.";
$lang['Checkout.cc_info.tooltip_code'] = "Le code de sécurité à 3 chiffres ou 4, trouvé habituellement sur le dos de la carte.";
$lang['Checkout.ach_info.field_type'] = "Type
";
$lang['Checkout.ach_info.field_accountnum'] = "Numéro de compte";
$lang['Checkout.ach_info.field_routingnum'] = "Numéro de routage";
$lang['Checkout.ach_info.field_savedetails'] = "Enregistrer les détails de paiement";
$lang['Checkout.ach_info.tooltip_savedetails'] = "Les détails de paiement pré-enregistrés peuvent être utilisés pour effectuer le paiement à l'avenir sans avoir à entrer dans les détails à chaque fois.";
$lang['Checkout.complete.order_number'] = "Commande #%1\$s"; // %1$s is the order number
$lang['Checkout.complete.complete_description'] = "Merci pour votre commande! Elle est maintenant complétée.";
$lang['Checkout.complete.almost_complete_description'] = "Votre commande a été reçue, en attente de votre paiement ci-bas.";
$lang['Checkout.complete.table_description'] = "#%1\$s %2\$s";
$lang['Checkout.complete.table_qty'] = "Quantité";
$lang['Checkout.complete.table_price'] = "Prix";
$lang['Checkout.complete.quantity'] = "%1\$s @"; // %1\$s is the quantity value being ordered
$lang['Checkout.complete.totals.subtotal'] = "Sous-total:";
$lang['Checkout.complete.totals.tax'] = "%1\$s (%2\$s%%):"; // %1$s is the tax name, %2$s is the tax percentage
$lang['Checkout.complete.totals.total'] = "Total dû:";
$lang['Checkout.complete.totals.total_paid'] = "Total payé:";
$lang['Checkout.index.totals.credit'] = "Crédit:";
$lang['Checkout.index.totals.paid'] = "Payé:";
$lang['Checkout.!error.not_client_owner'] = "Vous devez être connecté en tant que client propriétaire afin de continuer.";
?>