<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.!error.invalid_pricing_id'] = "L'ensemble fourni n'as pas été trouvé.";
$lang['Config.!error.invalid_module'] = "L'ensemble est actuellement indisponible.";
$lang['Config.index.package_price'] = "%1\$s @ %2\$s"; // %1$s is the term, %2$s is the price
$lang['Config.index.field_default_addon'] = "Aucun";
$lang['Config.index.field_addon_label'] = "%1\$s (%2\$s @ %3\$s)"; // %1$s is the addon on name, %2$s is the term, %3$s is the price
?>