<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderOrders.getstatuses.accepted'] = "Accepté";
$lang['OrderOrders.getstatuses.fraud'] = "Fraude";
$lang['OrderOrders.getstatuses.canceled'] = "Annulé";
$lang['OrderOrders.getstatuses.pending'] = "En cours de révision";
?>