<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Signup.!error.captcha.invalid'] = "Le captcha entré n'est pas valide. S'il vous plaît essayez de nouveau.";
$lang['Signup.index.field_taxid'] = "Taxe ID/VATIN";
$lang['Signup.index.field_firstname'] = "Prénom";
$lang['Signup.index.field_lastname'] = "Nom de famille";
$lang['Signup.index.field_company'] = "Compagnie / Organisation";
$lang['Signup.index.field_address1'] = "Adresse 1";
$lang['Signup.index.field_address2'] = "Adresse - Ligne 2";
$lang['Signup.index.field_city'] = "Ville";
$lang['Signup.index.field_state'] = "État/Province";
$lang['Signup.index.field_zip'] = "Code postal / ZIP";
$lang['Signup.index.field_country'] = "Pays";
$lang['Signup.index.field_phone'] = "Téléphone";
$lang['Signup.index.field_fax'] = "Fax";
$lang['Signup.index.field_email'] = "Courriel";
$lang['Signup.index.field_username_type_email'] = "Utiliser l'adresse courriel comme nom d'utilisateur";
$lang['Signup.index.field_username_type_username'] = "Spécifiez un nom d'utilisateur";
$lang['Signup.index.field_action_continue'] = "Continuer comme %1\$s %2\$s"; // %1$s is the first name of the client, %2$s is the last name of the client
$lang['Signup.index.field_action_login'] = "Connexion";
$lang['Signup.index.field_action_signup'] = "Créer un compte";
$lang['Signup.index.field_username'] = "Nom d'utilisateur";
$lang['Signup.index.field_password'] = "Mot de passe";
$lang['Signup.index.field_newpassword'] = "Mot de passe";
$lang['Signup.index.field_confirmpassword'] = "Confirmer le mot de passe";
$lang['Signup.index.login_btn'] = "Connexion";
$lang['Signup.index.continue_btn'] = "Aller à la caisse";
$lang['Signup.index.signup_btn'] = "Créer un compte";
$lang['Signup.!error.not_client_owner'] = "Vous devez être connectés avec un compte client propriétaire pour pouvoir continuer.";
$lang['Signup.index.field_title'] = "Titre";
$lang['Signup.index.field_receive_email_marketing'] = "Je souhaite recevoir des e-mails concernant les nouveaux produits, services et offres.";
?>