<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Summary.index.totals.discount'] = "Rabais";
$lang['Summary.index.totals.subtotal'] = "Sous-total:";
$lang['Summary.index.totals.total'] = "Total à payer:";
$lang['Summary.index.price'] = "@ %1\$s"; // %1$s is the price per term
?>