<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Hubtel.name'] = "Hubtel";
$lang['Hubtel.client_id'] = "ID client";
$lang['Hubtel.client_secret'] = "Secret du client";
$lang['Hubtel.buildprocess.submit'] = "Payer avec Hubtel";
$lang['Hubtel.!error.client_id.valid'] = "Vous devez entrer un ID Client valide.";
$lang['Hubtel.!error.client_secret.valid'] = "Vous devez entrer un secret client valide.";
?>