<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['QuickbooksInvoice.name'] = "Quickbooks";
$lang['QuickbooksInvoice.page_of'] = "Page %1\$s de %2\$s"; // %1$s is the current page number, %2$s is the total number of pages
$lang['QuickbooksInvoice.terms_heading'] = "Termes";
$lang['QuickbooksInvoice.type_active'] = "FACTURE";
$lang['QuickbooksInvoice.type_draft'] = "FACTURE - BROUILLON";
$lang['QuickbooksInvoice.type_void'] = "FACTURE - ANNULÉE";
$lang['QuickbooksInvoice.invoice_id_code'] = "Numéro de facture";
$lang['QuickbooksInvoice.client_id_code'] = "Client Numéro";
$lang['QuickbooksInvoice.date_billed'] = "Date";
$lang['QuickbooksInvoice.date_due'] = "Date due";
$lang['QuickbooksInvoice.notes_heading'] = "Notes";
$lang['QuickbooksInvoice.subtotal_heading'] = "Sous-total";
$lang['QuickbooksInvoice.tax_heading'] = "%1\$s (%2\$s%%)"; // %1$s is the tax name, %2$s is the tax rate, %% escapes the percent (%) sign so it can be displayed
$lang['QuickbooksInvoice.total_heading'] = "Total";
$lang['QuickbooksInvoice.lines_description'] = "Description";
$lang['QuickbooksInvoice.lines_quantity'] = "Quantité";
$lang['QuickbooksInvoice.lines_unit_price'] = "Prix unitaire";
$lang['QuickbooksInvoice.lines_cost'] = "Coût";
$lang['QuickbooksInvoice.address_heading'] = "Facture pour";
$lang['QuickbooksInvoice.address_city_state'] = "%1\$s, %2\$s %3\$s %4\$s"; // %1$s is the city, %2$s is the state code, %3$s is the zip/postal code, %4$s is the country code
$lang['QuickbooksInvoice.tax_id'] = "Taxe ID/VATIN: %1\$s"; // %1$s is the tax ID/VATIN
$lang['QuickbooksInvoice.watermark_paid'] = "PAYÉ";
$lang['QuickbooksInvoice.client_tax_id'] = "ID de taxe du client/VATIN: %1\$s"; // %1$s is the tax ID/VATIN
$lang['QuickbooksInvoice.type_proforma'] = "FACTURE PRO FORMA";
$lang['QuickbooksInvoice.payments_heading'] = "Paiements";
$lang['QuickbooksInvoice.payments_applied_date'] = "Date appliqué";
$lang['QuickbooksInvoice.payments_type_name'] = "Type";
$lang['QuickbooksInvoice.payments_transaction_id'] = "Numéro de transaction";
$lang['QuickbooksInvoice.payments_applied_amount'] = "Montant appliqué";
$lang['QuickbooksInvoice.balance_heading'] = "Balance ";
$lang['QuickbooksInvoice.proforma_id_code'] = "Pro Forma Non.";
$lang['QuickbooksInvoice.draft_id_code'] = "Brouillon num.";
?>