<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Tcadmin.name'] = "Tcadmin";
$lang['Tcadmin.module_row'] = "Serveur";
$lang['Tcadmin.module_row_plural'] = "Serveurs";
$lang['Tcadmin.module_group'] = "Groupe de serveurs";
$lang['Tcadmin.add_module_row'] = "Ajouter un serveur";
$lang['Tcadmin.add_module_group'] = "Ajouter un groupe de serveurs";
$lang['Tcadmin.manage.module_rows_title'] = "Serveurs";
$lang['Tcadmin.manage.module_groups_title'] = "Groupes de serveurs";
$lang['Tcadmin.manage.module_rows_heading.name'] = "Titre du serveur";
$lang['Tcadmin.manage.module_rows_heading.hostname'] = "Nom d'hôte";
$lang['Tcadmin.manage.module_rows_heading.port'] = "Port";
$lang['Tcadmin.manage.module_rows_heading.options'] = "Options";
$lang['Tcadmin.manage.module_groups_heading.name'] = "Nom de groupe";
$lang['Tcadmin.manage.module_groups_heading.servers'] = "Nombre de serveurs";
$lang['Tcadmin.manage.module_groups_heading.options'] = "Options";
$lang['Tcadmin.manage.module_rows.edit'] = "Modifier";
$lang['Tcadmin.manage.module_groups.edit'] = "Modifier";
$lang['Tcadmin.manage.module_rows.delete'] = "Supprimer";
$lang['Tcadmin.manage.module_groups.delete'] = "Supprimer";
$lang['Tcadmin.manage.module_rows.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer ce serveur?";
$lang['Tcadmin.manage.module_groups.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer ce groupe de serveurs?";
$lang['Tcadmin.manage.module_rows_no_results'] = "Il n'y a pas de serveurs.";
$lang['Tcadmin.manage.module_groups_no_results'] = "Il n'y a pas de groupes de serveurs.";
$lang['Tcadmin.order_options.first'] = "Premier serveur non complet";
$lang['Tcadmin.add_row.box_title'] = "Ajouter un serveur Tcadmin";
$lang['Tcadmin.add_row.basic_title'] = "Paramètres de base";
$lang['Tcadmin.add_row.add_btn'] = "Ajouter un serveur";
$lang['Tcadmin.edit_row.box_title'] = "Modifier le serveur Tcadmin";
$lang['Tcadmin.edit_row.basic_title'] = "Paramètres de base";
$lang['Tcadmin.edit_row.add_btn'] = "Modifier le serveur";
$lang['Tcadmin.row_meta.server_name'] = "Étiquette du serveur";
$lang['Tcadmin.row_meta.host_name'] = "Nom d'hôte";
$lang['Tcadmin.row_meta.user_name'] = "Nom d'utilisateur";
$lang['Tcadmin.row_meta.password'] = "Mot de passe";
$lang['Tcadmin.row_meta.port'] = "Port";
$lang['Tcadmin.row_meta.use_ssl'] = "Utiliser SSL lors de la connexion à l'API (recommandé)";
$lang['Tcadmin.row_meta.account_limit'] = "Limite de compte";
$lang['Tcadmin.package_fields.server_type'] = "Type de serveur";
$lang['Tcadmin.package_fields.game_server'] = "Serveur de jeu";
$lang['Tcadmin.package_fields.voice_server'] = "Serveur vocal";
$lang['Tcadmin.package_fields.supported_servers'] = "Serveurs Tcadmin pris en charge";
$lang['Tcadmin.package_fields.yes'] = "Oui";
$lang['Tcadmin.package_fields.no'] = "Non";
$lang['Tcadmin.package_fields.start'] = "Commencer après la création";
$lang['Tcadmin.package_fields.priority'] = "Priorité";
$lang['Tcadmin.package_fields.startup'] = "Démarrage";
$lang['Tcadmin.package_fields.priority.abovenormal'] = "Au-dessus de la normale";
$lang['Tcadmin.package_fields.priority.belownormal'] = "Inférieur à la normale";
$lang['Tcadmin.package_fields.priority.normal'] = "Normal";
$lang['Tcadmin.package_fields.priority.high'] = "Haute";
$lang['Tcadmin.package_fields.priority.idle'] = "Repos";
$lang['Tcadmin.package_fields.priority.realtime'] = "En temps réel";
$lang['Tcadmin.package_fields.startup.automatic'] = "Automatique";
$lang['Tcadmin.package_fields.startup.manual'] = "Manuel";
$lang['Tcadmin.package_fields.startup.disabled'] = "Désactivé";
$lang['Tcadmin.service_field.hostname'] = "Nom d'hôte";
$lang['Tcadmin.service_field.user_name'] = "Nom d'utilisateur Tcadmin";
$lang['Tcadmin.service_field.user_password'] = "Mot de passe Tcadmin";
$lang['Tcadmin.service_field.rcon_password'] = "Mot de passe RCON";
$lang['Tcadmin.service_field.private_password'] = "Mot de passe privé";
$lang['Tcadmin.stored_locally_only'] = "Ce champ sera mis à jour localement uniquement";
$lang['Tcadmin.service_info.hostname'] = "Nom d'hôte";
$lang['Tcadmin.service_info.rcon_password'] = "Mot de passe RCON";
$lang['Tcadmin.service_info.private_password'] = "Mot de passe privé";
$lang['Tcadmin.service_info.username'] = "Nom d'utilisateur";
$lang['Tcadmin.service_info.password'] = "Mot de passe";
$lang['Tcadmin.service_info.server'] = "Serveur";
$lang['Tcadmin.service_info.options'] = "Options";
$lang['Tcadmin.service_info.option_login'] = "Se connecter";
$lang['Tcadmin.!error.server_name_valid'] = "Vous devez entrer une étiquette de serveur.";
$lang['Tcadmin.!error.host_name_valid'] = "Le nom d'hôte semble être invalide.";
$lang['Tcadmin.!error.user_name_valid'] = "Le nom d'utilisateur semble être invalide.";
$lang['Tcadmin.!error.port_valid'] = "Le port semble être invalide.";
$lang['Tcadmin.!error.password_valid'] = "Le mot de passe semble être invalide.";
$lang['Tcadmin.!error.account_limit_valid'] = "La limite de compte semble être invalide.";
$lang['Tcadmin.!error.meta[server_type].valid'] = "Veuillez sélectionner un type de serveur valide.";
$lang['Tcadmin.!error.meta[supported_servers].empty'] = "Veuillez sélectionner l'un des serveurs Tcadmin pris en charge.";
$lang['Tcadmin.!error.meta[start].valid'] = "Veuillez sélectionner une option de départ valide";
$lang['Tcadmin.!error.meta[priority].valid'] = "Veuillez sélectionner une priorité valide";
$lang['Tcadmin.!error.meta[startup].valid'] = "Veuillez sélectionner une option de démarrage valide";
$lang['Tcadmin.!error.api.internal'] = "Une erreur interne s'est produite ou le serveur n'a pas répondu à la demande.";
$lang['Tcadmin.!error.module_row.missing'] = "Une erreur interne est survenue. La ligne de module est indisponible.";
$lang['Tcadmin.!error.hostname.format'] = "Veuillez entrer un nom de domaine valide, par exemple domain.com.";
$lang['Tcadmin.!error.hostname.test'] = "Le nom de domaine ne peut pas commencer par 'test'.";
$lang['Tcadmin.!error.user_name.empty'] = "Le nom d'utilisateur ne peut pas être vide.";
$lang['Tcadmin.!error.user_password.valid'] = "Le mot de passe doit comporter au moins 8 caractères.";
$lang['Tcadmin.!error.rcon_password.valid'] = "Le mot de passe RCON doit comporter au moins 8 caractères";
$lang['Tcadmin.!error.private_password.valid'] = "Le mot de passe privé doit comporter au moins 8 caractères.";
?>