<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.document_uploaded'] = "Le document a été téléversé.";
$lang['AdminMain.!success.document_deleted'] = "Le document a été effacé.";
$lang['AdminMain.index.page_title'] = "Documents";
$lang['AdminMain.add.page_title'] = "Documents > Ajouter";
$lang['AdminMain.index.categorylink_adddocument'] = "Ajouter un document";
$lang['AdminMain.index.boxtitle_client'] = "Client #%1\$s - %2\$s %3\$s";
$lang['AdminMain.index.boxtitle_documents'] = "Documents";
$lang['AdminMain.index.no_results'] = "Il n'y a pas de documents paramétrés pour ce client.";
$lang['AdminMain.index.heading_name'] = "Nom";
$lang['AdminMain.index.heading_description'] = "Description";
$lang['AdminMain.index.heading_date_added'] = "Date d'ajout";
$lang['AdminMain.index.heading_date_options'] = "Options";
$lang['AdminMain.index.option_delete'] = "Effacer";
$lang['AdminMain.index.option_download'] = "Télécharger";
$lang['AdminMain.modal.delete_document'] = "Réellement effacer ce document?";
$lang['AdminMain.add.boxtitle_adddocument'] = "Téléverser le document";
$lang['AdminMain.add.field_name'] = "Nom";
$lang['AdminMain.add.field_document'] = "Document";
$lang['AdminMain.add.field_description'] = "Description";
$lang['AdminMain.add.field_submit'] = "Téléverser un document";
?>