<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientDocumentsFiles.!error.client_id.exists'] = "Ce client n'existe pas.";
$lang['ClientDocumentsFiles.!error.name.valid'] = "Un nom de document est requis.";
$lang['ClientDocumentsFiles.!error.date_added.valid'] = "Une date d'ajout valide est nécessaire.";
?>