<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientDocumentsPlugin.nav_primary_client.main'] = "Documents";
$lang['ClientDocumentsPlugin.action_staff_client.index'] = "Documents";
?>