<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Virtualmin.name'] = "VirtualMin";
$lang['Virtualmin.module_row'] = "Serveur";
$lang['Virtualmin.module_row_plural'] = "Serveurs";
$lang['Virtualmin.module_group'] = "Groupe de serveurs";
$lang['Virtualmin.tab_stats'] = "Statistiques";
$lang['Virtualmin.tab_client_actions'] = "Actions";
$lang['Virtualmin.add_module_row'] = "Ajouter un serveur";
$lang['Virtualmin.add_module_group'] = "Ajouter un groupe de serveurs";
$lang['Virtualmin.manage.module_rows_title'] = "Serveurs";
$lang['Virtualmin.manage.module_groups_title'] = "Groupes de serveurs";
$lang['Virtualmin.manage.module_rows_heading.name'] = "Étiquette du serveur";
$lang['Virtualmin.manage.module_rows_heading.hostname'] = "Nom d'hôte";
$lang['Virtualmin.manage.module_rows_heading.port'] = "Port";
$lang['Virtualmin.manage.module_rows_heading.accounts'] = "Comptes";
$lang['Virtualmin.manage.module_rows_heading.options'] = "Options";
$lang['Virtualmin.manage.module_groups_heading.name'] = "Nom de groupe";
$lang['Virtualmin.manage.module_groups_heading.servers'] = "Nombre de serveurs";
$lang['Virtualmin.manage.module_groups_heading.options'] = "Options";
$lang['Virtualmin.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Virtualmin.manage.module_rows.edit'] = "Modifier";
$lang['Virtualmin.manage.module_groups.edit'] = "Modifier";
$lang['Virtualmin.manage.module_rows.delete'] = "Supprimer";
$lang['Virtualmin.manage.module_groups.delete'] = "Supprimer";
$lang['Virtualmin.manage.module_rows.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer ce serveur?";
$lang['Virtualmin.manage.module_groups.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer ce groupe de serveurs?";
$lang['Virtualmin.manage.module_rows_no_results'] = "Il n'y a pas de serveurs.";
$lang['Virtualmin.manage.module_groups_no_results'] = "Il n'y a pas de groupes de serveurs.";
$lang['Virtualmin.order_options.first'] = "Premier serveur non complet";
$lang['Virtualmin.add_row.box_title'] = "Ajouter un serveur VirtualMin";
$lang['Virtualmin.add_row.basic_title'] = "Paramètres de base";
$lang['Virtualmin.add_row.add_btn'] = "Ajouter un serveur";
$lang['Virtualmin.edit_row.box_title'] = "Modifier le serveur VirtualMin";
$lang['Virtualmin.edit_row.basic_title'] = "Paramètres de base";
$lang['Virtualmin.edit_row.add_btn'] = "Modifier le serveur";
$lang['Virtualmin.row_meta.server_name'] = "Étiquette du serveur";
$lang['Virtualmin.row_meta.host_name'] = "Hostname";
$lang['Virtualmin.row_meta.user_name'] = "Nom d'utilisateur";
$lang['Virtualmin.row_meta.password'] = "Mot de passe";
$lang['Virtualmin.row_meta.port'] = "Port";
$lang['Virtualmin.row_meta.use_ssl'] = "Utiliser SSL lors de la connexion à l'API (recommandé)";
$lang['Virtualmin.row_meta.account_limit'] = "Limite de compte";
$lang['Virtualmin.package_fields.plan'] = "Plan VirtualMin";
$lang['Virtualmin.package_fields.template'] = "Modèle VirtualMin";
$lang['Virtualmin.service_field.domain'] = "Domaine";
$lang['Virtualmin.service_field.username'] = "Nom d'utilisateur";
$lang['Virtualmin.service_field.password'] = "Mot de passe";
$lang['Virtualmin.service_field.confirm_password'] = "Confirmer le mot de passe";
$lang['Virtualmin.tab_client_actions.change_password'] = "Changer le mot de passe";
$lang['Virtualmin.tab_client_actions.field_virtualmin_password'] = "Mot de passe";
$lang['Virtualmin.tab_client_actions.field_virtualmin_confirm_password'] = "Confirmer le mot de passe";
$lang['Virtualmin.tab_client_actions.field_password_submit'] = "Modifier le mot de passe";
$lang['Virtualmin.tab_stats.info_title'] = "Information";
$lang['Virtualmin.tab_stats.info_heading.field'] = "champ";
$lang['Virtualmin.tab_stats.info_heading.value'] = "Valeur";
$lang['Virtualmin.tab_stats.info.disk_used'] = "Disque utilisé";
$lang['Virtualmin.tab_stats.info.databases_size'] = "Taille de la base de données";
$lang['Virtualmin.tab_stats.info.databases_count'] = "Nombre de bases de données";
$lang['Virtualmin.tab_stats.info.maximum_databases'] = "Bases de données maximales";
$lang['Virtualmin.tab_stats.info.maximum_mailboxes'] = "Nombre maximum de boîtes aux lettres";
$lang['Virtualmin.service_info.username'] = "Nom d'utilisateur";
$lang['Virtualmin.service_info.password'] = "Mot de passe";
$lang['Virtualmin.service_info.server'] = "Serveur";
$lang['Virtualmin.service_info.options'] = "Options";
$lang['Virtualmin.service_info.option_login'] = "Se connecter";
$lang['Virtualmin.service_field.tooltip.username'] = "Vous pouvez laisser le nom d'utilisateur vide pour en générer un automatiquement.";
$lang['Virtualmin.service_field.tooltip.password'] = "Vous pouvez laisser le mot de passe vide pour en générer un automatiquement.";
$lang['Virtualmin.!error.server_name_valid'] = "Vous devez entrer une étiquette de serveur.";
$lang['Virtualmin.!error.host_name_valid'] = "Le nom d'hôte semble être invalide.";
$lang['Virtualmin.!error.user_name_valid'] = "Le nom d'utilisateur semble être invalide.";
$lang['Virtualmin.!error.port_valid'] = "Le port semble être invalide.";
$lang['Virtualmin.!error.password_valid'] = "Le mot de passe semble être invalide.";
$lang['Virtualmin.!error.account_limit_valid'] = "Veuillez entrer une limite de compte valide.";
$lang['Virtualmin.!error.meta[plan].empty'] = "Un plan VirtualMin est requis.";
$lang['Virtualmin.!error.meta[template].empty'] = "Un modèle VirtualMin est requis.";
$lang['Virtualmin.!error.api.internal'] = "Une erreur interne s'est produite ou le serveur n'a pas répondu à la demande.";
$lang['Virtualmin.!error.module_row.missing'] = "Une erreur interne est survenue. La ligne de module est indisponible.";
$lang['Virtualmin.!error.virtualmin_domain.format'] = "Veuillez entrer un nom de domaine valide, par exemple domain.com.";
$lang['Virtualmin.!error.virtualmin_domain.test'] = "Le nom de domaine ne peut pas commencer par 'test'.";
$lang['Virtualmin.!error.virtualmin_username.format'] = "Le nom d'utilisateur peut contenir uniquement des lettres et des chiffres et ne pas commencer par un chiffre.";
$lang['Virtualmin.!error.virtualmin_username.test'] = "Le nom d'utilisateur ne peut pas commencer par 'test'.";
$lang['Virtualmin.!error.virtualmin_username.length'] = "Le nom d'utilisateur doit comporter entre 1 et 16 caractères.";
$lang['Virtualmin.!error.virtualmin_password.valid'] = "Le mot de passe doit comporter au moins 8 caractères.";
?>