<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Braintree.name'] = "Braintree";
$lang['Braintree.merchant_id'] = "ID du marchand";
$lang['Braintree.public_key'] = "Clé publique";
$lang['Braintree.private_key'] = "Clé privée";
$lang['Braintree.live_mode'] = "Mode en direct";
$lang['Braintree.environment'] = "Environnement";
$lang['Braintree.environment.sandbox'] = "Bac à sable";
$lang['Braintree.environment.production'] = "Production";
$lang['Braintree.!error.live_mode.valid'] = "Le mode en direct doit être réglé sur \"vrai\" si il est donné.";
$lang['Braintree.!error.merchant_id'] = "Merci d'entrer votre ID marchand.";
$lang['Braintree.!error.public_key'] = "Merci d'entrer votre clé publique.";
$lang['Braintree.!error.private_key'] = "S'il vous plaît, entrez votre clé privée.";
$lang['Braintree.!error.environment'] = "Veuillez sélectionner un environnement valide.";
?>