<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Perfectmoney.name'] = "Perfect Money";
$lang['Perfectmoney.payee_account'] = "Compte du bénéficiaire";
$lang['Perfectmoney.passphrase'] = "Autre phrase secrète";
$lang['Perfectmoney.passphrase_note'] = "La phrase secrète alternative est utilisée pour le calcul du hachage MD5 afin de valider les paiements.";
$lang['Perfectmoney.buildprocess.submit'] = "Payer avec Perfect Money";
$lang['Perfectmoney.!error.payee_account.valid'] = "Vous devez entrer un compte valide.";
$lang['Perfectmoney.!error.passphrase.valid'] = "Vous devez entrer une phrase secrète valide";
?>