<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CustomReport.name'] = "Rapport personnalisé";
$lang['CustomReports.options.field_report'] = "Rapport";
$lang['CustomReports.options.field_report_select'] = "- Veuillez choisir -";
$lang['CustomReport.!error.field'] = "%1\$s n'est pas valide."; // %1$s is the field label
?>