<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Csv1_0.!error.csv_data.invalid'] = "Les données CSV fournies ne sont pas valides.";
$lang['Csv1_0.!error.import'] = "L'importation est terminée mais les erreurs suivantes se sont produites:";
$lang['Csv1_0.!error.required_fields'] = "Les champs suivants doivent être importés: Nom d'utilisateur, Prénom, Nom, E-mail, Téléphone";
$lang['Csv1_0.settings.csv_data'] = "Données CSV";
$lang['Csv1_0.settings.enable_debug'] = "Activer le débogage";
$lang['Csv1_0.configuration.local_field'] = "Champ local";
$lang['Csv1_0.configuration.remote_field'] = "Champ distant";
$lang['Csv1_0.configuration.no_import'] = "Aucune importation";
$lang['Csv1_0.configuration.username'] = "Nom d'utilisateur";
$lang['Csv1_0.configuration.first_name'] = "Prénom";
$lang['Csv1_0.configuration.last_name'] = "Nom";
$lang['Csv1_0.configuration.email'] = "E-mail";
$lang['Csv1_0.configuration.address1'] = "Adresse 1";
$lang['Csv1_0.configuration.address2'] = "Address 2";
$lang['Csv1_0.configuration.state'] = "Etat";
$lang['Csv1_0.configuration.zip'] = "Code postal";
$lang['Csv1_0.configuration.city'] = "Ville";
$lang['Csv1_0.configuration.country'] = "Pays";
$lang['Csv1_0.configuration.phone'] = "Téléphone";
$lang['Csv1_0.configuration.company'] = "Société";
$lang['Csv1_0.configuration.title'] = "Titre";
?>