<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientDataPortability.name'] = "Transférabilité des données des clients";
$lang['ClientDataPortability.options.field_client_id'] = "ID client";
$lang['ClientDataPortability.!error.client_id'] = "L'ID client n'est pas valide.";
$lang['ClientDataPortability.!tooltip.client_id'] = "Il s'agit de l'ID client interne affiché dans l'URL lorsque vous visualisez un profil client.";
?>