<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminStaff.!success.staff_added'] = "Le membre du personnel a été ajouté avec succès.";
$lang['AdminStaff.!success.staff_updated'] = "Le membre du personnel a été mis à jour avec succès.";
$lang['AdminStaff.!success.staff_deleted'] = "Le membre de l'équipe a été supprimé avec succès.";
$lang['AdminStaff.!tooltip.all_day'] = "Cochez cette case pour rendre le membre du personnel disponible toute la journée.";
$lang['AdminStaff.!tooltip.ticket_emails'] = "Cochez la case de priorité de chaque ticket pour lequel le personnel devrait recevoir des emails.";
$lang['AdminStaff.!tooltip.mobile_ticket_emails'] = "Cochez la case de chaque priorité de billets que le personnel devrait recevoir des courriels de billets via mobiles.";
$lang['AdminStaff.index.page_title'] = "Gestionnaire du support > Personnel";
$lang['AdminStaff.add.page_title'] = "Gestionnaire du support > Ajouter un membre du personnel";
$lang['AdminStaff.edit.page_title'] = "Gestionnaire du support > Modifier le personnel";
$lang['AdminStaff.index.categorylink_addstaff'] = "Ajouter un membre du personnel";
$lang['AdminStaff.index.boxtitle_staff'] = "Personnel";
$lang['AdminStaff.index.heading_first_name'] = "Nom";
$lang['AdminStaff.index.heading_email'] = "Courriel";
$lang['AdminStaff.index.heading_ticket_emails'] = "Recevoir les tickets par email";
$lang['AdminStaff.index.heading_mobile_ticket_emails'] = "Recevoir les billets en mode courriel mobile";
$lang['AdminStaff.index.heading_options'] = "Options";
$lang['AdminStaff.index.option_edit'] = "Modifier";
$lang['AdminStaff.index.option_delete'] = "Effacer";
$lang['AdminStaff.index.confirm_delete'] = "La suppression de ce membre du personnel va désassigner tous les billets actuellement assignés à cette personne. Êtes-vous sûr de vouloir supprimer ce membre du personnel?";
$lang['AdminStaff.index.no_results'] = "Il n'y a pas d'employé affecté au système de support.";
$lang['AdminStaff.add.boxtitle_addstaff'] = "Ajouter un membre du personnel";
$lang['AdminStaff.add.heading_staff'] = "Personnel";
$lang['AdminStaff.add.heading_schedule'] = "Cédule ";
$lang['AdminStaff.add.heading_settings'] = "Paramètres";
$lang['AdminStaff.add.heading_departments'] = "Départements";
$lang['AdminStaff.add.field_staff_group_id'] = "Groupe d'équipe";
$lang['AdminStaff.add.field_staff_id'] = "Membre de l'équipe";
$lang['AdminStaff.add.heading_day'] = "Jour";
$lang['AdminStaff.add.heading_all_day'] = "Toute la journée";
$lang['AdminStaff.add.heading_start_time'] = "Heure de départ";
$lang['AdminStaff.add.heading_end_time'] = "Heure de fin";
$lang['AdminStaff.add.ticket_emails'] = "Recevoir les billets par courriel";
$lang['AdminStaff.add.mobile_ticket_emails'] = "Recevoir les emails des tickets au format Mobile";
$lang['AdminStaff.add.text_assigneddepartments'] = "Départements assignés";
$lang['AdminStaff.add.text_availabledepartments'] = "Départements disponibles";
$lang['AdminStaff.add.field_addsubmit'] = "Ajouter un membre du personnel";
$lang['AdminStaff.edit.boxtitle_editstaff'] = "Modifier le membre du personnel %1\$s %2\$s"; // %1$s is the staff member's first name, %2$s is the staff member's last name
$lang['AdminStaff.edit.heading_schedule'] = "Horaire ";
$lang['AdminStaff.edit.heading_settings'] = "Paramètres";
$lang['AdminStaff.edit.heading_departments'] = "Départements";
$lang['AdminStaff.edit.heading_day'] = "Jour";
$lang['AdminStaff.edit.heading_all_day'] = "Toute la journée";
$lang['AdminStaff.edit.heading_start_time'] = "Heure de départ";
$lang['AdminStaff.edit.heading_end_time'] = "Heure de fin";
$lang['AdminStaff.edit.ticket_emails'] = "Recevoir les billets par courriel";
$lang['AdminStaff.edit.mobile_ticket_emails'] = "Recevoir les courriels de billets en version mobile ";
$lang['AdminStaff.edit.text_assigneddepartments'] = "Départements assignés";
$lang['AdminStaff.edit.text_availabledepartments'] = "Départements disponibles";
$lang['AdminStaff.edit.field_editsubmit'] = "Modifier Personnel";
$lang['AdminStaff.staff.name'] = "%1\$s %2\$s"; // %1$s is the staff member's first name, %2$s is the staff member's last name
$lang['AdminStaff.schedule_list.heading_schedule'] = "Cédule";
$lang['AdminStaff.schedule_list.heading_day'] = "Jour";
$lang['AdminStaff.schedule_list.heading_start_time'] = "Heure de départ";
$lang['AdminStaff.schedule_list.heading_end_time'] = "Heure de fin";
$lang['AdminStaff.schedule_list.no_results'] = "Ce membre du personnel n'est prévu pour aucun jour.";
$lang['AdminStaff.schedule_list.heading_departments'] = "Départements";
$lang['AdminStaff.schedule_list.heading_department'] = "Département";
$lang['AdminStaff.schedule_list.heading_description'] = "Description";
$lang['AdminStaff.schedule_list.no_department_results'] = "Ce membre du personnel n'est pas assigné à un département.";
$lang['AdminStaff.text.no_time'] = "--";
$lang['AdminStaff.!tooltip.title'] = "Le paramétrage d'un titre pour ce membre du personnel remplace le titre par défaut: %1\$s"; // %1$s is the language for the default title
$lang['AdminStaff.!tooltip.signature'] = "Entrez une signature pour la rendre automatiquement disponible lorsque vous répondez aux tickets.";
$lang['AdminStaff.add.title'] = "Titre";
$lang['AdminStaff.add.signature'] = "Signature";
$lang['AdminStaff.edit.title'] = "Titre";
$lang['AdminStaff.edit.signature'] = "Signature";
?>