<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminKnowledgebase.!success.category_added'] = "La catégorie a été créée avec succès.";
$lang['AdminKnowledgebase.!success.category_updated'] = "La catégorie a été mise à jour avec succès.";
$lang['AdminKnowledgebase.!success.category_deleted'] = "La catégorie a été effacée avec succès.";
$lang['AdminKnowledgebase.!success.article_added'] = "L'article a été créé avec succès.";
$lang['AdminKnowledgebase.!success.article_updated'] = "L'article a été mis à jour avec succès.";
$lang['AdminKnowledgebase.!success.article_deleted'] = "Cet article a été supprimé avec succès.";
$lang['AdminKnowledgebase.index.page_title'] = "Gestionnaire du support > Base de connaissance";
$lang['AdminKnowledgebase.add.page_title'] = "Gestionnaire du support > Base de connaissance > Ajouter un article";
$lang['AdminKnowledgebase.edit.page_title'] = "Gestionnaire de support > Base de connaissance > Modifier l'article";
$lang['AdminKnowledgebase.addcategory.page_title'] = "Gestionnaire du support > Base de connaissance > Ajouter une catégorie";
$lang['AdminKnowledgebase.editcategory.page_title'] = "Gestionnaire du support > Base de connaissance > Modifier la catégorie";
$lang['AdminKnowledgebase.index.add_article'] = "Ajouter un article";
$lang['AdminKnowledgebase.index.add_category'] = "Ajouter une catégorie";
$lang['AdminKnowledgebase.index.boxtitle_knowledgebase'] = "Base de connaissance";
$lang['AdminKnowledgebase.index.go_back'] = "Remonter d'un niveau";
$lang['AdminKnowledgebase.index.edit'] = "Modifier";
$lang['AdminKnowledgebase.index.delete'] = "Effacer";
$lang['AdminKnowledgebase.modal.delete_article'] = "Êtes-vous sur de vouloir effacer cet article?";
$lang['AdminKnowledgebase.modal.delete_category'] = "Êtes-vous sur de vouloir effacer cette catégorie? Toutes les sous-catégories et articles contenue dans celle-ci seront déplacés à la catégorie parente.";
$lang['AdminKnowledgebase.index.no_results'] = "Il n'y a pas de catégories ou articles dans cette section.";
$lang['AdminKnowledgebase.addcategory.boxtitle_addcategory'] = "Ajouter une catégorie";
$lang['AdminKnowledgebase.addcategory.field_name'] = "Nom";
$lang['AdminKnowledgebase.addcategory.field_parent_id'] = "Catégorie parente";
$lang['AdminKnowledgebase.addcategory.field_description'] = "Description";
$lang['AdminKnowledgebase.addcategory.field_access'] = "Accessibilité";
$lang['AdminKnowledgebase.addcategory.submit_add'] = "Créer une catégorie";
$lang['AdminKnowledgebase.addcategory.submit_cancel'] = "Annuler";
$lang['AdminKnowledgebase.editcategory.boxtitle_editcategory'] = "Mettre à jour la catégorie";
$lang['AdminKnowledgebase.editcategory.field_name'] = "Nom";
$lang['AdminKnowledgebase.editcategory.field_parent_id'] = "Catégorie parente";
$lang['AdminKnowledgebase.editcategory.field_description'] = "Description";
$lang['AdminKnowledgebase.editcategory.field_access'] = "Accessibilité";
$lang['AdminKnowledgebase.editcategory.submit_edit'] = "Mettre à jour la catégorie";
$lang['AdminKnowledgebase.editcategory.submit_cancel'] = "Annuler";
$lang['AdminKnowledgebase.add.boxtitle_add'] = "Ajouter un article";
$lang['AdminKnowledgebase.add.field_access'] = "Accessibilité";
$lang['AdminKnowledgebase.add.field_categories'] = "Catégorie";
$lang['AdminKnowledgebase.add.submit_add'] = "Créer un article";
$lang['AdminKnowledgebase.add.submit_cancel'] = "Annuler";
$lang['AdminKnowledgebase.edit.boxtitle_edit'] = "Mettre à jour l'article";
$lang['AdminKnowledgebase.edit.field_access'] = "Accessibilité";
$lang['AdminKnowledgebase.edit.field_categories'] = "Catégorie";
$lang['AdminKnowledgebase.edit.submit_edit'] = "Mettre à jour l'article";
$lang['AdminKnowledgebase.edit.submit_cancel'] = "Annuler";
$lang['AdminKnowledgebase.article_content.title'] = "Titre";
$lang['AdminKnowledgebase.article_content.content_type'] = "Type de contenu";
$lang['AdminKnowledgebase.article_content.body'] = "Corps";
$lang['AdminKnowledgebase.select.none'] = "-- Aucun --";
$lang['AdminKnowledgebase.!text.root_directory'] = "Répertoire d’accueil ";
$lang['AdminKnowledgebase.!text.open_enclosure'] = "(";
$lang['AdminKnowledgebase.!text.closed_enclosure'] = ")";
$lang['AdminKnowledgebase.!text.enclosure_separator'] = "/";
$lang['AdminKnowledgebase.!text.add_category'] = "Ajouter une catégorie";
$lang['AdminKnowledgebase.!text.directory_separator'] = "/";
$lang['AdminKnowledgebase.!tooltip.access_article'] = "Les articles publics sont accessibles à tous. Les articles privés sont accessibles uniquement aux utilisateurs qui sont connectés. Les articles cachés sont inaccessibles.";
$lang['AdminKnowledgebase.!tooltip.access_category'] = "Les catégories publiques sont accessibles à tous. Les catégories privées sont accessibles uniquement aux utilisateurs qui sont connectés. Les catégories cachées sont inaccessibles.";
?>