<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_name'] = "Billet de membre du personnel mis à jour";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_desc'] = "Avis envoyé à un membre du personnel quand un billet est mis à jour.";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_mobile_name'] = "Ticket du personnel mis à jour (mobile)";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_mobile_desc'] = "Avis mobile envoyé à un membre du personnel quand un billet est mis à jour.";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_received_name'] = "Billet reçu";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_received_desc'] = "Avis envoyé à l'utilisateur lorsqu'un billet est reçu.";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_updated_name'] = "Billet mis à jour";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_updated_desc'] = "Avis envoyé lorsqu'un billet est mis à jour.";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_bounce_name'] = "Rebond de ticket";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_bounce_desc'] = "Avis envoyé lorsqu'un billet a échoué à la création via courriel.";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_assigned_name'] = "Billet d'équipe assigné";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_assigned_desc'] = "Avis envoyé à un membre du personnel lorsqu'un billet leur est assigné.";
?>