<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminTickets.!success.ticket_created'] = "Le ticket #%1\$s a été ouvert avec succès."; // %1$s is the ticket number
$lang['AdminTickets.!success.ticket_updated'] = "Le billet #%1\$s a été mis à jour avec succès."; // %1$s is the ticket number
$lang['AdminTickets.!notice.no_departments_staff'] = "Aucun personnel et/ou département n'a encore été créé. Cliquez sur %1\$s ci-dessus pour créer un service ou sur %2\$s pour affecter un membre du personnel."; // %1$s is the language definition for the Departments navigation item, %2$s is the language definition for the Staff navigation item
$lang['AdminTickets.index.page_title'] = "Gestionnaire de support > Billets";
$lang['AdminTickets.add.page_title'] = "Gestionnaire du support > Ouvrir un billet";
$lang['AdminTickets.reply.page_title'] = "Gestionnaire du support > Billet #%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.search.page_title'] = "Résultats de recherche pour \"%1\$s\""; // %1$s is the search keywords
$lang['AdminTickets.text.unassigned'] = "Non assigné";
$lang['AdminTickets.index.category_open'] = "Ouvert";
$lang['AdminTickets.index.category_awaiting_reply'] = "En attente de réponse";
$lang['AdminTickets.index.category_in_progress'] = "En cours";
$lang['AdminTickets.index.category_closed'] = "Fermé";
$lang['AdminTickets.index.categorylink_createticket'] = "Ouvrir un billet";
$lang['AdminTickets.index.boxtitle_tickets'] = "Billets";
$lang['AdminTickets.index.heading_code'] = "Numéro de billet";
$lang['AdminTickets.index.heading_priority'] = "Priorités";
$lang['AdminTickets.index.heading_department_name'] = "Département";
$lang['AdminTickets.index.heading_summary'] = "Sommaire";
$lang['AdminTickets.index.heading_last_reply_date'] = "Dernière réponse";
$lang['AdminTickets.index.no_results'] = "Il n'y a pas de billet avec ce statut.";
$lang['AdminTickets.add.boxtitle_add'] = "Ouvrir un billet";
$lang['AdminTickets.add.heading_search_client'] = "Rechercher le client";
$lang['AdminTickets.add.text_no_clients'] = "Aucun client trouvé. Veuillez réessayer.";
$lang['AdminTickets.add.heading_summary'] = "Sommaire";
$lang['AdminTickets.add.heading_client'] = "Client";
$lang['AdminTickets.add.heading_department'] = "Département";
$lang['AdminTickets.add.heading_staff_id'] = "Assigné à";
$lang['AdminTickets.add.heading_priority'] = "Priorité";
$lang['AdminTickets.add.heading_status'] = "Statut";
$lang['AdminTickets.add.field_attachments'] = "Pièces jointes";
$lang['AdminTickets.add.field_details'] = "Détails";
$lang['AdminTickets.add.text_add_attachment'] = "Ajouter une pièce jointe";
$lang['AdminTickets.add.field_addsubmit'] = "Billet ouvert";
$lang['AdminTickets.add.text_add_response'] = "Insérez une réponse prédéfinie";
$lang['AdminTickets.reply.boxtitle_reply'] = "Billet #%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.reply.heading_summary'] = "Sommaire";
$lang['AdminTickets.reply.heading_client'] = "Client";
$lang['AdminTickets.reply.heading_department'] = "Département";
$lang['AdminTickets.reply.heading_staff_id'] = "Assigné à";
$lang['AdminTickets.reply.heading_priority'] = "Priorité";
$lang['AdminTickets.reply.heading_status'] = "Statut";
$lang['AdminTickets.reply.heading_date_added'] = "Date d'ouverture";
$lang['AdminTickets.reply.text_add_response'] = "Entrez une réponse prédéfinie";
$lang['AdminTickets.reply.heading_reply'] = "Ajouter une réponse";
$lang['AdminTickets.reply.field_reply'] = "Répondre";
$lang['AdminTickets.reply.field_note'] = "Note";
$lang['AdminTickets.reply.field_attachments'] = "Pièces jointes";
$lang['AdminTickets.reply.text_add_attachment'] = "Ajouter une pièce jointe";
$lang['AdminTickets.reply.field_replysubmit'] = "Mettre à jour le billet";
$lang['AdminTickets.reply.reply_date'] = "Le %1\$s, %2\$s %3\$s a répondu"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['AdminTickets.reply.log_date'] = "%1\$s par %2\$s %3\$s"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['AdminTickets.reply.system'] = "Système";
$lang['AdminTickets.reply.staff_title'] = "Personnel de soutien";
$lang['AdminTickets.client.category_open'] = "Ouvert";
$lang['AdminTickets.client.category_awaiting_reply'] = "En attente de réponse";
$lang['AdminTickets.client.category_in_progress'] = "En cours";
$lang['AdminTickets.client.category_closed'] = "Fermé";
$lang['AdminTickets.client.categorylink_createticket'] = "Ouvrir un billet";
$lang['AdminTickets.client.boxtitle_tickets'] = "Billets";
$lang['AdminTickets.client.heading_code'] = "Numéro de billet";
$lang['AdminTickets.client.heading_priority'] = "Priorité";
$lang['AdminTickets.client.heading_department_name'] = "Département";
$lang['AdminTickets.client.heading_summary'] = "Sommaire";
$lang['AdminTickets.client.heading_last_reply_date'] = "Dernière réponse";
$lang['AdminTickets.client.no_results'] = "Il n'y a aucun billet avec ce statut.";
$lang['AdminTickets.search.boxtitle_tickets'] = "Recherche de billets pour \"%1\$s\""; // %1$s is the search criteria
$lang['AdminTickets.search.heading_code'] = "Numéro de billet";
$lang['AdminTickets.search.heading_priority'] = "Priorité";
$lang['AdminTickets.search.heading_status'] = "Statut";
$lang['AdminTickets.search.heading_department_name'] = "Département";
$lang['AdminTickets.search.heading_summary'] = "Sommaire";
$lang['AdminTickets.search.heading_last_reply_date'] = "Dernière réponse";
$lang['AdminTickets.search.no_results'] = "Il n'y a pas de billet qui correspondent aux critères de recherche.";
$lang['AdminTickets.index.last_reply_by'] = "par";
$lang['Admintickets.add.client_placeholder'] = "ID Client ou nom";
$lang['AdminTickets.!success.ticket_split'] = "Le billet #%1\$s a été scindé avec succès dans le billet #%2\$s."; // %1$s is the ticket number of the ticket being split, %2$s is the ticket number of the split ticket
$lang['AdminTickets.!success.ticket_merge'] = "Les billets sélectionnés ont été fusionnés avec succès dans le billet # %1\$s."; // %1$s is the ticket number
$lang['AdminTickets.!success.ticket_update_status'] = "Les tickets sélectionnés ont été mis à jour avec succès.";
$lang['AdminTickets.index.heading_assigned_staff'] = "Assigné à";
$lang['AdminTickets.index.unassigned'] = "Non affecté";
$lang['AdminTickets.index.text_with_selected'] = "Avec les billets sélectionnés, faire:";
$lang['AdminTickets.index.text_into_ticket'] = "Dans le billet:";
$lang['AdminTickets.index.text_to_status'] = "Changer à:";
$lang['AdminTickets.index.ticket_number_placeholder'] = "Numéro de billet";
$lang['AdminTickets.index.text_no_tickets'] = "Aucun billet ouvert trouvé. Veuillez chercher à nouveau.";
$lang['AdminTickets.index.field_actionsubmit'] = "Soumettre";
$lang['AdminTickets.index.ticket_name'] = "#%1\$s %2\$s %3\$s"; // %1$s is the ticket number, %2$s is the client's first name, %3$s is the client's last name
$lang['AdminTickets.index.ticket_email'] = "#%1\$s %2\$s"; // %1$s is the ticket number, %2$s is the client's email address
$lang['AdminTickets.reply.text_with_selected'] = "Avec les réponses sélectionnées, faire:";
$lang['AdminTickets.reply.field_actionsubmit'] = "Aller";
$lang['AdminTickets.index.heading_client'] = "Client";
$lang['AdminTickets.!success.ticket_delete'] = "Les tickets sélectionnés ont été supprimés avec succès.";
$lang['AdminTickets.index.category_on_hold'] = "En attente";
$lang['AdminTickets.index.category_trash'] = "Corbeille";
$lang['AdminTickets.client.category_on_hold'] = "En attente";
$lang['AdminTickets.client.category_trash'] = "Corbeille";
?>