<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientTickets.!success.ticket_created'] = "Le billet # %1\$s a été créé avec succès."; // %1$s is the ticket number
$lang['ClientTickets.!success.ticket_updated'] = "Le ticket # %1\$s a été mis à jour."; // %1$s is the ticket number
$lang['ClientTickets.!success.ticket_closed'] = "Le billet #%1\$s a été fermé correctement."; // %1$s is the ticket number
$lang['ClientTickets.!notice.no_departments'] = "Il n'y a pas de département de support disponible.";
$lang['ClientTickets.index.page_title'] = "Support > Billets";
$lang['ClientTickets.add.page_title'] = "Support > Ouvrir un billet";
$lang['ClientTickets.reply.page_title'] = "Support > Mettre à jour le billet";
$lang['ClientTickets.index.category_open'] = "Ouvert";
$lang['ClientTickets.index.category_closed'] = "Fermé";
$lang['ClientTickets.index.categorylink_createticket'] = "Billet ouvert";
$lang['ClientTickets.index.boxtitle_tickets'] = "Billets";
$lang['ClientTickets.index.heading_code'] = "Numéro de billet";
$lang['ClientTickets.index.heading_priority'] = "Priorité";
$lang['ClientTickets.index.heading_department_name'] = "Département";
$lang['ClientTickets.index.heading_summary'] = "Résumé";
$lang['ClientTickets.index.heading_last_reply_date'] = "Dernière réponse";
$lang['ClientTickets.index.heading_status'] = "Statut";
$lang['ClientTickets.index.heading_options'] = "Options";
$lang['ClientTickets.index.option_close'] = "Fermer";
$lang['ClientTickets.add.text_add_attachment'] = "Ajouter pièce-jointe";
$lang['ClientTickets.index.no_results'] = "Il n'y a pas de billet avec ce statut.";
$lang['ClientTickets.index.confirm_close'] = "Êtes-vous sur de vouloir fermer ce billet?";
$lang['ClientTickets.add.boxtitle_add'] = "Ouvrir un billet";
$lang['ClientTickets.add.field_email'] = "Courriel";
$lang['ClientTickets.add.field_summary'] = "Sommaire";
$lang['ClientTickets.add.field_priority'] = "Priorité";
$lang['ClientTickets.add.field_details'] = "Détails";
$lang['ClientTickets.add.field_attachments'] = "Pièces jointes";
$lang['ClientTickets.add.field_addsubmit'] = "Ticket ouvert";
$lang['ClientTickets.reply.boxtitle_reply'] = "Billet #%1\$s"; // %1$s is the ticket number
$lang['ClientTickets.reply.heading_summary'] = "Sommaire";
$lang['ClientTickets.reply.heading_department'] = "Département";
$lang['ClientTickets.reply.heading_priority'] = "Priorité";
$lang['ClientTickets.reply.heading_status'] = "Statut";
$lang['ClientTickets.reply.heading_date_added'] = "Date d'ouverture";
$lang['ClientTickets.reply.heading_reply'] = "Ajouter une réponse";
$lang['ClientTickets.reply.field_details'] = "Détails";
$lang['ClientTickets.reply.field_attachments'] = "Pièces jointes";
$lang['ClientTickets.reply.text_add_attachment'] = "Ajouter une pièce jointe.";
$lang['ClientTickets.reply.reply_date'] = "Le %1\$s %2\$s %3\$s a répondu"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['ClientTickets.reply.log_date'] = "%1\$s par %2\$s %3\$s"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['ClientTickets.reply.system'] = "Système";
$lang['ClientTickets.reply.staff_title'] = "Personnel de support";
$lang['ClientTickets.departments.boxtitle_departments'] = "Départements de support";
$lang['ClientTickets.index.option_reply'] = "Répondre";
$lang['ClientTickets.add.placeholder_summary'] = "Entrez un résumé";
$lang['ClientTickets.add.placeholder_details'] = "Entrer les détails";
$lang['ClientTickets.reply.placeholder_reply'] = "Entrer les détails";
$lang['ClientTickets.reply.field_closesubmit'] = "Fermer";
$lang['ClientTickets.reply.confirm_close'] = "Êtes-vous sur de vouloir fermer ce billet?";
$lang['ClientTickets.reply.field_replysubmit'] = "Réponse";
?>