<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Knowledgebase.index.page_title'] = "Base de connaissances";
$lang['Knowledgebase.view.page_title'] = "%1\$s"; // %1\$s is the title of the knowledge base article
$lang['Knowledgebase.search.placeholder'] = "Vous avez une question? Recherchez notre base de connaissance ici.";
$lang['Knowledgebase.search.form_submit'] = "Recherche";
$lang['Knowledgebase.index.heading_categories'] = "Catégories";
$lang['Knowledgebase.index.heading_subcategories'] = "Sous-catégories";
$lang['Knowledgebase.index.category_items'] = "(%1\$s)"; // %1$s is the number of items within this category
$lang['Knowledgebase.index.categories_description'] = "Consultez notre base de connaissances par catégorie.";
$lang['Knowledgebase.index.categories_no_results'] = "Il n'y a pas de catégorie disponible.";
$lang['Knowledgebase.index.heading_popular'] = "Articles populaires";
$lang['Knowledgebase.index.popular_description'] = "Les gens ont trouvé ces articles comme étant les plus utiles.";
$lang['Knowledgebase.index.heading_articles'] = "Articles";
$lang['Knowledgebase.index.articles_description'] = "Articles pour %1\$s."; // %1$s is the name of the category
$lang['Knowledgebase.search.heading_articles'] = "Articles correspondant à '%1\$s'"; // %1$s is the search criteria
$lang['Knowledgebase.search.articles_no_results'] = "Il n'y a pas d'articles qui correspondent aux critères de recherche.";
$lang['Knowledgebase.view.text_rate'] = "Veuillez évaluer cet article pour nous aider à améliorer notre base de connaissances.";
$lang['Knowledgebase.view.edit'] = "Éditer";
$lang['Knowledgebase.view.text_voted'] = "Vous avez déjà voté sur cet article.";
$lang['Knowledgebase.view.text_vote_thanks'] = "Merci d'avoir voté sur cet article!";
$lang['Knowledgebase.!text.root_directory'] = "Accueil";
$lang['Knowledgebase.!text.ellipsis'] = "...";
?>