<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerTickets.!error.code.format'] = "Le code du ticket ne doit contenir que des chiffres.";
$lang['SupportManagerTickets.!error.department_id.exists'] = "Veuillez sélectionner un département valide.";
$lang['SupportManagerTickets.!error.staff_id.exists'] = "Le membre du personnel choisi pour ce billet n'existe pas.";
$lang['SupportManagerTickets.!error.service_id.exists'] = "Le service choisi pour ce billet n'existe pas.";
$lang['SupportManagerTickets.!error.service_id.belongs'] = "Le service sélectionné est invalide.";
$lang['SupportManagerTickets.!error.client_id.exists'] = "Le client sélectionné pour ce billet n'existe pas.";
$lang['SupportManagerTickets.!error.client_id.set'] = "Le billet appartient à un autre client et le client associé au billet ne peut être changé.";
$lang['SupportManagerTickets.!error.email.format'] = "Merci d'entrer une adresse email valide.";
$lang['SupportManagerTickets.!error.summary.empty'] = "Veuillez entrer un sommaire.";
$lang['SupportManagerTickets.!error.summary.length'] = "Le sommaire ne doit pas excéder 255 caractères.";
$lang['SupportManagerTickets.!error.priority.format'] = "Veuillez sélectionner une priorité valide.";
$lang['SupportManagerTickets.!error.status.format'] = "Veuillez sélectionner un statut valide.";
$lang['SupportManagerTickets.!error.date_closed.format'] = "La date de fermeture de ticket est invalide.";
$lang['SupportManagerTickets.!error.ticket_id.exists'] = "ID de billet invalide.";
$lang['SupportManagerTickets.!error.type.format'] = "Veuillez sélectionner un type de réponse valide.";
$lang['SupportManagerTickets.!error.type.new_valid'] = "Les nouveaux billets doivent avoir un type de réponse de type \"réponse\".";
$lang['SupportManagerTickets.!error.details.empty'] = "Veuillez entrer des détails à propos de ce billet.";
$lang['SupportManagerTickets.!error.client_id.attached_to'] = "La réponse d'un billet ne peut être d'un client différent.";
$lang['SupportManagerTickets.priority.emergency'] = "Urgence";
$lang['SupportManagerTickets.priority.critical'] = "Critique";
$lang['SupportManagerTickets.priority.high'] = "Haut";
$lang['SupportManagerTickets.priority.medium'] = "Moyen";
$lang['SupportManagerTickets.priority.low'] = "Bas";
$lang['SupportManagerTickets.status.open'] = "Ouvert";
$lang['SupportManagerTickets.status.in_progress'] = "En cours";
$lang['SupportManagerTickets.status.closed'] = "Fermé";
$lang['SupportManagerTickets.type.reply'] = "Répondre";
$lang['SupportManagerTickets.type.note'] = "Note";
$lang['SupportManagerTickets.type.log'] = "Journaux";
$lang['SupportManagerTickets.log.department_id'] = "Le département a été changé à %1\$s."; // %1$s is the department name
$lang['SupportManagerTickets.log.summary'] = "Le sommaire a été mis à jour";
$lang['SupportManagerTickets.log.priority'] = "La priorité a été changé à %1\$s."; // %1$s is the priority
$lang['SupportManagerTickets.log.status'] = "Le statut a été changé à %1\$s."; // %1$s is the status
$lang['SupportManagerTickets.log.ticket_staff_id'] = "Assigné à %1\$s."; // %1$s is the name of the department staff member the ticket was assigned to
$lang['SupportManagerTickets.log.unassigned'] = "Non assigné";
$lang['SupportManagerTickets.status.awaiting_reply'] = "En attente de retour";
$lang['SupportManagerTickets.!error.by_staff_id.exists'] = "Le membre du personnel défini comme effectuant la modification n'existe pas.";
$lang['SupportManagerTickets.!error.replies.valid'] = "Au moins un ID de réponse de billet est invalide ou toutes les réponses ont été sélectionnées. Vous devez avoir au moins une réponse restante.";
$lang['SupportManagerTickets.!error.tickets.valid'] = "Au moins un billet sélectionné est invalide, fermé ou n'appartient pas au même client que le billet choisi. ";
$lang['SupportManagerTickets.!error.merge_into.itself'] = "Le billet ne peut être fusionné avec lui-même. ";
$lang['SupportManagerTickets.!error.tickets.service_matches'] = "Au moins un des billets n'as pu être assigné au service fourni car ce service n'est pas associé au client.";
$lang['SupportManagerTickets.!error.tickets.department_matches'] = "Au moins un des billets n'a pas pu être affecté au département donné, car il n'appartient pas à la même compagnie.";
$lang['SupportManagerTickets.merge.reply'] = "Ce billet a été intégré dans le billet #%1\$s."; // %1$s is the ticket number
$lang['SupportManagerTickets.!error.contact_id.exists'] = "Le contact sélectionné pour la réponse à ce billet n'existe pas.";
$lang['SupportManagerTickets.!error.contact_id.valid'] = "Le contact ne peut répondre au billet sans un client valide.";
$lang['SupportManagerTickets.!error.replies.notes'] = "Les notes de réponse de ticket ne peuvent pas être divisées en un ticket séparé sans inclure également une réponse de ticket.";
$lang['SupportManagerTickets.!error.status.trash'] = "Un ticket mis à la corbeille ne peut pas être édité.";
$lang['SupportManagerTickets.!error.date_added.format'] = "La date d'ajout du ticket est dans un format de date invalide.";
$lang['SupportManagerTickets.!error.date_updated.format'] = "La date de mise à jour du ticket est dans un format de date non valide.";
$lang['SupportManagerTickets.status.on_hold'] = "En attente";
$lang['SupportManagerTickets.status.trash'] = "Corbeille";
?>