<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerResponses.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['SupportManagerResponses.!error.parent_id.exists'] = "ID de catégorie parent invalide";
$lang['SupportManagerResponses.!error.parent_id.company'] = "Cette catégorie doit appartenir à la même compagnie que son parent.";
$lang['SupportManagerResponses.!error.name.empty'] = "Veuillez entrer un nom de catégorie.";
$lang['SupportManagerResponses.!error.name.length'] = "Le nom de la catégorie ne peut excéder 64 caractères de long.";
$lang['SupportManagerResponses.!error.category_id.exists'] = "ID de catégorie invalide.";
$lang['SupportManagerResponses.!error.name.response_empty'] = "Veuillez entrer un nom pour cette réponse.";
$lang['SupportManagerResponses.!error.name.response_length'] = "Le nom de catégorie ne peut excéder 64 caractères.";
$lang['SupportManagerResponses.!error.details.empty'] = "Veuillez entrer les détails de réponse.";
$lang['SupportManagerResponses.!error.category_id.root_responses'] = "La catégorie ne peut être supprimé car elle contient des réponses prédéfinies.";
?>