<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerKbCategories.!error.parent_id.exists'] = "ID parent invalide.";
$lang['SupportManagerKbCategories.!error.parent_id.valid_company'] = "Cette catégorie ne peut être assignée à un parent d'une compagnie séparée.";
$lang['SupportManagerKbCategories.!error.parent_id.valid_parent'] = "Cette catégorie ne peut pas être parente à elle-même.";
$lang['SupportManagerKbCategories.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['SupportManagerKbCategories.!error.name.empty'] = "Veuillez indiquer une catégorie.";
$lang['SupportManagerKbCategories.!error.name.length'] = "Le nom de la catégorie ne peut excéder 255 caractères.";
$lang['SupportManagerKbCategories.!error.access.type'] = "Type d'accès invalide.";
$lang['SupportManagerKbCategories.!error.category_id.exists'] = "ID de catégorie invalide.";
$lang['SupportManagerKbCategories.access_types.public'] = "Public";
$lang['SupportManagerKbCategories.access_types.private'] = "Privé";
$lang['SupportManagerKbCategories.access_types.hidden'] = "Caché";
$lang['SupportManagerKbCategories.!error.articles.parent'] = "La catégorie ne peut être supprimée que si tous les articles qu'elle contient appartiennent à une autre catégorie.";
?>