<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerPlugin.name'] = "Gestionnaire du support";
$lang['SupportManagerPlugin.cron.poll_tickets_name'] = "Télécharger les billets";
$lang['SupportManagerPlugin.cron.poll_tickets_desc'] = "Se connecte au serveur POP3 / IMAP pour télécharger courriels et les convertir en billets.";
$lang['SupportManagerPlugin.nav_primary_client.main'] = "Support";
$lang['SupportManagerPlugin.nav_primary_staff.main'] = "Support";
$lang['SupportManagerPlugin.nav_primary_staff.tickets'] = "Billets";
$lang['SupportManagerPlugin.nav_primary_staff.departments'] = "Départements";
$lang['SupportManagerPlugin.nav_primary_staff.responses'] = "Réponses";
$lang['SupportManagerPlugin.nav_primary_staff.staff'] = "Équipe";
$lang['SupportManagerPlugin.widget_staff_client.tickets'] = "Billets";
$lang['SupportManagerPlugin.action_staff_client.add'] = "Billet ouvert";
$lang['SupportManagerPlugin.event_getsearchoptions.tickets'] = "Recherche de billet";
$lang['SupportManagerPlugin.permission.admin_main'] = "Support";
$lang['SupportManagerPlugin.permission.admin_tickets'] = "Billets";
$lang['SupportManagerPlugin.permission.admin_tickets_client'] = "Widget de profil client";
$lang['SupportManagerPlugin.permission.admin_departments'] = "Départements";
$lang['SupportManagerPlugin.permission.admin_responses'] = "Réponses";
$lang['SupportManagerPlugin.permission.admin_staff'] = "Personnel";
$lang['SupportManagerPlugin.cron.close_tickets_name'] = "Billets fermés";
$lang['SupportManagerPlugin.cron.close_tickets_desc'] = "Ferme automatiquement billets ouverts tel que configuré pour les départements dans le gestionnaire de support.";
$lang['SupportManagerPlugin.nav_primary_client.tickets'] = "Billets";
$lang['SupportManagerPlugin.nav_primary_client.knowledgebase'] = "Base de connaissance";
$lang['SupportManagerPlugin.nav_primary_staff.knowledgebase'] = "Base de connaissance";
$lang['SupportManagerPlugin.permission.admin_knowledgebase'] = "Base de connaissance";
$lang['SupportManagerPlugin.cron.delete_tickets_name'] = "Supprimer les tickets de la corbeille";
$lang['SupportManagerPlugin.cron.delete_tickets_desc'] = "Supprimez automatiquement les tickets de la corbeille tels que configurés pour les départements dans le Gestionnaire de support.";
$lang['SupportManagerPlugin.permission.admin_tickets_delete'] = "Supprimer définitivement les tickets";
?>