<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerStaff.!error.staff_id.exists'] = "Le membre du personnel à être ajouté n'existe pas.";
$lang['SupportManagerStaff.!error.staff_id.belongs'] = "Le membre de l'équipe ne fait pas partie de la compagnie à laquelle il est assigné.";
$lang['SupportManagerStaff.!error.staff_id.duplicate'] = "Le membre du personnel sélectionné existe déjà dans le système de support.";
$lang['SupportManagerStaff.!error.company_id.exists'] = "L'ID de compagnie est invalide.";
$lang['SupportManagerStaff.!error.departments.exists'] = "Au moins un des départements n'existe pas.";
$lang['SupportManagerStaff.!error.schedules.minimum'] = "Veuillez définir une heure de début et de fin prévue pour au moins une journée.";
$lang['SupportManagerStaff.!error.schedules.unique_days'] = "Chaque jour prévu doit être unique.";
$lang['SupportManagerStaff.!error.schedules[][day].format'] = "Journée planifiée invalide";
$lang['SupportManagerStaff.!error.schedules[][start_time].format'] = "Veuillez sélectionner un heure de départ pour chaque journée cédulée.";
$lang['SupportManagerStaff.!error.schedules[][end_time].format'] = "Veuillez choisir une heure de fin pour chaque jour cédulé. ";
$lang['SupportManagerStaff.days.sun'] = "Dimanche";
$lang['SupportManagerStaff.days.mon'] = "Lundi";
$lang['SupportManagerStaff.days.tue'] = "Mardi";
$lang['SupportManagerStaff.days.wed'] = "Mercredi";
$lang['SupportManagerStaff.days.thu'] = "Jeudi";
$lang['SupportManagerStaff.days.fri'] = "Vendredi";
$lang['SupportManagerStaff.days.sat'] = "Samedi";
?>