<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerDepartments.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['SupportManagerDepartments.!error.name.empty'] = "Veuillez entrer un nom pour ce département.";
$lang['SupportManagerDepartments.!error.description.empty'] = "Veuillez entrer une description";
$lang['SupportManagerDepartments.!error.email.format'] = "Veuillez entrer une adresse courriel valide.";
$lang['SupportManagerDepartments.!error.method.format'] = "Type de méthode invalide.";
$lang['SupportManagerDepartments.!error.method.imap'] = "L’extension PHP IMAP est requise pour télécharger les messages via POP3 ou IMAP.";
$lang['SupportManagerDepartments.!error.method.mailparse'] = "L'extension PHP Mailparse PECL est nécessaire pour l'analyse des billets courriels.";
$lang['SupportManagerDepartments.!error.default_priority.format'] = "Type de priorité par défaut invalide.";
$lang['SupportManagerDepartments.!error.host.format'] = "Veuillez entrer un nom d'hôte valide.";
$lang['SupportManagerDepartments.!error.host.length'] = "Le nom d'hôte ne peut pas dépasser 128 caractères.";
$lang['SupportManagerDepartments.!error.user.format'] = "Veuillez entrer un nom d'utilisateur.";
$lang['SupportManagerDepartments.!error.user.length'] = "Le nom d'utilisateur ne peut dépasser 64 caractères de long.";
$lang['SupportManagerDepartments.!error.password.format'] = "Veuillez entrer un mot de passe.";
$lang['SupportManagerDepartments.!error.port.format'] = "Veuillez entrer un numéro de port.";
$lang['SupportManagerDepartments.!error.port.length'] = "Le port ne peut excéder 6 caractères de longueur.";
$lang['SupportManagerDepartments.!error.service.format'] = "Veuillez choisir un type de service valide.";
$lang['SupportManagerDepartments.!error.security.format'] = "Veuillez choisir un type de sécurité valide.";
$lang['SupportManagerDepartments.!error.mark_messages.format'] = "S'il vous plaît choisir un type de message valide pour marquer des messages.";
$lang['SupportManagerDepartments.!error.mark_messages.valid'] = "Les messages utilisant POP3 peuvent seulement être marqués comme supprimés.";
$lang['SupportManagerDepartments.!error.status.format'] = "Type de statut invalide.";
$lang['SupportManagerDepartments.!error.department_id.exists'] = "ID de département invalide.";
$lang['SupportManagerDepartments.!error.department_id.has_tickets'] = "Le département ne peut pas être supprimé car il a actuellement des billets qui lui sont confiées.";
$lang['SupportManagerDepartments.methods.none'] = "Aucun";
$lang['SupportManagerDepartments.methods.pipe'] = "Piping";
$lang['SupportManagerDepartments.methods.pop3'] = "POP3";
$lang['SupportManagerDepartments.methods.imap'] = "IMAP";
$lang['SupportManagerDepartments.statuses.hidden'] = "Caché";
$lang['SupportManagerDepartments.statuses.visible'] = "Visible";
$lang['SupportManagerDepartments.priorities.emergency'] = "Urgence";
$lang['SupportManagerDepartments.priorities.critical'] = "Critique";
$lang['SupportManagerDepartments.priorities.high'] = "Élevé";
$lang['SupportManagerDepartments.priorities.medium'] = "Moyen";
$lang['SupportManagerDepartments.priorities.low'] = "Bas";
$lang['SupportManagerDepartments.security_types.none'] = "Aucun";
$lang['SupportManagerDepartments.security_types.ssl'] = "SSL";
$lang['SupportManagerDepartments.security_types.tls'] = "TLS";
$lang['SupportManagerDepartments.message_types.read'] = "Lecture";
$lang['SupportManagerDepartments.message_types.deleted'] = "Effacé";
$lang['SupportManagerDepartments.!error.clients_only.format'] = "Permettre ou non aux clients d'ouvrir ou de répondre aux billets doit être paramétré à 0 ou 1.";
$lang['SupportManagerDepartments.!error.override_from_email.format'] = "Ceci pour permettre aux départements d'utiliser leur adresse mail comme adresse d'envoie  dans les modèles de courriel. doit être réglé sur 0 ou 1.";
$lang['SupportManagerDepartments.!error.close_ticket_interval.format'] = "Veuillez sélectionner un intervalle valide de fermeture de billet.";
$lang['SupportManagerDepartments.!error.response_id.format'] = "Veuillez choisir une réponse de fermeture automatique valide.";
$lang['SupportManagerDepartments.ticket_intervals.day'] = "1 Jour";
$lang['SupportManagerDepartments.ticket_intervals.days'] = "%1\$s jours"; // %1$s is the number of days
$lang['SupportManagerDepartments.!error.send_ticket_received.format'] = "Si vous souhaitez envoyer des e-mails de confirmation de ticket pour ce service, vous devez définir la valeur 0 ou 1.";
$lang['SupportManagerDepartments.!error.delete_ticket_interval.format'] = "Veuillez sélectionner un intervalle de suppression de ticket valide.";
?>