<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Centoswebpanel.name'] = "CentOS WebPanel";
$lang['Centoswebpanel.module_row'] = "Serveur";
$lang['Centoswebpanel.module_row_plural'] = "Serveurs";
$lang['Centoswebpanel.module_group'] = "Groupe de serveurs";
$lang['Centoswebpanel.tab_firewall'] = "Pare-feu";
$lang['Centoswebpanel.tab_client_firewall'] = "Pare-feu";
$lang['Centoswebpanel.add_module_row'] = "Ajouter un serveur";
$lang['Centoswebpanel.add_module_group'] = "Ajouter un groupe de serveurs";
$lang['Centoswebpanel.manage.module_rows_title'] = "Serveurs";
$lang['Centoswebpanel.manage.module_groups_title'] = "Groupes de serveurs";
$lang['Centoswebpanel.manage.module_rows_heading.name'] = "Étiquette du serveur";
$lang['Centoswebpanel.manage.module_rows_heading.hostname'] = "Nom d'hôte";
$lang['Centoswebpanel.manage.module_rows_heading.accounts'] = "Comptes";
$lang['Centoswebpanel.manage.module_rows_heading.options'] = "Options";
$lang['Centoswebpanel.manage.module_groups_heading.name'] = "Nom de groupe";
$lang['Centoswebpanel.manage.module_groups_heading.servers'] = "Nombre de serveurs";
$lang['Centoswebpanel.manage.module_groups_heading.options'] = "Options";
$lang['Centoswebpanel.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Centoswebpanel.manage.module_rows.edit'] = "Modifier";
$lang['Centoswebpanel.manage.module_groups.edit'] = "Modifier";
$lang['Centoswebpanel.manage.module_rows.delete'] = "Supprimer";
$lang['Centoswebpanel.manage.module_groups.delete'] = "Supprimer";
$lang['Centoswebpanel.manage.module_rows.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer ce serveur?";
$lang['Centoswebpanel.manage.module_groups.confirm_delete'] = "Êtes-vous sûr de vouloir supprimer ce groupe de serveurs?";
$lang['Centoswebpanel.manage.module_rows_no_results'] = "Il n'y a pas de serveurs.";
$lang['Centoswebpanel.manage.module_groups_no_results'] = "Il n'y a pas de groupe de serveur";
$lang['Centoswebpanel.order_options.first'] = "Premier serveur non complet";
$lang['Centoswebpanel.order_options.roundrobin'] = "Répartir uniformément entre les serveurs";
$lang['Centoswebpanel.add_row.box_title'] = "Ajouter un serveur WebPanel CentOS";
$lang['Centoswebpanel.add_row.basic_title'] = "Paramètres de base";
$lang['Centoswebpanel.add_row.name_servers_title'] = "Serveurs de noms";
$lang['Centoswebpanel.add_row.notes_title'] = "Remarques";
$lang['Centoswebpanel.add_row.name_server_btn'] = "Ajouter un serveur de noms supplémentaire";
$lang['Centoswebpanel.add_row.name_server_col'] = "Serveur de nom";
$lang['Centoswebpanel.add_row.name_server_host_col'] = "Nom d'hôte";
$lang['Centoswebpanel.add_row.name_server'] = "Serveur de noms %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Centoswebpanel.add_row.remove_name_server'] = "Supprimer";
$lang['Centoswebpanel.add_row.add_btn'] = "Ajouter un serveur";
$lang['Centoswebpanel.edit_row.box_title'] = "Modifier le serveur CentOS WebPanel";
$lang['Centoswebpanel.edit_row.basic_title'] = "Paramètres de base";
$lang['Centoswebpanel.edit_row.name_servers_title'] = "Serveurs de noms";
$lang['Centoswebpanel.edit_row.notes_title'] = "Remarques";
$lang['Centoswebpanel.edit_row.name_server_btn'] = "Ajouter un serveur de noms supplémentaire";
$lang['Centoswebpanel.edit_row.name_server_col'] = "Serveur de noms";
$lang['Centoswebpanel.edit_row.name_server_host_col'] = "Nom d'hôte";
$lang['Centoswebpanel.edit_row.name_server'] = "Serveur de noms %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Centoswebpanel.edit_row.remove_name_server'] = "Supprimer";
$lang['Centoswebpanel.edit_row.add_btn'] = "Modifier le serveur";
$lang['Centoswebpanel.row_meta.server_name'] = "Étiquette du serveur";
$lang['Centoswebpanel.row_meta.host_name'] = "Nom d'hôte";
$lang['Centoswebpanel.row_meta.api_key'] = "Clé API";
$lang['Centoswebpanel.row_meta.use_ssl'] = "Utiliser SSL lors de la connexion à l'API (recommandé)";
$lang['Centoswebpanel.row_meta.account_limit'] = "Limite de compte";
$lang['Centoswebpanel.package_fields.package'] = "ID du forfait";
$lang['Centoswebpanel.package_fields.inode'] = "Maximum d'Inodes";
$lang['Centoswebpanel.package_fields.nofile'] = "Nombre maximum de fichiers";
$lang['Centoswebpanel.package_fields.nproc'] = "Processus maximum";
$lang['Centoswebpanel.service_field.domain'] = "Domaine";
$lang['Centoswebpanel.service_field.username'] = "Nom d'utilisateur";
$lang['Centoswebpanel.service_field.password'] = "Mot de passe";
$lang['Centoswebpanel.tab_firewall.unblock_ip_title'] = "Débloquer IP";
$lang['Centoswebpanel.tab_firewall.field_ip_address'] = "Adresse IP";
$lang['Centoswebpanel.tab_firewall.button_unblock'] = "Débloquer";
$lang['Centoswebpanel.tab_client_firewall.unblock_ip_title'] = "Débloquer IP";
$lang['Centoswebpanel.tab_client_firewall.field_ip_address'] = "Adresse IP";
$lang['Centoswebpanel.tab_client_firewall.button_unblock'] = "Débloquer";
$lang['Centoswebpanel.service_info.username'] = "Nom d'utilisateur";
$lang['Centoswebpanel.service_info.password'] = "Mot de passe";
$lang['Centoswebpanel.service_info.server'] = "Serveur";
$lang['Centoswebpanel.service_info.options'] = "Options";
$lang['Centoswebpanel.service_info.option_login'] = "Connexion";
$lang['Centoswebpanel.service_field.tooltip.username'] = "Vous pouvez laisser le nom d'utilisateur vide pour en générer un automatiquement.";
$lang['Centoswebpanel.service_field.tooltip.password'] = "Vous pouvez laisser le mot de passe vide pour en générer un automatiquement.";
$lang['Centoswebpanel.!error.server_name_valid'] = "Vous devez entrer une étiquette de serveur.";
$lang['Centoswebpanel.!error.host_name_valid'] = "Le nom d'hôte (Hostname) semble être invalide
";
$lang['Centoswebpanel.!error.user_name_valid'] = "Le nom d'utilisateur semble être invalide.";
$lang['Centoswebpanel.!error.remote_api_key_valid'] = "La clé API semble être invalide.";
$lang['Centoswebpanel.!error.remote_api_key_valid_connection'] = "Une connexion au serveur n'a pas pu être établie. Veuillez vérifier que le nom d'hôte et la clé d'API sont corrects.";
$lang['Centoswebpanel.!error.account_limit_valid'] = "La limite du compte doit être laissée vide (pour les comptes illimités) ou défini à une valeur entière.";
$lang['Centoswebpanel.!error.name_servers_valid'] = "Un ou plusieurs de serveurs de noms entrés ne sont pas valides.";
$lang['Centoswebpanel.!error.name_servers_count'] = "Vous devez définir au moins 2 serveurs de noms.";
$lang['Centoswebpanel.!error.meta[package].empty'] = "Un forfait CentOS WebPanel est requis.";
$lang['Centoswebpanel.!error.meta[inode].valid'] = "Le nombre maximal d'inodes doit être une valeur numérique.";
$lang['Centoswebpanel.!error.meta[nofile].valid'] = "Le nombre maximum de fichiers doit être une valeur numérique.";
$lang['Centoswebpanel.!error.meta[nproc].valid'] = "Le nombre de processus maximum doit être une valeur numérique.";
$lang['Centoswebpanel.!error.api.internal'] = "Une erreur interne s'est produite, ou le serveur n'a pas répondu à la demande.";
$lang['Centoswebpanel.!error.module_row.missing'] = "Une erreur interne est survenue. La ligne de module est indisponible.";
$lang['Centoswebpanel.!error.centoswebpanel_domain.format'] = "Veuillez entrer un nom de domaine valide, par exemple domain.com.";
$lang['Centoswebpanel.!error.centoswebpanel_domain.test'] = "Le nom de domaine ne peut pas commencer par 'test'.";
$lang['Centoswebpanel.!error.centoswebpanel_username.format'] = "Le nom d'utilisateur peut contenir uniquement des lettres et des chiffres et ne pas commencer par un chiffre.";
$lang['Centoswebpanel.!error.centoswebpanel_username.test'] = "Le nom d'utilisateur ne peut pas commencer par 'test'.";
$lang['Centoswebpanel.!error.centoswebpanel_username.length'] = "Le nom d'utilisateur doit comporter entre 1 et 16 caractères.";
$lang['Centoswebpanel.!error.centoswebpanel_password.valid'] = "Le mot de passe doit comporter au moins 8 caractères.";
$lang['Centoswebpanel.!error.centoswebpanel_password.matches'] = "Le mot de passe et confirmer le mot de passe ne correspondent pas.";
?>