<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Plesk.!error.simplexml_required'] = "L'extension Simplexml est requise pour ce module.";
$lang['Plesk.!error.api.internal'] = "Une erreur interne s'est produite, ou le serveur n'a pas répondu à la demande.";
$lang['Plesk.!error.server_name.empty'] = "Vous devez fournir une étiquette pour le serveur.";
$lang['Plesk.!error.host_name.valid'] = "L'adresse IP semble invalide";
$lang['Plesk.!error.port.format'] = "Le numéro de port doit être un nombre.";
$lang['Plesk.!error.username.empty'] = "Veuillez entrer un nom d'utilisateur.";
$lang['Plesk.!error.password.empty'] = "Veuillez entrer un mot de passe.";
$lang['Plesk.!error.panel_version.valid'] = "Veuillez choisir votre version de Plesk Panel";
$lang['Plesk.!error.meta[plan].empty'] = "Veuillez choisir un plan de service.";
$lang['Plesk.!error.meta[reseller_plan].empty'] = "Veuillez choisir un plan revendeur.";
$lang['Plesk.!error.meta[type].valid'] = "Le compte doit être soit Standard ou Revendeur.";
$lang['Plesk.!error.plesk_domain.format'] = "Veuillez entrer un nom de domaine valide, par exemple domaine.com";
$lang['Plesk.!error.plesk_username.length'] = "Le nom d'utilisateur doit être entre 1 et 60 caractères de long.";
$lang['Plesk.!error.plesk_password.length'] = "Le mot de passe doit avoir entre 5 et 14 caractères de long.";
$lang['Plesk.!error.plesk_confirm_password.matches'] = "Les mots de passe ne concordent pas.";
$lang['Plesk.!error.plesk_webspace_id.exists'] = "L'ID d'inscription fournie n'existe pas dans Plesk.";
$lang['Plesk.!error.downgrade.unsupported'] = "Le déclassement d'un compte de revendeur à un compte non-revendeur n'est pas pris en charge.";
$lang['Plesk.please_select'] = "-- Veuillez choisir --";
$lang['Plesk.tab_stats'] = "Statistiques";
$lang['Plesk.tab_client_stats'] = "Statistiques";
$lang['Plesk.stats.unlimited'] = "Illimité";
$lang['Plesk.!bytes.value'] = "%1\$s %2\$s"; // %1$s is a number value, %2$s is the unit of that value (i.e., one of B, KB, MB, GB)
$lang['Plesk.tab_stats.info_title'] = "Information";
$lang['Plesk.tab_stats.bandwidth_title'] = "Bande passante";
$lang['Plesk.tab_stats.disk_title'] = "Disque";
$lang['Plesk.tab_stats.info_heading.field'] = "Champ";
$lang['Plesk.tab_stats.info_heading.value'] = "Valeur";
$lang['Plesk.tab_stats.bandwidth_heading.used'] = "Utilisé";
$lang['Plesk.tab_stats.bandwidth_heading.limit'] = "Limite";
$lang['Plesk.tab_stats.disk_heading.used'] = "Utilisé";
$lang['Plesk.tab_stats.disk_heading.limit'] = "Limite";
$lang['Plesk.tab_stats.info.domain'] = "Domaine";
$lang['Plesk.tab_stats.info.ip_address'] = "Adresse IP";
$lang['Plesk.tab_client_stats.info_title'] = "Information";
$lang['Plesk.tab_client_stats.info_heading.field'] = "Champ";
$lang['Plesk.tab_client_stats.info_heading.value'] = "Valeur";
$lang['Plesk.tab_client_stats.info.domain'] = "Domaine";
$lang['Plesk.tab_client_stats.info.ip_address'] = "Adresse IP";
$lang['Plesk.name'] = "Plesk";
$lang['Plesk.module_row'] = "Serveur";
$lang['Plesk.module_row_plural'] = "Serveurs";
$lang['Plesk.module_group'] = "Groupe de serveurs";
$lang['Plesk.service_field.domain'] = "Domaine";
$lang['Plesk.service_field.username'] = "Nom d'utilisateur";
$lang['Plesk.service_field.password'] = "Mot de passe";
$lang['Plesk.service_field.confirm_password'] = "Confirmer le mot de passe";
$lang['Plesk.service_field.webspace_id'] = "Identifiant d'abonnement (espace Web)";
$lang['Plesk.service_field.tooltip.username'] = "Vous pouvez laisser le champ du nom d'utilisateur vide pour en générer un automatiquement.";
$lang['Plesk.service_field.tooltip.password'] = "Vous pouvez laissez le mot de passe vide pour en générer un automatiquement.";
$lang['Plesk.service_field.tooltip.webspace_id'] = "Définir un identifiant d'abonnement seulement si vous ne provisionnez pas ce service avec le module. Elle peut être utilisée pour certaines requêtes d'API.";
$lang['Plesk.service_field.tooltip.webspace_id_edit'] = "L'ID de l'abonnement ne sera modifié que localement. Il ne sera pas modifié dans Plesk.";
$lang['Plesk.package_fields.plan'] = "Plan de service Plesk";
$lang['Plesk.package_fields.type'] = "Type de compte";
$lang['Plesk.package_fields.type_standard'] = "Standard";
$lang['Plesk.package_fields.type_reseller'] = "Revendeur";
$lang['Plesk.package_fields.reseller_plan'] = "Plan de compte revendeur";
$lang['Plesk.service_info.username'] = "Nom d'utilisateur";
$lang['Plesk.service_info.password'] = "Mot de passe";
$lang['Plesk.service_info.server'] = "Serveur";
$lang['Plesk.add_row.box_title'] = "Ajouter un serveur Plesk";
$lang['Plesk.add_row.basic_title'] = "Paramètres de base";
$lang['Plesk.add_row.add_btn'] = "Ajouter un serveur";
$lang['Plesk.edit_row.box_title'] = "Modifier le serveur Plesk";
$lang['Plesk.edit_row.basic_title'] = "Paramètres de base";
$lang['Plesk.edit_row.add_btn'] = "Modifier le serveur";
$lang['Plesk.row_meta.server_name'] = "Étiquette serveur";
$lang['Plesk.row_meta.ip_address'] = "Adresse IP";
$lang['Plesk.row_meta.port'] = "Port";
$lang['Plesk.row_meta.username'] = "Nom d'utilisateur";
$lang['Plesk.row_meta.password'] = "Mot de passe";
$lang['Plesk.row_meta.panel_version'] = "Version de Plesk Panel";
$lang['Plesk.order_options.first'] = "Premier serveur non-plein";
$lang['Plesk.add_module_row'] = "Ajouter un serveur";
$lang['Plesk.add_module_group'] = "Ajouter un groupe de serveurs";
$lang['Plesk.manage.module_rows_title'] = "Serveurs";
$lang['Plesk.manage.module_groups_title'] = "Groupes de serveurs";
$lang['Plesk.manage.module_rows_heading.name'] = "Étiquette serveur";
$lang['Plesk.manage.module_rows_heading.ip_address'] = "Adresse IP";
$lang['Plesk.manage.module_rows_heading.options'] = "Options";
$lang['Plesk.manage.module_groups_heading.name'] = "Nom de groupe";
$lang['Plesk.manage.module_groups_heading.servers'] = "Nombre de serveurs";
$lang['Plesk.manage.module_groups_heading.options'] = "Options";
$lang['Plesk.manage.module_rows.edit'] = "Modifier";
$lang['Plesk.manage.module_groups.edit'] = "Modifier";
$lang['Plesk.manage.module_rows.delete'] = "Effacer";
$lang['Plesk.manage.module_groups.delete'] = "Effacer";
$lang['Plesk.manage.module_rows.confirm_delete'] = "Êtes-vous sur de vouloir effacer ce serveur?";
$lang['Plesk.manage.module_groups.confirm_delete'] = "Êtes-vous sur de vouloir effacer ce groupe de serveurs?";
$lang['Plesk.manage.module_rows_no_results'] = "Il n'y a pas de serveurs.";
$lang['Plesk.manage.module_groups_no_results'] = "Il n'y a pas de groupes de serveurs.";
$lang['Plesk.panel_version.windows'] = "Windows";
$lang['Plesk.panel_version.linux'] = "Linux/Unix";
$lang['Plesk.panel_version.plesk_type'] = "Plesk %1\$s pour %2\$s"; // %1$s is the Plesk panel version number, %2$s is the OS type (i.e. Windows or Linux/Unix)
$lang['Plesk.panel_version.plesk'] = "Plesk %1\$s"; // %1$s is the Plesk panel version number
$lang['Plesk.panel_version.parallels'] = "Parallels Plesk Panel %1\$s"; // %1$s is the Plesk panel version number
$lang['Plesk.!error.reseller.valid'] = "Vous devez préciser si ce compte est un compte revendeur ou non.";
$lang['Plesk.!error.api.webspace_delete_filter_missing'] = "Filtre manquant pour effacer un abonnement spécifique.";
$lang['Plesk.!error.api.customer_delete_filter_missing'] = "Filtre manquant pour la suppression d'un client spécifique.";
$lang['Plesk.!error.api.reseller_delete_filter_missing'] = "Filtre manquant pour effacer un revendeur spécifique.";
$lang['Plesk.service_info.options'] = "Options";
$lang['Plesk.service_info.option_login'] = "Connexion";
$lang['Plesk.row_meta.reseller'] = "Compte revendeur";
$lang['Plesk.row_meta.tooltip.reseller'] = "Cochez cette case si c'est un compte revendeur Plesk . Les comptes d'administrateurs de Parallels Plesk Panel peuvent laisser cette case décochée.";
$lang['Plesk.tab_client_stats.usage'] = "(%1\$s/%2\$s)"; // %1$s is the amount of resource usage, %2$s is the resource usage limit
$lang['Plesk.tab_client_stats.not_available'] = "Non Disponible";
$lang['Plesk.tab_client_stats.disk_title'] = "Utilisation de l'espace disque";
$lang['Plesk.tab_client_stats.bandwidth_title'] = "Utilisation de la bande passante";
$lang['Plesk.row_meta.tooltip.version'] = "Chaque version de Plesk prend en charge plusieurs versions de l'API XML publiées avec et avant cette version de Plesk. Par conséquent, les versions les plus récentes sont compatibles avec les versions antérieures.";
$lang['Plesk.panel_version.latest'] = "Utiliser la dernière version (recommandé)";
?>