<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Alipay.name'] = "Alipay";
$lang['Alipay.merchant_email'] = "E-mail du marchand";
$lang['Alipay.merchant_uid'] = "UID/PID du marchand";
$lang['Alipay.signature_key'] = "Clé de signature";
$lang['Alipay.dev_mode'] = "Mode développeur";
$lang['Alipay.dev_mode_note'] = "L'activation de cette option enregistrera les transactions dans l'environnement Sandbox d'Alipay. Activez cette option uniquement si vous testez avec un compte Sanbox d'Alipay.";
$lang['Alipay.buildprocess.submit'] = "Payer avec Alipay";
$lang['Alipay.!error.merchant_email.valid'] = "Vous devez entrer une adresse e-mail valide.";
$lang['Alipay.!error.merchant_uid.valid'] = "Vous devez entrer un UID / PID de marchand valide.";
$lang['Alipay.!error.signature_key.valid'] = "Vous devez entrer une clé de signature valide.";
?>