<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderTypeRegistration.name'] = "Enregistrement du client";
$lang['OrderTypeRegistration.!success.signup'] = "Merci d'avoir créé un compte chez nous.";
$lang['OrderTypeRegistration.!error.template.valid'] = "L'enregistrement du client ne prend en charge que le modèle standard.";
?>