<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PricingPresenter.nested_identifier'] = "?";
$lang['PricingPresenter.description.tax'] = "%1\$s (%2\$s%%)"; // %1$s is the tax name, %2$s is the tax amount
$lang['PricingPresenter.description.coupon.amount'] = "Coupon %1\$s (%2\$s)"; // %1$s is the coupon code, %2$s is the formatted coupon amount
$lang['PricingPresenter.description.coupon.percent'] = "Coupon %1\$s (%2\$s %%)"; // %1$s is the coupon code, %2$s is the coupon percentage amount
$lang['PricingPresenter.description.package'] = "%1\$s"; // %1$s is the name of the package
$lang['PricingPresenter.description.package.setup_fee'] = "%1\$s Prix de l'installation"; // %1$s is the name of the package
$lang['PricingPresenter.description.package.cancel_fee'] = "%1\$s Frais d'annulation"; // %1$s is the name of the package
$lang['PricingPresenter.description.package.prorate.add'] = "Ajout au prorata de %1\$s (%2\$s - %3\$s)"; // %1$s is the name of the package, %2$s is the prorated start date, %3$s is the prorated end date
$lang['PricingPresenter.description.package.prorate.remove'] = "Crédit au prorata de %1\$s (%2\$s - %3\$s)"; // %1$s is the name of the package, %2$s is the prorated start date, %3$s is the prorated end date
$lang['PricingPresenter.description.service'] = "%1\$s - %2\$s"; // %1$s is the name of the package, %2$s is the name of the service
$lang['PricingPresenter.description.service.setup_fee'] = "%1\$s - %2\$s Frais d'installation"; // %1$s is the name of the package, %2$s is the name of the service
$lang['PricingPresenter.description.service.cancel_fee'] = "%1\$s - %2\$s Frais d'annulation"; // %1$s is the name of the package, %2$s is the name of the service
$lang['PricingPresenter.description.service.prorate.add'] = "Ajout au prorata de %1\$s - %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the package, %2$s is the name of the service, %3$s is the prorated start date, %4$s is the prorated end date
$lang['PricingPresenter.description.service.prorate.remove'] = "Crédit au Pro Rata de %1\$s - %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the package, %2$s is the name of the service, %3$s is the prorated start date, %4$s is the prorated end date
$lang['PricingPresenter.description.service.option'] = "%1\$s - %2\$s"; // %1$s is the package option label, %2$s is the package option name
$lang['PricingPresenter.description.service.option.qty'] = "%1\$s - %2\$sx %3\$s"; // %1$s is the package option label, %2$s is the package option quantity, %3$s is the package option name
$lang['PricingPresenter.description.service.option.setup_fee'] = "%1\$s - %2\$s Frais d'installation"; // %1$s is the package option label, %2$s is the package option name
$lang['PricingPresenter.description.service.option.prorate.add'] = "Ajout au prorata de %1\$s - %2\$s (%3\$s - %4\$s)"; // %1$s is the package option label, %2$s is the package option name, %3$s is the prorated start date, %4$s is the prorated end date
$lang['PricingPresenter.description.service.option.prorate.remove'] = "Crédit au prorata de %1\$s - %2\$s (%3\$s - %4\$s)"; // %1$s is the package option label, %2$s is the package option name, %3$s is the prorated start date, %4$s is the prorated end date
$lang['PricingPresenter.description.service.option.qty.prorate.add'] = "Ajout au prorata de %1\$s - %2\$s x %3\$s (%4\$s - %5\$s)"; // %1$s is the package option label, %2$s is the package option quantity, %3$s is the package option name, %4$s is the prorated start date, %5$s is the prorated end date
$lang['PricingPresenter.description.service.option.qty.prorate.remove'] = "Crédit au prorata de %1\$s - %2\$sx %3\$s (%4\$s - %5\$s)"; // %1$s is the package option label, %2$s is the package option quantity, %3$s is the package option name, %4$s is the prorated start date, %5$s is the prorated end date
?>