<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientMain.index.page_title'] = "Téléchargements";
$lang['ClientMain.index.boxtitle_downloads'] = "Téléchargements";
$lang['ClientMain.index.no_downloads'] = "Il n'y a pas de téléchargement disponibles dans cette section.";
$lang['ClientMain.!text.root_directory'] = "Accueil ";
$lang['ClientMain.index.login'] = "Vous devez vous connecter pour voir les téléchargements dans cette section";
?>