<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerCategories.!error.parent_id.exists'] = "La catégorie parente sélectionnée n'existe pas.";
$lang['DownloadManagerCategories.!error.parent_id.loop'] = "La catégorie parent sélectionnée ne peut être la catégorie elle-même.";
$lang['DownloadManagerCategories.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['DownloadManagerCategories.!error.name.empty'] = "Veuillez entrer un nom de catégorie.";
$lang['DownloadManagerCategories.!error.description.empty'] = "Veuillez entrer une description de catégorie.";
$lang['DownloadManagerCategories.!error.category_id.exists'] = "La catégorie étant mis à jour n'existe pas.";
?>