<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerManagePlugin.!success.category_added'] = "La catégorie a été créée avec succès.";
$lang['DownloadManagerManagePlugin.!success.category_updated'] = "La catégorie a été mise à jour avec succès.";
$lang['DownloadManagerManagePlugin.!success.category_deleted'] = "Cette catégorie a été effacée avec succès.";
$lang['DownloadManagerManagePlugin.!success.file_added'] = "Le fichier a été ajouté avec succès.";
$lang['DownloadManagerManagePlugin.!success.file_updated'] = "Le fichier a été mis à jour avec succès.";
$lang['DownloadManagerManagePlugin.!success.file_deleted'] = "Le fichier a été effacé avec succès.";
$lang['DownloadManagerManagePlugin.!tooltip.path_to_file'] = "Entrez le chemin absolu au fichier sur le système de fichiers.";
$lang['DownloadManagerManagePlugin.!text.open_parenthesis'] = "(";
$lang['DownloadManagerManagePlugin.!text.forward_slash'] = "/";
$lang['DownloadManagerManagePlugin.!text.closed_parenthesis'] = ")";
$lang['DownloadManagerManagePlugin.modal.delete_file'] = "Êtes-vous sur de vouloir effacer ce fichier?";
$lang['DownloadManagerManagePlugin.modal.delete_category'] = "Etes-vous sûr de vouloir effacer cette catégorie? Tous les sous-catégories et les fichiers de cette catégorie seront déplacés vers la catégorie parente.";
$lang['DownloadManagerManagePlugin.index.page_title'] = "Gestionnaire de téléchargement ­­­> Gestion";
$lang['DownloadManagerManagePlugin.index.boxtitle_downloadmanager'] = "Gestionnaire de téléchargement";
$lang['DownloadManagerManagePlugin.index.add_download'] = "Ajouter un téléchargement ici";
$lang['DownloadManagerManagePlugin.index.add_category'] = "Ajouter une catégorie ici";
$lang['DownloadManagerManagePlugin.index.go_back'] = "Monter d'un niveau";
$lang['DownloadManagerManagePlugin.index.edit'] = "Éditer";
$lang['DownloadManagerManagePlugin.index.delete'] = "Effacer";
$lang['DownloadManagerManagePlugin.index.no_downloads'] = "Il n'y a pas de téléchargements dans cette section.";
$lang['DownloadManagerManagePlugin.add.page_title'] = "Gestionnaire de téléchargement > Ajout d'un fichier";
$lang['DownloadManagerManagePlugin.add.boxtitle_root'] = "Ajouter le téléchargement à %1\$s"; // %1$s is the name of the root directory
$lang['DownloadManagerManagePlugin.add.boxtitle_add'] = "Ajouter des téléchargements à la catégorie [%1\$s]"; // %1$s is the name of the category the download is to be uploaded to
$lang['DownloadManagerManagePlugin.add.field_public'] = "Disponible publiquement";
$lang['DownloadManagerManagePlugin.add.field_logged_in'] = "Doit être connecté";
$lang['DownloadManagerManagePlugin.add.field_name'] = "Nom";
$lang['DownloadManagerManagePlugin.add.field_available_to_client_groups'] = "Disponible pour les groupes de clients";
$lang['DownloadManagerManagePlugin.add.field_available_to_packages'] = "Disponible pour les ensembles";
$lang['DownloadManagerManagePlugin.add.text_clientgroups'] = "Groupes clients sélectionné";
$lang['DownloadManagerManagePlugin.add.text_packagegroups'] = "Ensembles sélectionnés";
$lang['DownloadManagerManagePlugin.add.text_availableclientgroups'] = "Groupes clients disponibles";
$lang['DownloadManagerManagePlugin.add.text_availablepackages'] = "Ensembles disponibles";
$lang['DownloadManagerManagePlugin.add.field_upload'] = "Téléverser le fichier";
$lang['DownloadManagerManagePlugin.add.field_path'] = "Indiquez le chemin du fichier";
$lang['DownloadManagerManagePlugin.add.field_file'] = "Fichier";
$lang['DownloadManagerManagePlugin.add.field_file_name'] = "Chemin du fichier";
$lang['DownloadManagerManagePlugin.add.submit_add'] = "Ajouter téléchargement";
$lang['DownloadManagerManagePlugin.add.submit_cancel'] = "Annuler";
$lang['DownloadManagerManagePlugin.edit.page_title'] = "Gestionnaire de téléchargements > Ajouter un téléchargement";
$lang['DownloadManagerManagePlugin.edit.boxtitle_edit'] = "Télécharger la mise à jour";
$lang['DownloadManagerManagePlugin.edit.field_public'] = "Disponible publiquement";
$lang['DownloadManagerManagePlugin.edit.field_logged_in'] = "Doit être connecté";
$lang['DownloadManagerManagePlugin.edit.field_name'] = "Nom";
$lang['DownloadManagerManagePlugin.edit.field_available_to_client_groups'] = "Disponible au groupes de clients";
$lang['DownloadManagerManagePlugin.edit.field_available_to_packages'] = "Disponible aux groupes";
$lang['DownloadManagerManagePlugin.edit.text_clientgroups'] = "Groupes de clients sélectionnés";
$lang['DownloadManagerManagePlugin.edit.text_packagegroups'] = "Ensembles sélectionnés";
$lang['DownloadManagerManagePlugin.edit.text_availableclientgroups'] = "Groupes clients disponibles";
$lang['DownloadManagerManagePlugin.edit.text_availablepackages'] = "Ensembles disponibles";
$lang['DownloadManagerManagePlugin.edit.field_upload'] = "Téléverser le fichier";
$lang['DownloadManagerManagePlugin.edit.field_path'] = "Spécifiez chemin vers le fichier";
$lang['DownloadManagerManagePlugin.edit.field_file'] = "Fichier";
$lang['DownloadManagerManagePlugin.edit.field_file_name'] = "Chemin du fichier";
$lang['DownloadManagerManagePlugin.edit.submit_edit'] = "Téléchargement mise a jour";
$lang['DownloadManagerManagePlugin.edit.submit_cancel'] = "Annuler";
$lang['DownloadManagerManagePlugin.addcategory.page_title'] = "Gestionnaire de téléchargements> Ajouter une catégorie";
$lang['DownloadManagerManagePlugin.addcategory.boxtitle_root'] = "Ajouter la catégorie à %1\$s"; // %1$s is the name of the root directory
$lang['DownloadManagerManagePlugin.addcategory.boxtitle_addcategory'] = "Ajouoter une catégorie à la catégorie [%1\$s]"; // %1$s is the name of the category that this category is to be nested under
$lang['DownloadManagerManagePlugin.addcategory.field_name'] = "Nom";
$lang['DownloadManagerManagePlugin.addcategory.field_description'] = "Description";
$lang['DownloadManagerManagePlugin.addcategory.submit_add'] = "Créer une catégorie";
$lang['DownloadManagerManagePlugin.addcategory.submit_cancel'] = "Annuler";
$lang['DownloadManagerManagePlugin.editcategory.page_title'] = "Gestionnaire de téléchargements > Mettre à jour la catégorie";
$lang['DownloadManagerManagePlugin.editcategory.boxtitle_editcategory'] = "Mettre à jour la catégorie [%1\$s]"; // %1$s is the name of the category
$lang['DownloadManagerManagePlugin.editcategory.field_name'] = "Nom";
$lang['DownloadManagerManagePlugin.editcategory.field_description'] = "Description";
$lang['DownloadManagerManagePlugin.editcategory.submit_edit'] = "Mettre à jour la catégorie";
$lang['DownloadManagerManagePlugin.editcategory.submit_cancel'] = "Annuler";
$lang['DownloadManagerManagePlugin.!text.root_directory'] = "Répertoire de base";
$lang['DownloadManagerManagePlugin.package_name'] = "%1\$s (%2\$s)"; // %1$s is the package name, %2$s is the package status
?>