<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerLogs.!error.file_id.exists'] = "Ce fichier n'existe pas.";
$lang['DownloadManagerLogs.!error.client_id.exists'] = "Le client n'existe pas.";
$lang['DownloadManagerLogs.!error.contact_id.exists'] = "Le contact n'existe pas.";
?>