<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerFiles.!error.category_id.exists'] = "Veuillez choisir une catégorie valide.";
$lang['DownloadManagerFiles.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['DownloadManagerFiles.!error.name.empty'] = "Merci d'entrer un nom pour ce fichier";
$lang['DownloadManagerFiles.!error.file_name.format'] = "Veuillez téléverser un fichier ou entrer un chemin d'accès valide au fichier.";
$lang['DownloadManagerFiles.!error.public.format'] = "L'option de la disponibilité publique est dans un format non valide.";
$lang['DownloadManagerFiles.!error.public.assignment'] = "Le fichier doit être disponible soit au public, aux groupes de clients, ou aux ensembles.";
$lang['DownloadManagerFiles.!error.permit_client_groups.format'] = "L'option de disponibilité du groupe client est dans un format invalide.";
$lang['DownloadManagerFiles.!error.file_groups.format'] = "Au moins un groupe de clients sélectionnés ne peut être ajouté car il n'existe pas.";
$lang['DownloadManagerFiles.!error.permit_packages.format'] = "L'option de la disponibilité de l'ensemble est dans un format non valide.";
$lang['DownloadManagerFiles.!error.file_packages.format'] = "Au moins un ensemble sélectionné n'as pu être ajouté car il n'existe pas. ";
$lang['DownloadManagerFiles.!error.file_id.exists'] = "Le fichier mis à jour n'existe pas.";
?>