<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Pagseguro.name'] = "PagSeguro";
$lang['Pagseguro.email_id'] = "Courriel";
$lang['Pagseguro.email_note'] = "Entrez votre adresse email PagSeguro.";
$lang['Pagseguro.token'] = "Jeton";
$lang['Pagseguro.token_note'] = "Entrez le jeton de sécurité de 32 caractères qui a été créé dans votre compte PagSeguro.";
$lang['Pagseguro.buildprocess.submit'] = "Payer avec PagSeguro";
$lang['Pagseguro.!error.libxml_required'] = "Les extensions libxml et simplexml sont requises pour cette passerelle.";
$lang['Pagseguro.!error.dom_required'] = "L'extension dom est requise pour cette passerelle.";
$lang['Pagseguro.!error.email.format'] = "Veuillez entré un courriel valide";
$lang['Pagseguro.!error.token.valid'] = "Veuillez entrer votre jeton de sécurité à 32 caractères.";
$lang['Pagseguro.!error.notification.type'] = "Type de notification inconnu:";
$lang['Pagseguro.!error.notification.invalid'] = "Paramètres de notification invalides.";
?>