<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AgingInvoices.name'] = "Anciennes factures";
$lang['AgingInvoices.options.field_status'] = "Statut";
$lang['AgingInvoices.option.any'] = "Tous";
$lang['AgingInvoices.heading.id_code'] = "Facture #";
$lang['AgingInvoices.heading.client_id_code'] = "Client #";
$lang['AgingInvoices.heading.subtotal'] = "Sous-total";
$lang['AgingInvoices.heading.total'] = "Total";
$lang['AgingInvoices.heading.paid'] = "Payé";
$lang['AgingInvoices.heading.currency'] = "Devise";
$lang['AgingInvoices.heading.status'] = "Statut";
$lang['AgingInvoices.heading.date_billed'] = "Date facturé";
$lang['AgingInvoices.heading.date_due'] = "Date d'échéance";
$lang['AgingInvoices.heading.past30'] = "30";
$lang['AgingInvoices.heading.past60'] = "60";
$lang['AgingInvoices.heading.past90'] = "90+";
$lang['AgingInvoices.heading.client_first_name'] = "Prénom du client";
$lang['AgingInvoices.heading.client_last_name'] = "Nom de famille du client";
$lang['AgingInvoices.heading.client_email'] = "E-mail du client";
$lang['AgingInvoices.heading.client_numbers'] = "Numéros de téléphone du client";
?>