<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Bitpay.name'] = "Bitpay";
$lang['Bitpay.api_key'] = "Clé API";
$lang['Bitpay.transaction_speed'] = "Vitesse de transaction";
$lang['Bitpay.transaction.speed.high'] = "Haut";
$lang['Bitpay.transaction.speed.medium'] = "Medium";
$lang['Bitpay.transaction.speed.low'] = "Bas";
$lang['Bitpay.transaction_speed_note'] = "La vitesse de transaction détermine la rapidité d'une facture (en Bitpay) peut être considéré comme «confirmée».";
$lang['Bitpay.buildprocess.submit'] = "Payer en utilisant Bitcoin";
$lang['Bitpay.!error.api_key.valid'] = "Veuillez entrer une clé API valide.";
$lang['Bitpay.!error.transaction_speed.valid'] = "Veuillez sélectionner une vitesse de transaction valide.";
$lang['Bitpay.!error.failed.response'] = "La transaction n'as pu être effectuée.";
$lang['Bitpay.!error.payment.invalid'] = "La transaction est invalide et ne peut être traitée.";
$lang['Bitpay.!error.payment.expired'] = "La transaction a expiré et ne peut être traitée.";
?>