<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.health_excellent'] = "Le système est dans un bon état et semble opérer de façon normale.";
$lang['AdminMain.index.health_good'] = "Globalement, le système est en bonne santé, mais il ya quelques éléments qui peuvent nécessiter votre attention.";
$lang['AdminMain.index.health_fair'] = "Il ya quelques problèmes qui affectent la capacité du système à fonctionner normalement.";
$lang['AdminMain.index.health_poor'] = "Il y a de graves problèmes qui affectent la capacité du système à fonctionner normalement. Ceux-ci devraient être résolus dès que possible.";
$lang['AdminMain.index.boxtitle_feed'] = "État du système";
$lang['AdminMain.index.cron_serious'] = "La tâche Cron n'as jamais fonctionné.";
$lang['AdminMain.index.cron_minor'] = "La tâche Cron n'as pas été activée dans les dernières 24 heures.";
$lang['AdminMain.index.cron_configure'] = "Configurer?";
$lang['AdminMain.index.invoices_minor'] = "Les factures n'ont pas été automatiquement créé via Cron au cours des dernières 24 heures.";
$lang['AdminMain.index.invoices_configure'] = "Configurer?";
$lang['AdminMain.index.backup_minor'] = "Aucune sauvegarde n'as été effectuée dans les derniers 7 jours.";
$lang['AdminMain.index.cron_task_stalled_minor'] = "Il y a une ou plusieurs tâches cron qui s'exécutent de puis plus de %1\$s minutes."; // %1$s is the number of minutes
$lang['AdminMain.index.cron_task_stalled_automation'] = "Voir les tâches automatisées";
$lang['AdminMain.index.trial_minor'] = "Votre License d'évaluation expire dans  %1\$s."; // %1$s is the date the trial license expires
$lang['AdminMain.index.trial_buy'] = "Acheter maintenant?";
$lang['AdminMain.index.updates_forever'] = "Le soutien et les mises à jour sont en vigueur éternellement. ";
$lang['AdminMain.index.updates_minor'] = "Le support et les mises à jour sont en vigueur jusqu'à %1\$s."; // %1$s is the date support expires
$lang['AdminMain.index.updates_serious'] = "Votre plan de support et les mises à jours ont expiré le %1\$s."; // %1$s is the date support expired
$lang['AdminMain.index.updates_buy'] = "Ajouter support et mises à jour?";
?>