<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Main.index.heading'] = "Sélection du forfait";
$lang['Main.index.subheading'] = "Sélectionner un groupe de  paquets ci-dessous pour continuer.";
$lang['Main.index.group_heading'] = "Sélectionnez un forfait ci-dessous.";
$lang['Main.index.field_pricing_id'] = "Choisissez votre cycle de facturation.";
$lang['Main.index.button_order'] = "Commander maintenant";
$lang['Main.index.sold_out'] = "En rupture de stock";
$lang['Main.index.field_currency'] = "Devise:";
$lang['Main.packages.subheading'] = "Sélectionnez un forfait, puis configurez-le ci-dessous.";
$lang['Main.packages.select_note'] = "Glisser pour sélectionner un autre forfait.";
$lang['Main.packages.price_start'] = "À partir de";
$lang['Main.packages.box_select'] = "Sélectionner";
$lang['Main.packages.box_selected'] = "Sélectionné";
$lang['Main.packages.box_sold_out'] = "En rupture de stock";
?>