<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['InvoiceCreation.name'] = "Création de facture";
$lang['InvoiceCreation.options.field_start_date'] = "Date de départ";
$lang['InvoiceCreation.options.field_end_date'] = "Date de fin";
$lang['InvoiceCreation.options.field_status'] = "Statut";
$lang['InvoiceCreation.option.any'] = "Tous";
$lang['InvoiceCreation.heading.id_code'] = "Facture #";
$lang['InvoiceCreation.heading.client_id_code'] = "Client #";
$lang['InvoiceCreation.heading.subtotal'] = "Sous-total";
$lang['InvoiceCreation.heading.total'] = "Total";
$lang['InvoiceCreation.heading.paid'] = "Payé";
$lang['InvoiceCreation.heading.currency'] = "Devise";
$lang['InvoiceCreation.heading.status'] = "Statut";
$lang['InvoiceCreation.heading.date_billed'] = "Date facturé";
$lang['InvoiceCreation.heading.date_due'] = "Date due";
$lang['InvoiceCreation.heading.date_closed'] = "Date de fermeture";
?>