<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Payflow.!error.user.empty'] = "Veuillez entrer un utilisateur autorisé à traiter ces transactions.";
$lang['Payflow.!error.vendor.empty'] = "Veuillez entrer votre identifiant de compte marchand.";
$lang['Payflow.!error.partner.empty'] = "Veuillez indiquer votre marchand partenaire.";
$lang['Payflow.!error.test_mode.valid'] = "Le mode de test doit être réglé sur \"vrai\" s'il est indiqué.";
$lang['Payflow.name'] = "PayPal Payflow Pro";
$lang['Payflow.vendor'] = "Connexion vendeur / marchand";
$lang['Payflow.user'] = "Utilisateur";
$lang['Payflow.password'] = "Mot de passe";
$lang['Payflow.partner'] = "Partenaire";
$lang['Payflow.test_mode'] = "Mode test";
$lang['Payflow.tooltip_user'] = "Si vous avez configuré plus d'un utilisateur pour votre compte, entrez l'utilisateur autorisé à traiter les transactions. Sinon, entrez la même valeur que la connexion fournisseur/marchant.";
$lang['Payflow.tooltip_partner'] = "Il s'agit du partenaire commercial que vous a attribué un revendeur PayPal agréé qui vous a enregistré pour le SDK Payflow. Si votre compte a été acheté directement auprès de PayPal, utilisez plutôt \"PayPal\".";
$lang['Payflow.!error.password.format'] = "Veuillez entrer un mot de passe entre 6 et 32 caractères de long.";
?>