<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['_2Checkout.name'] = "2Checkout";
$lang['_2Checkout.vendor_id'] = "ID vendeur";
$lang['_2Checkout.secret_word'] = "Mot secret";
$lang['_2Checkout.api_username'] = "Nom d'utilisateur de l'API";
$lang['_2Checkout.api_username_note'] = "Ceci, ainsi que le mot de passe API, sont nécessaires afin de traiter les remboursements par 2Checkout.";
$lang['_2Checkout.api_password'] = "Mot de passe API";
$lang['_2Checkout.test_mode'] = "Mode de test";
$lang['2Checkout.refund.comment'] = "Tentative de remboursement pour %1\$s."; // %1$s is the refund amount
$lang['_2Checkout.buildprocess.submit'] = "Payer avec 2Checkout";
$lang['_2Checkout.!error.vendor_id.empty'] = "Merci d'entrer votre numéro de compte vendeur.";
$lang['_2Checkout.!error.secret_word.empty'] = "Merci d'entrer votre clé secrète.";
$lang['_2Checkout.!error.test_mode.valid'] = "Le mode Test doit être réglée sur 'Activé' ou 'Désactivé'.";
$lang['_2Checkout.!error.key.valid'] = "La clé utilisée pour vérifier la vente depuis 2Checkout est invalide.";
$lang['_2Checkout.!error.credit_card_processed.completed'] = "La transaction n'a pas été traitée avec succès.";
$lang['_2Checkout.!error.sid.valid'] = "Le numéro de compte client ne correspond au numéro de compte utilisé pour cette transaction.";
?>