<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PayJunction.name'] = "PayJunction";
$lang['PayJunction.api_key'] = "Clé API";
$lang['PayJunction.user_name'] = "Nom d'utilisateur";
$lang['PayJunction.password'] = "Mot de passe";
$lang['PayJunction.test_mode'] = "Mode développeur";
$lang['PayJunction.api_key_note'] = "Veuillez entrer votre clé API de votre compte PayJunction.";
$lang['PayJunction.user_name_note'] = "Entrez votre nom d'utilisateur pour vvotre compte PayJunction.";
$lang['PayJunction.password_note'] = "Entrez le mot de passe de votre compte PayJunction.";
$lang['PayJunction.test_mode_note'] = "L'activation du mode développeur affichera transactions à l'environnement de démonstration PayJunction Labs. Vous devez utiliser le nom d'utilisateur et mot de passe de démonstration, ainsi que votre clé API Labs, pour utiliser le mode de développeur.";
$lang['PayJunction.!error.api_key.empty'] = "Veuillez entrer une clé API valide.";
$lang['PayJunction.!error.user_name.empty'] = "Veuiller entrer votre nom d'utilisateur pour le compte";
$lang['PayJunction.!error.password.empty'] = "Veuillez entrer le mot de passe de votre compte.";
$lang['PayJunction.!error.test_mode.valid'] = "Mode développeur doit être réglé à 'vrai' si donné.";
?>