<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Blesta2_5.!error.host.invalid'] = "L'hôte de base de données est requis.";
$lang['Blesta2_5.!error.database.invalid'] = "Le nom de la base de données est requis.";
$lang['Blesta2_5.!error.user.invalid'] = "le nom d'utilisateur de base de données est requis.";
$lang['Blesta2_5.!error.pass.invalid'] = "Le mot de passe de la base de données est requis.";
$lang['Blesta2_5.!error.key.invalid'] = "Une clé AES valide est requise.";
$lang['Blesta2_5.settings.host'] = "Hôte de base de données";
$lang['Blesta2_5.settings.database'] = "Nom de la base de données";
$lang['Blesta2_5.settings.user'] = "Utilisateur de base de données";
$lang['Blesta2_5.settings.pass'] = "Mot de passe de la Base de donnée";
$lang['Blesta2_5.settings.key'] = "Clé AES";
$lang['Blesta2_5.settings.key.info'] = "Entrez la valeur de la clé AES définie dans /inc/config.php. Elle doit être de 32 caractères.";
$lang['Blesta2_5.configuration.create_packages_true'] = "Créer automatiquement les forfaits nécessaires lors de l'importation";
$lang['Blesta2_5.configuration.create_packages_false'] = "Mapper manuellement les forfaits";
$lang['Blesta2_5.configuration.local_package'] = "Forfait local";
$lang['Blesta2_5.configuration.remote_package'] = "Forfait distant";
$lang['Blesta2_5.configuration.no_local_packages'] = "Vous devez créer des forfaits avant de pouvoir les mapper.";
?>