<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Eway.!error.customer_id.empty'] = "Veuillez entrer votre ID de client eWAY.";
$lang['Eway.!error.customer_id.length'] = "L'ID client ne peut pas dépasser 8 caractères.";
$lang['Eway.!error.developer_mode.valid'] = "Mode développeur doit être réglée sur \"vrai\" si donné.";
$lang['Eway.!error.test_mode.valid'] = "Le mode test doit être à \"vrai\" si donné.";
$lang['Eway.!error.refund_password.empty'] = "Un mot de passe de remboursement doit être réglé afin de traiter les remboursements par eWAY.";
$lang['Eway.!error.libxml_required'] = "Les extension libxml et simplexml sont requis pour cette passerelle.";
$lang['Eway.!error.invalid_xml'] = "La passerelle a répondu avec un XML invalide.";
$lang['Eway.name'] = "eWAY";
$lang['Eway.customer_id'] = "ID client";
$lang['Eway.refund_password'] = "Mot de passe de remboursement";
$lang['Eway.developer_mode'] = "Mode développeur";
$lang['Eway.test_mode'] = "Mode test";
$lang['Eway.tooltip_refund_password'] = "Veuillez entrer le mot de passe de remboursement que vous avez défini dans votre compte eWAY. Ce n'est pas votre mot de passe de votre compte eWAY. Un mot de passe de remboursement doit être réglé afin de traiter les remboursements par eWAY.";
$lang['Eway.tooltip_developer_mode'] = "L'activation de cette option affichera les transactions à l'environnement de test (sandbox) eWAY. Vous devez avoir un compte de test sandbox afin d'utiliser cet environnement.";
$lang['Eway.tooltip_test_mode'] = "Le mode test va utiliser un compte de test eWAY avec un numéro de carte de crédit de test, indépendamment de ce que vous entrez. Pour plus d'informations concernant le mode de test dans eWAY s'il vous plaît consulter le manuel.";
?>