<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CoinPayments.name'] = "CoinPayments.net";
$lang['CoinPayments.merchant_id'] = "ID Marchant CoinPayments";
$lang['CoinPayments.ipn_secret'] = "Secret IPN";
$lang['CoinPayments.buildprocess.submit'] = "Payer avec CoinPayments";
?>