<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Blue_pay.!error.account_id.empty'] = "Veuillez entrer votre ID de compte";
$lang['Blue_pay.!error.secret_key.empty'] = "Veuillez entrer votre clé secrète.";
$lang['Blue_pay.!error.test_mode.valid'] = "Le mode test doit être paramétré à \"vrai\" si donné.";
$lang['Blue_pay.name'] = "BluePay";
$lang['Blue_pay.account_id'] = "ID de compte";
$lang['Blue_pay.secret_key'] = "Clé secrète";
$lang['Blue_pay.test_mode'] = "Mode de test";
?>