<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderTypeDomain.name'] = "Domaine et autre";
$lang['OrderTypeDomain.!error.domain.invalid'] = "Ce nom de domaine n'est pas supporté.";
$lang['OrderTypeDomain.!error.domain.empty'] = "Veuillez entrer un nom de domaine.";
$lang['OrderTypeDomain.!error.template.valid'] = "Le modèle sélectionné nécessite au moins un groupe de forfaits.";
$lang['OrderTypeDomain.settings.domain_group_title'] = "Groupe de forfaits de domaine";
$lang['Main.steps.step_1_description'] = "Choisissez un domaine";
?>