<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.options_updated'] = "Les options de la vue d'ensemble de la facturation ont été mis à jour avec succès!";
$lang['AdminMain.index.boxtitle_overview'] = "Vue d'ensemble de la facturation";
$lang['AdminMain.index.statistic.revenue_today'] = "Revenus du jour";
$lang['AdminMain.index.statistic.revenue_month'] = "Revenu pour ce mois";
$lang['AdminMain.index.statistic.invoiced_today'] = "Facturé aujourd'hui";
$lang['AdminMain.index.statistic.invoiced_month'] = "Facturé ce mois";
$lang['AdminMain.index.statistic.balance_outstanding'] = "Solde en cours";
$lang['AdminMain.index.statistic.balance_overdue'] = "Solde en retard";
$lang['AdminMain.index.statistic.scheduled_cancelation'] = "Annulations prévues";
$lang['AdminMain.index.statistic.services_active'] = "Services actifs";
$lang['AdminMain.index.statistic.services_added_today'] = "Services ajoutés aujourd'hui";
$lang['AdminMain.index.statistic.services_canceled_today'] = "Services annulés aujourd'hui";
$lang['AdminMain.settings.text_options'] = "Validez les options qui apparaîtrons sur la vue d'ensemble de la facturation.";
$lang['AdminMain.settings.heading_statistics'] = "Statistiques";
$lang['AdminMain.settings.heading_graphs'] = "Graphiques";
$lang['AdminMain.settings.heading_graph_settings'] = "Paramètres des graphiques";
$lang['AdminMain.settings.revenue_today'] = "Revenus d'aujourd'hui";
$lang['AdminMain.settings.revenue_month'] = "Revenu du mois";
$lang['AdminMain.settings.invoiced_today'] = "Facturé aujourd'hui";
$lang['AdminMain.settings.invoiced_month'] = "Facturé ce mois ci ";
$lang['AdminMain.settings.balance_outstanding'] = "Balance due";
$lang['AdminMain.settings.balance_overdue'] = "Solde en souffrance";
$lang['AdminMain.settings.scheduled_cancelation'] = "Annulations prévues";
$lang['AdminMain.settings.services_active'] = "Services actifs";
$lang['AdminMain.settings.services_added_today'] = "Services ajoutés aujourd'hui";
$lang['AdminMain.settings.services_canceled_today'] = "Services annulés aujourd'hui";
$lang['AdminMain.settings.text_graphs'] = "Validez quels graphiques devraient apparaître dans le survol de facturation.";
$lang['AdminMain.settings.graph_invoiced'] = "Graphique des montants facturés";
$lang['AdminMain.settings.text_graph_settings'] = "Gérer les paramètres de graphique pour les graphiques qui apparaîtront sur la vue d'ensemble de la facturation.";
$lang['AdminMain.settings.show_legend'] = "Montrer les légendes des graphiques";
$lang['AdminMain.settings.date_range'] = "Période du graphique";
$lang['AdminMain.settings.submit_settings'] = "Mettre à jour les paramètres";
$lang['AdminMain.settings.submit_cancel'] = "Retour à la vue d'ensemble";
$lang['AdminMain.date_range.days'] = "jours";
$lang['AdminMain.graph_name.graph_invoiced'] = "Montant facturé";
$lang['AdminMain.graph_line_name.total'] = "Total";
$lang['AdminMain.graph_line_name.credit'] = "Carte de crédit";
$lang['AdminMain.graph_line_name.ach'] = "ACH";
$lang['AdminMain.graph_line_name.other'] = "Autre";
$lang['AdminMain.index.statistic.revenue_year'] = "Revenus pour cette année";
$lang['AdminMain.settings.revenue_year'] = "Revenus pour l'année";
$lang['AdminMain.settings.graph_revenue_year'] = "Graphique des Revenus (Sur un an)";
$lang['AdminMain.graph_name.graph_revenue_year'] = "Chiffre d'affaires (sur un an)";
$lang['AdminMain.settings.graph_revenue'] = "Graphiques des revenus (éventail)";
$lang['AdminMain.graph_name.graph_revenue'] = "Revenus (fourchette)";
$lang['AdminMain.index.statistic.credits_today'] = "Crédits aujourd'hui";
$lang['AdminMain.index.statistic.credits_month'] = "Crédits ce mois";
$lang['AdminMain.index.statistic.credits_year'] = "Crédits cette année";
$lang['AdminMain.settings.credits_today'] = "Crédits aujourd'hui";
$lang['AdminMain.settings.credits_month'] = "Crédits ce mois";
$lang['AdminMain.settings.credits_year'] = "Crédits cette année";
$lang['AdminMain.graph_line_name.credits'] = "Crédits";
$lang['AdminMain.index.statistic.invoiced_today_proforma'] = "Facturé aujourd'hui (Proforma)";
$lang['AdminMain.index.statistic.invoiced_month_proforma'] = "Facturé ce mois(Proforma)";
$lang['AdminMain.settings.invoiced_today_proforma'] = "Facturé aujourd'hui (Proforma)";
$lang['AdminMain.settings.invoiced_month_proforma'] = "Facturé ce mois-(Proforma)";
?>