<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['BillingOverviewSettings.!error.staff_id.exists'] = "Code incorrect du personnel.";
$lang['BillingOverviewSettings.!error.company_id.exists'] = "ID de compagnie invalide.";
$lang['BillingOverviewSettings.!error.settings[][key].empty'] = "Pas de paramètre. La clef doit être vide.";
$lang['BillingOverviewSettings.!error.settings[][value].length'] = "Chaque longueur de la valeur de réglage individuel ne peut pas dépasser 255 caractères.";
?>