<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.feed_added'] = "Le flux a été ajouté avec succès.";
$lang['AdminMain.!success.feed_refreshed'] = "Le flux a été rafraîchi avec succès.";
$lang['AdminMain.!success.feed_removed'] = "Le flux a été enlevé avec succès.";
$lang['AdminMain.index.boxtitle_feed'] = "Lecteur de flux";
$lang['AdminMain.index.no_results'] = "Il n'y a pas de résultats de flux.";
$lang['AdminMain.index.last_updated'] = "Dernière mise à jour: %1\$s"; // %1$s is a date/time stamp of the last time the feed was updated
$lang['AdminMain.add.boxtitle_feed'] = "Ajouter un flux";
$lang['AdminMain.add.field_url'] = "URL";
$lang['AdminMain.add.submit_add'] = "Ajouter un flux";
$lang['AdminMain.add.submit_cancel'] = "Annuler";
$lang['AdminMain.settings.no_feeds'] = "Il n'y a pas de flux.";
$lang['AdminMain.settings.add_feed'] = "Ajouter un flux";
$lang['AdminMain.settings.submit_cancel'] = "Retourner aux flux";
$lang['AdminMain.settings.heading_url'] = "Adresse";
$lang['AdminMain.settings.heading_lastupdated'] = "Dernière mise à jour";
$lang['AdminMain.settings.heading_options'] = "Options";
$lang['AdminMain.settings.option_refresh'] = "Rafraîchir";
$lang['AdminMain.settings.option_remove'] = "Enlever";
?>