<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderManagePlugin.!success.feed_added'] = "Le flux a été ajouté avec succès.";
$lang['FeedReaderManagePlugin.!success.feed_refreshed'] = "Les flux ont été rafraîchis avec succès.";
$lang['FeedReaderManagePlugin.!success.feed_removed'] = "Le flux a été supprimé avec succès.";
$lang['FeedReaderManagePlugin.index.boxtitle_feedreader'] = "Lecteur de flux";
$lang['FeedReaderManagePlugin.index.add_feed'] = "Ajouter un flux";
$lang['FeedReaderManagePlugin.index.heading_url'] = "URL";
$lang['FeedReaderManagePlugin.index.heading_lastupdated'] = "Dernière mise à jour";
$lang['FeedReaderManagePlugin.index.heading_options'] = "Options";
$lang['FeedReaderManagePlugin.index.option_refresh'] = "Rafraîchir";
$lang['FeedReaderManagePlugin.index.option_remove'] = "Supprimer";
$lang['FeedReaderManagePlugin.index.no_feeds'] = "Il n'y a pas de flux par défaut.";
$lang['FeedReaderManagePlugin.add.boxtitle_feed'] = "Ajouter un flux";
$lang['FeedReaderPlugin.add.field_url'] = "URL";
$lang['FeedReaderPlugin.add.submit_add'] = "Ajouter un flux";
$lang['FeedReaderPlugin.add.submit_cancel'] = "Annuler";
$lang['FeedReaderManagePlugin.index.page_title'] = "Lecteur de Flux > Gérer";
$lang['FeedReaderManagePlugin.add.page_title'] = "Flux > Ajouter un flux";
$lang['FeedReaderManagePlugin.index.text_confirm_delete'] = "Voulez-vous vraiment supprimer ce flux?";
?>