<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderPlugin.!error.libxml_required'] = "L'extension libxml est requise pour ce plugin.";
$lang['FeedReaderPlugin.!error.dom_required'] = "L'extension DOM est requise pour ce plugin.";
$lang['FeedReaderPlugin.name'] = "Lecteur de flux";
?>