<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderFeeds.!error.url.valid'] = "L'URL donnée n'est pas valide";
$lang['FeedReaderFeeds.!error.company_id.exists'] = "La compagnie spécifiée n'existe pas.";
$lang['FeedReaderFeeds.!error.updated.valid'] = "Vous devez spécifier une date de mise à jour valide.";
$lang['FeedReaderFeeds.!error.feed_id.exists'] = "Le flux indiqué n'existe pas.";
$lang['FeedReaderFeeds.!error.staff_id.exists'] = "Le membre du personnel spécifié n'existe pas.";
$lang['FeedReaderFeeds.!error.date.valid'] = "Les données spécifiées n'est pas valide.";
?>