<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Checkout.index.header_checkout'] = "Passer à la caisse";
$lang['Checkout.index.header_paymethod'] = "Choisissez votre mode de paiement";
$lang['Checkout.index.field_useaccount'] = "Utiliser un compte de paiement";
$lang['Checkout.index.field_newdetails'] = "Nouveaux détails de paiement";
$lang['Checkout.index.heading_other_payment_options'] = "Autres options de paiement";
$lang['Checkout.index.heading_payment_options'] = "Options de paiement";
$lang['Checkout.index.apply_credit'] = "Appliquer un crédit (%1\$s disponible)"; // %1$s is the amount of credit available
$lang['Checkout.index.pay_btn'] = "Envoyer la commande";
$lang['Checkout.index.pay_credit_btn'] = "Appliquer le crédit et envoyer la commande";
$lang['Checkout.index.continue_btn'] = "Continuer";
$lang['Checkout.index.no_options'] = "Il n'y a pas d'options de paiement disponibles.";
$lang['Checkout.contact_info.heading_contact'] = "Informations de contact";
$lang['Checkout.contact_info.field_contact_id'] = "Copier les informations de contact depuis";
$lang['Checkout.contact_info.text_select_contact'] = "Vous pouvez sélectionner un contact existant pour pré-renseigner ce formulaire.";
$lang['Checkout.cc_info.heading_cc'] = "Information de carte de crédit";
$lang['Checkout.ach_info.heading_ach'] = "Information de compte bancaire";
$lang['Checkout.complete.header_complete'] = "Commande terminée";
$lang['Checkout.complete.header_almost_complete'] = "On y est presque....";
$lang['Checkout.complete.order_more_btn'] = "Passer une autre commande";
?>