<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.index.header_configuration'] = "Configuration";
$lang['Config.index.header_configure_service'] = "Configurer %1\$s"; // %1$s is the service name to configure
$lang['Config.index.header_term'] = "Durée et prix";
$lang['Config.index.header_module'] = "Options configurables"; // %1$s is the name of the module
$lang['Config.index.header_addons'] = "Compléments disponibles";
$lang['Config.index.continue_btn'] = "Continuer";
?>