<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Domain.lookup.title'] = "Vérifier la disponibilité du domaine";
$lang['Domain.lookup.domain_placeholder'] = "votredomaine.com";
$lang['Domain.lookup.transfer_btn'] = "Transférer ";
$lang['Domain.lookup.lookup_btn'] = "Vérifier la disponibilité";
$lang['Domain.lookup.other_btn'] = "Commander d'autres articles";
$lang['Domain.lookup.domains_header_available'] = "Félicitations, ce domaine est disponible.";
$lang['Domain.lookup.domains_header_unavailable'] = "Désolé, ce domaine n'est pas disponible.";
$lang['Domain.lookup.domains_domain_name'] = "Nom de domaine";
$lang['Domain.lookup.domains_status'] = "Statut";
$lang['Domain.lookup.domains_term'] = "Terme";
$lang['Domain.lookup.domain_available'] = "Disponible";
$lang['Domain.lookup.domain_unavailable'] = "Indisponible";
$lang['Domain.lookup.order_btn'] = "Commande sélectionnée";
$lang['Domain.lookup.term'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the term, %2$s is the period, %3$s is the currency price
$lang['Domain.lookup.term_onetime'] = "%1\$s @ %2\$s"; // %1$s is the period, %2$s is the currency price
?>