<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Main.steps.step_1_name'] = "Étape 1";
$lang['Main.steps.step_1_description'] = "Choisissez votre forfait";
$lang['Main.steps.step_2_name'] = "Étape 2";
$lang['Main.steps.step_2_description'] = "Configuration";
$lang['Main.steps.step_3_name'] = "Étape 3";
$lang['Main.steps.step_3_description'] = "Réviser la commande";
$lang['Main.steps.step_4_name'] = "Étape 4";
$lang['Main.steps.step_4_description'] = "Passer à la caisse";
$lang['Main.index.select_btn'] = "Ajouter au panier";
$lang['Main.index.sold_out'] = "En rupture de stock";
?>