<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Quantum_gateway.!error.gateway_login.empty'] = "Veuillez entrer votre identifiant de passerelle.";
$lang['Quantum_gateway.!error.restrict_key.empty'] = "Veuillez entrer votre clé de restriction.";
$lang['Quantum_gateway.!error.maxmind.valid'] = "Maxmind doit être réglé sur \"vrai\" s'il est défini.";
$lang['Quantum_gateway.name'] = "Passerelle Quantum";
$lang['Quantum_gateway.gateway_login'] = "Connexion de passerelle";
$lang['Quantum_gateway.restrict_key'] = "Clée restreinte";
$lang['Quantum_gateway.maxmind'] = "Utiliser Maxmind";
$lang['Quantum_gateway.tooltip_maxmind'] = "Cochez la case pour activer la répression des fraudes Maxmind. Vérifiez votre panneau de contrôle de QuantumGateway pour les paramètres Maxmind supplémentaires.";
?>