<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.4.0
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SharedLoginManagePlugin.index.page_title'] = "Connexion partagée";
$lang['SharedLoginManagePlugin.index.boxtitle_manage'] = "Connexion partagée";
$lang['SharedLoginManagePlugin.index.field_key'] = "Clé partagée";
$lang['SharedLoginManagePlugin.index.submit'] = "Sauvegarder";
?>